### ISSUE TITLE
sambamba depth CANCELLED DUE TO TIME LIMIT

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#1000]
**Describe the bug**
`sambamba depth` is cancelled due to time limit.

**To Reproduce**
The error occurred when running a tumor-normal TGA sample.

**Expected behavior**
Completion of the workflow and not failing while running `sambamba depth`.

**If workflow, which rules**
`sambamba_exon_depth`

**Version (please complete the following information):**
`balsamic  10.0.3`

**Additional context**
The issue can be resolved by increasing the time limit for the rule `sambamba_exon_depth` in cluster.json and adding threads to the command within the rule.

**Comment by vwirta** [comment]
Nice @ivadym - you closed issue 1000 in Balsamic!
