### ISSUE TITLE
vcf2cytosure version bump 0.8

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/BALSAMIC#1002]
**Current affected rule if snakemake workflow related**
Gentle reminder; the `vcf2cytosure` container should be bumped to 0.8, based on feedback from the somatic side users. 

https://github.com/NBISweden/vcf2cytosure/releases/tag/v0.8

**Comment by dnil** [comment]
Hi looks good, I think, just one question: what dis?
https://github.com/Clinical-Genomics/BALSAMIC/blob/abf01aaaac680093d105ab0b9d4d6e38229c49cf/BALSAMIC/containers/vcf2cytosure/vcf2cytosure.yaml

**Comment by ivadym** [comment]
Hello, @khurrammaqbool merge it to develop in this PR: https://github.com/Clinical-Genomics/BALSAMIC/pull/987 but it has not yet been deployed.

Since it seems that this is urgent I would make a patch to master updating vcf2cytosure and deploy it on Monday.
