### ISSUE TITLE
LOH in Scout from balsamic data (Myeloid panel)

### ISSUE THREAD

**Issue by christacosta** [Clinical-Genomics/BALSAMIC#1009]
Hi,

We need to be able to detect LOH with BALSAMIC and the myeloid panel. Most urgent is to get it for the TP53-gene (kromosom 17p13.1). But if it is genome-wide that's also great! New clinical guidelines require us to report TP53 LOH to the referring hematologists.

There is a rather old issue about this: Ideogram vizualisation in Scout from balsamic data (Myeloid panel) #564, but it doesn't seem like anyone is working on this. 

Hopefully this can be investigated soon!
Thanks a lot in advance! Christa

**Comment by khurrammaqbool** [comment]
This issue is addressed in https://github.com/Clinical-Genomics/BALSAMIC/issues/1105.
