### ISSUE TITLE
Fixing `balsamic init` and references downloads by adding `SLURM` configuration and fixing `singularity` commands 

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#1044]
**Describe the bug**
There are multiple problems with building the reference cache via SLURM. 
Below is the comment left in the `PR` #762 referenced from the `issue` #686 :

`Some minor comments:
It may be nice to have it tested on hg38 as well.
Ashwini and Hassan already discussed the possibility to split the jobs. I suggest, Further improvements may be considered, in future, by submission of each reference as separate job or aggregation of jobs to further reduce cache build time. Ashwini suggested to, at least, split the gnomad_reference download from the rest, which may offer significant improvement.`

In addition to the implementation of the suggestions above, we need to some more changes in SLURM configurations for reference generation. `Singularity` fails to pull containers when the jobs are submitted via `SLURM`, which requires stopping `Singularity` from using `/tmp` and allocating `snakemake` resources in the rules.

**To Reproduce**
`balsamic init` via `SLURM`

**Expected behavior**
`singularity pull` for containers and `reference downloads` fail. 

**If workflow, which rules**
`reference.smk`

**Screenshots**

**Version (please complete the following information):**
`balsamic v11.0.1`

**Additional context**

**Comment by ivadym** [comment]
Addressed in https://github.com/Clinical-Genomics/BALSAMIC/pull/1188
