### ISSUE TITLE
GenMod family missing for ranked files

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/BALSAMIC#1045]
Sorry if this is a duplicate; since we couldn't find the issue this morning, I'm adding it here!

**Describe the bug**
GenMod family/case id is missing from rank score in Balsamic ranking (VarDict research variants so far), as determined way back when in `/home/proj/stage/cancer/validation/2022-06-30/poeticghoul/analysis/vep/SNV.somatic.poeticghoul.vardict.all.filtered.pass.ranked.vcf.gz`. Family_id is `1` here in `ID.RankScore`.

**Expected behavior**
Family ID (case id) should be present in ranked files (compare e.g. MIP) for loading to Scout.
If no family information file (e.g. `.ped`) is available, one can simply give this on a case by case basis: `genmod score --family_id <family_id>`.

**Comment by mathiasbio** [comment]
Hi @dnil ! What is this family id used for? Me and @josefinelantz also noticed that the family_id is always 1 in the scored VCFs. Is it used for something in Scout? I was wondering if it was something that was only relevant for RD

**Comment by dnil** [comment]
Family id is used to connect the score to the case at hand. Pretty redundant currently from a production point of view as we essentially always just score one case at the time. But since it is there, it is also really important for scout loading. 1 is the default genmod inserts. You will need to provide your actual family id when scoring, as per this issue text, either with some form of family file you use or just directly with a CLI option when you run it.

**Comment by mathiasbio** [comment]
Solved by adding family-id to genmod in genmod rule:` -i {params.case_name} ` added in this PR: https://github.com/Clinical-Genomics/BALSAMIC/pull/1475
