### ISSUE TITLE
BALSAMIC v12.0.0 release

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#1048]
## Balsamic features for the next release:

 Balsamic v12

## Alignment
- [ ] #993 : 
  - [ ] Adapt the CLI to accept multiple reads and concatenate the fastqs
  - [ ] Remove concatenation and merge aligned BAM in BALSAMIC 

## Annotation
  - [ ] loqusdb tumor SNV Frequencies for WGS: 
  - [ ] loqusdb tumor SV Frequencies for WGS: 
  - [ ] loqusdb somatic SNV Frequencies for WGS: 
  - [ ] loqusdb somatic SV Frequencies for WGS: 
  - [ ] Update documentation

## Filtering strategy prior to upload to Scout
 - [ ] Add Pre-annotation blacklist filtering: 
 - [ ] Implement filtering against loqusdb tumor and somatic observations: 
 - [ ] Update documentation

## Rescue filtered out variants:
  - [ ] Add Filter PASS: 
  - [ ] Update documentation

## Variant callers
- [ ] Add CNVpytor for WGS T-N analysis
- [ ] Update documentation

## PON
- [ ] Add TNhaplotyper PON : 
- [ ] Generate a panel of normal reference and use it as input for BALSAMIC analysis
- [ ] Update documentation

## Scout
- [ ] Add CNVpytor TN analysis PDF to Scout: 

## Update delivery report
  - [ ] Delivery report for QC only analysis
  - [ ] Update documentation

## File delivery
- [ ] Update stored and delivered files (HERMES & CG)
- [ ] Update documentation
- [ ] Update atlas

## Feature Update
- [ ] Version information regarding tools and databases used in analysis
- [ ] Update cluster.json for cpu, time for all the rules
- [ ] Add memory in cluster.json
- [ ] Split BAM for non-threaded processes

## Bug Fixes
- [ ] 

## Timeline:
To be defined.

**Comment by ivadym** [comment]
Isn't it trivial to have this issue if we have a [v12](https://github.com/Clinical-Genomics/BALSAMIC/milestone/1) milestone?

Any thoughts @Clinical-Genomics/cancer-bioinfo?

**Comment by pbiology** [comment]
> Isn't it trivial to have this issue if we have a [v12](https://github.com/Clinical-Genomics/BALSAMIC/milestone/1) milestone?
> 
> Any thoughts @Clinical-Genomics/cancer-bioinfo?

I think we can also use the milestone to keep track of what will go into the v12 release. However, we shouldn't lose track of the items listed in bullet points here.

**Comment by pbiology** [comment]
Feature issues are now created for what I hope is all parts of this issue:
- #1130 
- #1131 
- #1132 
- #1133 
- #1134 
- #1135 
- #1136 
- #1137 
- #1138 
- #1139 

With these tracked in https://github.com/orgs/Clinical-Genomics/projects/46 I think we can close this issue

**Comment by ivadym** [comment]
Nice! Since everything here has been included in the board I will close this issue
