### ISSUE TITLE
Check reference links availability via Github Actions

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#1054]
**Is your feature request related to a problem? Please describe.**
Reference  URLs are currently not checked regularly and we only realise that the link is broken when we build the cache.

**Describe the solution you'd like**
A GitHub actions that verifies the sanity of the URLs when pushing to develop.

**Additional context**
Original issue: https://github.com/Clinical-Genomics/BALSAMIC/issues/675#issuecomment-1348483735

**Expected output for the feature**
Warn when a reference file is missing or not available.

**Current BALSAMIC version**
v11.0.2

**Comment by pbiology** [comment]
Part of #1112  ??

**Comment by ivadym** [comment]
It is, I even included it as a checkbox there. Should I just close all of these issues that depend on that one and add them as bullet points? What do you think?

**Comment by pbiology** [comment]
ah great. Let's just remove the feature flag here and then we capture all of those issues as a single new feature
