### ISSUE TITLE
Explicitly specify versions for all dependencies for containers

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/BALSAMIC#1061]
### Description

Currently containers often fails when building due to changes in versions of unspecified requirements (e.g. tools dependencies). For reproducibility purposes it would be nice to set all versions of all tools in the environment. Once environments are fully specified, it would be good to avoid build testing on every single push as it often takes a long time. 

## Suggested solution

- Replace requirement .yaml files with the output of `conda env export` of working containers
- Add `paths` on the docker build actions it only runs when files within the `containers` directories are modified

**BALSAMIC version**
`11.0.2`

**Comment by ivadym** [comment]
Addressed in: https://github.com/Clinical-Genomics/BALSAMIC/pull/1096.

@Clinical-Genomics/cancer-bioinfo: FYI I'll pull the updated containers from docker hub and add them to the 11.2.0 cache in stage
