### ISSUE TITLE
Update snakemake to be able to use `retries`

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/BALSAMIC#1067]
### Description

- Currently balsamic is using "snakemake==6.5.3". It would be nice to update to version >=7.7.0. to be able to use the `retries` directive. This can be handy when pulling containers or downloading references that fail due to temporary  errors or problem with connection. `retries` allows to specify the number of attempt to execute a rule before failing the workflow.

**BALSAMIC version**
`11.0.2`

**Current affected rule if snakemake workflow related**
If possible, describe which rules or workflows might be affected by this.

**References and other implementations**
If possible, an example of similar implementations.

**Comment by ivadym** [comment]
Done! 

https://github.com/Clinical-Genomics/BALSAMIC/pull/1099
