### ISSUE TITLE
Balsamic fails to pull containers from docker hub

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#1070]
**Describe the bug**

It is not possible to pull containers from docker hub using singularity:

> singularity pull develop-varcall_py27.sif docker://clinicalgenomics/balsamic:develop-varcall_py27
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
FATAL:   Unable to pull docker://clinicalgenomics/balsamic:develop-varcall_py27: conveyor failed to get: Error reading manifest develop-varcall_py27 in docker.io/clinicalgenomics/balsamic: manifest unknown: OCI index found, but accept header does not support OCI indexes

However, it is possible to bypass this issue by:
  1. Pulling the containers with docker to a local machine.
  2. Reuploading the downloaded containers to the clinical genomics docker hub.

**Expected behavior**
Being able to pull the containers uploaded via GitHub Actions with singularity.

**Comment by henrikstranneheim** [comment]
Do you need to add an authentication token file? Are you using the same version of singularity in the actions cmp to locally? There seem to be some issue with the OCI index that might depend on the difference in version

**Comment by ivadym** [comment]
Thanks @henrikstranneheim.

As of Buildx 0.10, images are built with provenance and the uploaded containers appears to be just a manifest entry and can't be pulled. We'll just keep provenance disabled for now. More info in https://github.com/Clinical-Genomics/BALSAMIC/pull/1071.

Closing :)
