### ISSUE TITLE
[ Failed Analysis ] TGS cases failing manta (new prep testing) 

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1078]
**Case or sample information**

Internal sample id or case id: 
Several cases all from ticket https://clinical-scilifelab.supportsystem.com/scp/tickets.php?number=469287 failed with errors in manta_tumor_only and manta_germline. 

This regards cases: fitsheep, civilalien, proudmutt, normalalpaca, steadykiwi.

Final two cases have not reached that step yet but might have the same error (divinemite and grownrobin)

Amount read-pairs:
- fitsheep: 34542193
- civilalien: 38309532
- proudmutt: 30931293
- normalalpaca: 39917244
- steadykiwi: 36201272

Sequence type (WES, TGA, WGS):

TGS

**Error message**
Copy either the error message from the e-mail or copy **only the relevant** line(s) in the error log showing the error message(s). Please do not paste the whole error text.

Example error log from proudmutt, manta_germline rule:
From file: "BALSAMIC.proudmutt.manta_germline.59.sh_4313612.err"
[ERROR] Failed to complete command task: 'getAlignmentStats_generateStats_000' launched from master workflow, error code: 1, command: '/opt/conda/share/manta-1.6.0-2/libexec/GetAlignmentStats --ref 

All cases have similar errors. 

**Link to the error message**

Replace manta_germline for manta_tumor_only error message, and proudmutt with other case-names for corresponding messages in these cases:
/home/proj/production/cancer/cases/proudmutt/logs/BALSAMIC.proudmutt.manta_germline.59.sh_4313612.err

**Reason for failure**

I have looked into the multiQC of 2 of the cases and saw an unusually high number of duplicates reported by picard, suggesting that it might have to do with the input read quality. 
Example from fitsheep:

![image](https://user-images.githubusercontent.com/14308912/215125111-4f94227d-b0fa-4651-887e-0ff0ed2fa073.png)

There is also the issue of these cases being involved in the testing of a new prep: https://www.illumina.com/products/by-type/ivd-products/dna-prep-enrichment-dx.html

Finally, there was something strange with the cases as they were recorded in statusDB which meant that we had to start the analysis manually with: cg workflow balsamic start --panel-bed gms_myeloid_5.3 caseid 

**If workflow, which rules**

manta_germline
manta_tumor_only

**Version (please complete the following information):**
`balsamic --version` v11.0.2

**Additional context**
Add any other context about the problem here. For e.g. amount sequencing reads or other parameters that are of interest.

**Comment by mathiasbio** [comment]
Update on this issue, it seems to be the same issue discussed here: https://github.com/Illumina/manta/issues/168 
For some reason the cases involved in the previously mentioned ticket all had a % of most frequent read-pair orientation below 90% which is the threshold for manta when it calculates AlignmentSats before doing the calling.

Apparently fixing this and pushing the cases through would require a modification of the code of Manta itself. https://github.com/Illumina/manta/blob/master/src/c%2B%2B/lib/manta/ReadGroupStatsUtil.cpp#L198 

But hopefully since these are internal cases there is actually no need for Manta to be run at all. It's probably mostly the QC values that are relevant. So I'm considering just creating these placeholder files to trick snakemake that the rules have been run.

If nobody has encountered this error before then I think we can just close this issue, and I will simply work around it for these cases, and take the info with me to the evaluation of these cases that I'm doing.

**Comment by fevac** [comment]
- Exactly same error observed with 6 cases from ticket 476648
- These cases are also from a development project
- These cases were also started manually with the same command written above
- These cases also have lower reads than expected for apptag

**Comment by fevac** [comment]
Again same error observed with additional cases for same project from ticket 963289 (also started manually). Observed extremely high fraction of duplicates
