### ISSUE TITLE
Add CADD scores to VCF for use in filtering in Scout

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1100]
**Is your feature request related to a problem? Please describe.**

During the latest GMS-BT meeting we were shown the workflow of one of our customers and how they use the filters in Scout for a BALSAMIC case. One thing that came up was that this customer needed to use some external tool to add CADD scores to her VCF in order to filter. 

Apparently CADD scores are not added to at least the SNVs and InDel VCFs that I have checked for BALSAMIC.  Whereas this is done for MIP. 

Given this issue: 
https://github.com/Clinical-Genomics/BALSAMIC/issues/834

Which mentions adding CADD scores for InDels, it makes me think that CADD was once added for SNVs but has been removed? So maybe this feature has been lost somewhere along the line, or maybe it was never added at all. 

**Describe the solution you'd like**

Add CADD scores to VCFs uploaded to Scout, where possible.  

**Current BALSAMIC version**
`balsamic 11.2.0`

**Comment by pbiology** [comment]
This is now added as a new feature issue (#1106) planned for BALSAMIC v12.
Closing this issue and tracking in the feature.
