### ISSUE TITLE
CN-LoH analysis

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1105]
## Need
- https://github.com/Clinical-Genomics/BALSAMIC/issues/1009

## Suggested approach
LOH analysis was performed using the PON generated from the normal samples and results were presented. Further investigation, aiming to improve the method, lead to the identification of feature addition and improvements given in the sections below.

## Considered alternatives
*Were there alternative approaches which has been rejected?*

## Can be closed when

- The containers are added
  - https://github.com/Clinical-Genomics/BALSAMIC/pull/1252
  - https://github.com/Clinical-Genomics/BALSAMIC/pull/1255
  - https://github.com/Clinical-Genomics/BALSAMIC/pull/1234
- The CN-LOH is added to the TGA workflow 
  - https://github.com/Clinical-Genomics/BALSAMIC/pull/1278
- The CN-LOH is added to the report and uploaded to Scout
- https://github.com/Clinical-Genomics/BALSAMIC/issues/1140

**Comment by khurrammaqbool** [comment]
The following PONs will Imrove LOH analysis:
- https://github.com/Clinical-Genomics/BALSAMIC/issues/1115
- https://github.com/Clinical-Genomics/BALSAMIC/issues/1135
- Add PureCN PON



The following  features will help with the interpretation of CN-LOH results:
- https://github.com/Clinical-Genomics/BALSAMIC/issues/1110 
- LOH-plots


The following features will further improve the analysis of CN-LOH:
- https://github.com/Clinical-Genomics/BALSAMIC/issues/1235
- https://github.com/Clinical-Genomics/BALSAMIC/issues/1109
- https://github.com/Clinical-Genomics/BALSAMIC/issues/1132
- https://github.com/Clinical-Genomics/BALSAMIC/pull/1176
- Germline somatic variant calling best practices and filtration.
- Add TNScope to TGA workflow
- Improve the panel design

**Comment by pbiology** [comment]
Good refinement of the issue!
Could we open new issues for all of the improvement features suggested?
