### ISSUE TITLE
Somatic impact scores

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1107]
## Need
`BALSAMIC ` adds `SOMATICSCORE` to the final SV `VCF` (*.clinical.filtered.pass.vcf.gz). This final `VCF` file is then uploaded to scout. `SCOMATICSCORE` is computed by manta for  tumor-normal cases.  

## Suggested approach
*A few sentences about the intended solution* 

## Considered alternatives
*Were there alternative approaches which has been rejected?*

## Can be closed when
- https://github.com/Clinical-Genomics/scout/issues/3883
- https://github.com/Clinical-Genomics/scout/issues/3884

## Blockers
*Anything preventing this from happening?*

**Comment by khurrammaqbool** [comment]
The following Issues are opened in `Scout` requesting to add and filter `SOMATICSCORE` for SVs from tumor-normal cases.
 - [add SOMATICSCORE for SVs](https://github.com/Clinical-Genomics/scout/issues/3883)
 - [Filter by SOMATICSCORE](https://github.com/Clinical-Genomics/scout/issues/3884)

**Comment by khurrammaqbool** [comment]
@mathiasbio would you like to add to the `SOMATCSCORE` described above and the associated action points?

**Comment by mathiasbio** [comment]
I will take a look!

**Comment by pbiology** [comment]
The development on the BALSAMIC side is completed and the final part is on the Scout side.

**Comment by khurrammaqbool** [comment]
Added to Scout in https://github.com/Clinical-Genomics/scout/commit/a21b6f60721a644aaff134b31962fdf8f896164e

**Comment by khurrammaqbool** [comment]
<img width="2016" alt="Screenshot 2023-08-09 at 14 47 17" src="https://github.com/Clinical-Genomics/BALSAMIC/assets/5569347/97504496-b38e-4291-8680-8ef7e7a8c0ab">
