### ISSUE TITLE
GENS

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1110]
## Need

Customers have requested GENS to be implemented for Balsamic. GENS is a tool basically for viewing copy-number alterations and regions with LoH. 

Originally developed in Lund, it has been forked to Stockholm:
https://github.com/Clinical-Genomics/gens/tree/master

Description from repo:
_"Gens is a web-based interactive tool to visualize genomic copy number profiles from WGS data (although it could theoretically be used for any type of data). It plots the normalized read depth and alternative allele frequency. It currently does not attempt to visualize breakpoint information, so use IGV for that! The way we generate the data it is suitable for visualizing CNVs of sizes down to a couple Kbp, for smaller things use IGV!"_

## Suggested approach

To activate we need 4 files stored in housekeeper for a case:
- SAMPLE_ID.baf.bed.gz (bgzipped)
- SAMPLE_ID.baf.bed.gz.tbi (tabix) 
- SAMPLE_ID.cov.bed.gz (bgzipped)
- SAMPLE_ID.cov.bed.gz.tbi (tabix)

A GENS upload cli has been implemented in CG here:
https://github.com/Clinical-Genomics/cg/blob/master/cg/cli/upload/gens.py
Which loops over all samples associated to the provided case, and extracts the paths to the above files based on some housekeeper tags.

To activate this for MIP it seems they have simply added this line:
`ctx.invoke(upload_to_gens, case_id=case.internal_id)`
Here: https://github.com/Clinical-Genomics/cg/blob/master/cg/meta/upload/mip/mip_dna.py

To create the 4 files there are a few steps:

**BAF file**
For MIP:
- They have a pre-created bed-file with positions from gnomad with variants with an AF above 0.05.
- They create a g-vcf
- Then they use the same pre-processing perl-script that Lund created to only keep positions in the g-vcf that overlap with the gnomad bed file. The script also outputs different zoom-ranges for the visualisation of the BAFs, and the final file has around 5.6M positions. With the most zoomed in window having around 4.1M positions.

For BALSAMIC the current plan is to mirror this output via a slightly different approach:
- Create a pre-filtered gnomad-vcf with only AF above 0.05 (then use this as a new cli-argument to config case)
- Run DNAscope with this gnomad-vcf as --given (forcing DNAscope to call positions on this)
- Run modified python version of the gens_preprocessing script which basically just outputs the variants in the different zoom windows, in the gens-format. 

**COV file**
Here is the trickier part. The GENS documentation recommends the creation of two PONs with `GATK CreateReadCountPanelOfNormals` one for each gender, with at least 100 samples for each. However, in RD they have already created this, so hopefully we can just re-use this, and hopefully we can use these files both for the TUMOR and the NORMAL samples, regardless of the tumor being sequenced roughly 3X higher (hopefully it's more the relative evenness of coverage that matters rather than total depth)
- To use the PONs that the RD guys have created we need to create 1 new cli-argument for config case
- There's also a genome_interval file which can be created with this:
```
gatk PreprocessIntervals                            \
     --reference GRCh38.fa                          \
     --bin-length 100                               \
     --interval-merging-rule OVERLAPPING_ONLY       \
     -O targets_preprocessed_100bp.interval_list
``` 
However if we run this on our reference we will add extra contigs to the bedfile, and other extra chromosome-IDs to the header, which do not match with the PON from MIP. We could still add this preprocessintervals as a rule in BALSAMIC, maybe in the generate cache, and add some extra processing of the file to make it compatible with the PONs. But at the moment I have added an extra cli to config case where this file is input from MIP.
- Beyond this we're doing the same processing here as in GENS documentation:
- gatk CollectReadCounts to create the cov file 
- gatk DenoiseReadCounts to normalise with the PON
- the modified gens_preprocessing python script to create the cov visualisation in different zoom levels.

## Infrastructure changes

- Add extra line in: https://github.com/Clinical-Genomics/cg/blob/master/cg/meta/upload/balsamic/balsamic.py for gens upload
- Add more files and housekeeper tags for the GENS-files to hermes?

## Considered alternatives
*Were there alternative approaches which has been rejected?*

## Can be closed when
-  [x] GENS has been implemented in balsamic https://github.com/Clinical-Genomics/BALSAMIC/pull/1279
- [x] Logic in CG has been implemented to upload files to GENS  https://github.com/Clinical-Genomics/cg/issues/2447
- [x] Links in Scout correctly links out to GENS files https://github.com/Clinical-Genomics/BALSAMIC/issues/1298
- [x] Names in sample columns of final VCFs uploaded to Scout uses LIMS-IDs https://github.com/Clinical-Genomics/BALSAMIC/pull/1310

## Blockers
*Anything preventing this from happening?*

**Comment by ivadym** [comment]
Closing as the remaining bullet points have been addressed outside Balsamic: https://github.com/Clinical-Genomics/cg/issues/2447
