### ISSUE TITLE
Easy handling of validation cases

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1111]
## Need
Validation cases must always be available to be used in stage. We need to avoid decompressing and storing FASTQs every time we want to run a validation case for verification/test purposes.

## Suggested approach
1. Fix the storage of FASTQs in production, which are currently saved with an absolute production path that is being extended to the stage environment.
2. Add the validation samples to the stage housekeeper bundle, making them permanently available for testing purposes.

## Can be closed when
- [x] https://github.com/Clinical-Genomics/servers/issues/1002
- [x] Validations cases are decompressed and available in housekeeper bundles in stage (cases: https://docs.google.com/spreadsheets/d/1QGJpdaeKLZGWCYseEXja9vOcCeVMNwQo/edit#gid=797072593)
- [x] Script to start validation cases
  - The script can be found in `/home/proj/stage/cancer/validation/run_validation_cases.sh`

**Comment by ivadym** [comment]
Closing this as completed @Clinical-Genomics/cancer-bioinfo. All validation cases should be available on the stage, and no further actions should be taken to run these analyses.

**Comment by pbiology** [comment]
Really nice! Speedy validations ahead!
