### ISSUE TITLE
COSMIC profiles

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1113]
## Need
*In a short and concise manner, describe the need the feature satisfies*

## Suggested approach
*A few sentences about the intended solution* 

## Considered alternatives
*Where there alternative approaches which has been rejected?*

## Can be closed when
*Link the issues needed to be closed for this to be implemented*

## Blockers
*Anything preventing this from happening?*

**Comment by mathiasbio** [comment]
Closing as a user-story has been created: https://github.com/Clinical-Genomics/BALSAMIC/issues/1416
