### ISSUE TITLE
improve filtering of structural variants

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1119]
## Need

Two recent issues have been lifted with regards to filtering of SVs:
1. **Filter TIDDIT:** In version 10.0.0 of balsamic TIDDIT and Delly were introduced into the pipeline as additional variant callers for SVs. This resulted in a significant increase in the number of SVs, and especially from TIDDIT. See issue: https://github.com/Clinical-Genomics/BALSAMIC/issues/1118
2. **Rescue long variants from VEP:** In VEP a --max_sv_size filter exist with a default setting too low for some of our called SV variants. The default behavior in VEP version < 109 is to output warnings and not output the variants at all. This can result in clinically relevant variants to be filtered away. See issue: https://github.com/Clinical-Genomics/BALSAMIC/issues/1123

## Suggested approach

**Filter TIDDIT:** In the case of TIDDIT there are additional filters that should be fairly simple to implement which could significantly reduce the number of variants. Most notably:
1. Filtering the somatic SVs based on their co-occurrence in the normal sample, as intended, rather than merging the calls from both the normal and tumor. 
2. Choosing 1 of the 2 instances of the BND - variants that are called by TIDDIT (2 are called for each of these types of SVs, one for the start location and one for the end).  

The most important of these to implement is the first one. But if there is time it would be nice if the second approach could be implemented as well, and any other filtering that seems useful, especially if the number of variants after implementing these approaches are still high.

**Rescue long variants from VEP:**  Two approaches exists either:
1.  Increase the --max_sv_size to the maximum (the size of Chr 1 of the human genome)
2. Update VEP which still keeps variants longer than max_sv_size but leaves them unannotated
Or possibly both! 

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Can be closed when

- [x] https://github.com/Clinical-Genomics/BALSAMIC/pull/1120
- [x] https://github.com/Clinical-Genomics/BALSAMIC/pull/1124

## Blockers
*Anything preventing this from happening?*

**Comment by mathiasbio** [comment]
I was thinking to implement the second point mentioned above "Choosing 1 of the 2 instances of the BND - variants that are called by TIDDIT (2 are called for each of these types of SVs, one for the start location and one for the end)." But I don't fully understand it, and it seems like it might be too complicated to squeeze into the time-frame we have for the release 12.

I made a separate issue for it that I believe may be better addressed in a later release of Balsamic. https://github.com/Clinical-Genomics/BALSAMIC/issues/1121

So for this feature issue I think we can be satisfied with just removing the normal variants.

**Comment by pbiology** [comment]
Makes sense. We can discuss in the next cancer group meeting about the timeline for #1121

**Comment by mathiasbio** [comment]
Further information about implementation of tumor normal filtering.

This filtering aims to remove variants in the merged tumor-normal vcf from TIDDIT which have a presence in the normal:
- It begins by marking all variants which contains NORMAL_PASS_INFO in the INFO field with filter in_normal 
- It then rescues variants which have an allele-frequency >= 0.4, and a frequency in the normal <= 0.1, this to rescue potential tumor contamination in the normal. This implementation is not perfect, as it allows in a sense for different degrees of tumor contamination depending on the frequency of the variant in the tumor. For 0.4 it allows for 25%, and for 1 it allows only 10%. Ideally this would be implemented with a consistent tumor contamination fraction, such as this example in bcftools: `filter -s in_normal -e '((FORMAT/DV[1] + FORMAT/RV[1]) / (FORMAT/COV[1:0] + FORMAT/COV[1:2])) >= ((FORMAT/DV[0] + FORMAT/RV[0]) / (FORMAT/COV[0:0] + FORMAT/COV[0:2]) * 0.1)' -m +` where the in_normal filter would be set if it has a frequency >= to the tumor frequency * 0.1, to allow for a 10% contamination consistently. However it seems that bcftools does not work properly on an expression which parses information on both sides of the comparison operator. So this was the simplest way I found of implementing this rescue for the moment, and I believe it should cover most cases! 
- It then sets all remaining variants to PASS

**Comment by mathiasbio** [comment]
Update on the above description: 

I removed the last step where the variants without PASS are removed as this filtering is already done downstream. This way the variants flagged with the filter "in_normal" will still be added to the loqusDB database and it avoids the normal information being lost after merging with outputs from other variant-callers.

As further information...

The way SVDB works it also means that only the filters applied to a variant from the highest priority variant caller will be present after merging (other less high priority filters will be in the info-field). This means that if a variant from TIDDIT with "in_normal" set merged with a Manta PASS variant, will still have the filter PASS, and the "in_normal" filter will be present in the INFO field.

This avoids the potential risk of filtering out a variant called as PASS from Manta, merged with a slightly different variant from TIDDIT with "in_normal" filter set.

**Comment by pbiology** [comment]
Looks like this is completed. Can you verify and close if so @mathiasbio

**Comment by mathiasbio** [comment]
Definitely, closing!
