### ISSUE TITLE
Running processes without using Cosmic authorization

### ISSUE THREAD

**Issue by user-tq** [Clinical-Genomics/BALSAMIC#1128]
I learned a lot from this project, which contains comprehensive source and knowledge of somatic mutation analysis. 
To be honest, I really want to try using this pipeline, as it is much more comprehensive than my own analysis process. 
However, according to the guidelines, the primary condition for running this process seems to be having authorization from COSMIC. Due to commercial licensing reasons (I graduated last year😂 ), I cannot use this database. Is there a way to skip it?

**Comment by pbiology** [comment]
Hi @user-tq. 

Thanks for the interest in BALSAMIC.
If you are interested in running the pipeline but are neither a commercial enterprise, nor are doing it for academic reasons, you do represent a bit of an edge case. 

COSMIC does allow for free registration for non commercial parties, but you do of course need to specify an affiliation. I would recommend adding your previous academic institution for this. 

It is not possible right now to circumvent the COSMIC part in BALSAMIC, and adding a solution for this would require substantial amount of work. As this is such an unusual user case, we won't be able to implement this any time soon I'm afraid.

I will close this issue for now.
Best of luck!
