### ISSUE TITLE
Filter variants agains LoqusDB

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1131]
## Need
To reduce the number of variants uploaded to scout, we should filter out the one that comes from local technical artefacts.

## Suggested approach
Use LocusDB to remove these

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Can be closed when
- [ ] Decide on best strategy
- [ ] Filtering implemented in BALSAMIC
- [ ] Update documentation

## Blockers
- SVs: https://github.com/Clinical-Genomics/BALSAMIC/issues/1316
- SNVs:

**Comment by mathiasbio** [comment]
We have added https://github.com/Clinical-Genomics/BALSAMIC/issues/1377 in release 16 for SNVs, though it can be improved by adding more samples. As we already have this issue for SVs https://github.com/Clinical-Genomics/BALSAMIC/issues/1316 maybe we can close this one.
