### ISSUE TITLE
Add TNScope PON

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1135]
## Need
To refine the analysis we need a panel of normal to filter results against.

## Suggested approach
*A few sentences about the intended solution* 

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Can be closed when
- [ ] Decide which samples should be included in the PON
- [ ] Generate the PON
- [ ] Update BALSAMIC to take the PON as input
- [ ] Update documentation

## Blockers
*Anything preventing this from happening?*

**Comment by mathiasbio** [comment]
replaced by https://github.com/Clinical-Genomics/BALSAMIC/issues/1405
