### ISSUE TITLE
Delivery report for QC only analysis

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1136]
## Need
When we only do QC, we should still have a delivery report with performance metrics

## Suggested approach
*A few sentences about the intended solution* 

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Can be closed when
*Link the issues needed to be closed for this to be implemented*

## Blockers
*Anything preventing this from happening?*

**Comment by ivadym** [comment]
I've added the CG issue to the board (https://github.com/Clinical-Genomics/cg/issues/1563). I'll close this one as there's nothing else to do from the Balsamic side.
