### ISSUE TITLE
Update files stored and delivered (HERMES and CG)

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1137]
## Need
We need to update which files are stored and delivered to ensure we are compliant with SWEDAC and the clinical needs.

## Suggested approach
*A few sentences about the intended solution* 

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Can be closed when
- [x] Decide which files to deliver (https://docs.google.com/spreadsheets/d/1QGJpdaeKLZGWCYseEXja9vOcCeVMNwQo/edit#gid=2047401755)
- [x] Decide which files to keep longer term
  - [x] https://github.com/Clinical-Genomics/cg/issues/1739
  - [x] https://github.com/Clinical-Genomics/BALSAMIC/pull/1144
  - [x] https://github.com/Clinical-Genomics/hermes/pull/71
- [x] Decide on a transparent place where this is kept:
  - Atlas:
     - Delivered files: https://github.com/Clinical-Genomics/atlas/pull/722
     - Stored files: https://github.com/Clinical-Genomics/atlas/pull/1705
   - Order portal:
     - Delivered files: https://github.com/Clinical-Genomics/cgweb/pull/424

**Comment by ivadym** [comment]
Closing as all the bullet points have been addressed
