### ISSUE TITLE
Update resource requests of all rules

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1139]
## Need
We should aim for not over or under requesting resources when submitting SLURM jobs.
In the cluster.json file we should update cpu, time and memory of all rules.

## Suggested approach
*A few sentences about the intended solution* 

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Can be closed when
- [ ] All rules in the pipeline are accounted for in the cluster.json 

## Blockers
*Anything preventing this from happening?*

**Comment by ivadym** [comment]
Added to user story: https://github.com/Clinical-Genomics/BALSAMIC/issues/1312
