### ISSUE TITLE
Increase time-limit for processes that often time out

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1142]
## Need

sambamba_exon_depth and picard_markduplicates sometimes time-out at around 270 minutes. It would be nice for production to avoid restarting these manually, so we should increase the allowed time for running these processes.

## Suggested approach

Increase timeout of processes to 360 minutes for these processes. 

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Requests/bugs/suggestions solved
*Link any feature requests, bug reports or other issues solved by this feature*

## Can be closed when
- [ ]  https://github.com/Clinical-Genomics/BALSAMIC/pull/1143

## Blockers
*Anything preventing this from happening?*

**Comment by pbiology** [comment]
Completed and closed? @mathiasbio

**Comment by mathiasbio** [comment]
Si! Closing.
