### ISSUE TITLE
[ Failed Analysis ] CNVpytor float values not accepted by bcftools

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1152]
**Case or sample information**
Internal sample id or case id: modelstag
Amount read-pairs: 2688801506
Sequence type (WGS): Tumor only

**Error message**
Rule that failed: bcftools_quality_filter_svdb

Error message: 
```
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">;"'
[E::vcf_parse_format] Invalid character '.' in 'CN' FORMAT field at 8:35400001
[E::vcf_parse_format] Invalid character '.' in 'CN' FORMAT field at 8:46900001
Error: VCF parse error
```

**Link to the error message**

/home/proj/production/cancer/cases/modelstag/logs/BALSAMIC.modelstag.bcftools_quality_filter_svdb.6.sh_4695700.err

**Reason for failure**

CNVpytor outputs float values for CN sometimes:
8	35400001	CNVpytor_dup8	.	<DUP>	.	PASS	INFOfieldremoved	GT:CN	./1:**2.73**

Don't know if this is intentional or a bug from CNVpytor!

**If workflow, which rules**

bcftools_quality_filter_svdb in WGS tumor only

**Version (please complete the following information):**
`balsamic --version` 11.0.2

**Additional context**
Add any other context about the problem here. For e.g. amount sequencing reads or other parameters that are of interest.

**Comment by pbiology** [comment]
@mathiasbio can you assign gain/urgency/effort labels to this?

**Comment by pbiology** [comment]
Or was this solved by #1183 ?

**Comment by khurrammaqbool** [comment]
It was fixed in CNVpytor https://github.com/abyzovlab/CNVpytor/issues/178 and we have added the latest version of CNVpytor in develop.

**Comment by mathiasbio** [comment]
I didn't know about the CNVpytor update fixing it, that's great. I guess my fix is unnecessary then at this point, did you remove the sed command I added @khurrammaqbool ? I guess it doesn't matter if it's there either, but it would be cleaner if we removed it I suppose when it's not necessary anymore : )

**Comment by mathiasbio** [comment]
Removed the sed command in https://github.com/Clinical-Genomics/BALSAMIC/pull/1310 and as the issue has already been solved in the CNVpytor update I'll close this issue
