### ISSUE TITLE
Visualising/trending GC dropout in Balsamic for TGA data

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/BALSAMIC#1156]
**Is your feature request related to a problem? Please describe.**
Sometimes we have issue with GC dropout but we do not trend this so we cannot improve our analysis (wetlab). We get GC dropout for target enrichment (TGA) data but only from picardtools.

**Describe the solution you'd like**
It would be nice to be able to get an overview of how the GC dropout varies over the targeted regions, this could also differ from different capture panels

**Describe alternatives you've considered**
If possible, a clear and concise description of any alternative solutions or features you've considered.

**Additional context**
If possible, add any other context or screenshots about the feature request here.

**Expected output for the feature**
If possible, an example of expected output

**Current BALSAMIC version**
`balsamic --version`

**Comment by annaengstrom** [comment]
@vwirta please add/adjust if needed

**Comment by mathiasbio** [comment]
Is this something that will come with https://github.com/Clinical-Genomics/Janus ? As we are adding GC dropout values to the multiqc files which are stored in housekeeper, I think it will be up to some other tool in CG to create the actual trending of the values, as balsamic itself does not have any information about historical samples only the current one running. I will close this but feel free to open if I missed something! 🙏
