### ISSUE TITLE
Singularity bind path

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#1160]
## Need
The current version of BALSAMIC uses same path as internal and external bind paths for singularity. 

## Suggested approach
Having a separate internal and external bind path for singularity containers.

## Requests/suggestions/bugs solved by the feature
The proposed solution will enable adding containers that require different internal and external bind paths.

## Can be closed when
*Link the issues needed to be closed for this to be implemented*

## Blockers
https://github.com/snakemake/snakemake/issues/262

**Comment by ivadym** [comment]
Closing this issue now as it has been resolved in #1211.

However, we would need to consider an alternative solution in case we encounter a situation where container-specific binding paths are required.
