### ISSUE TITLE
Update Python (3.7 end of life)

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#1169]
## Need

Balsamic is currently built using Python version 3.7, which is reaching its end of life ([27 Jun 2023](https://endoflife.date/python)). 

## Considered alternatives

The alternative involves maintaining the current Python 3.7 version. However, this approach is risky in terms of compatibility with future developments, lack of security updates, and limited access to the latest Python features.

## Can be closed when

- [ ] Perform compatibility evaluation and decide on the new Python version.
- [ ] Analyse the current Balsamic's codebase to identify any potential issues that might arise during the migration process and update dependencies (also Balsamic container).
- [ ] Update documentation.

**Comment by pbiology** [comment]
I agree that maintaining a deprecated python version seems quite tricky.  
To what version should we upgrade?

**Comment by ivadym** [comment]
I would say the latest which doesn't break the workflow and rendering of the documentation

@khurrammaqbool mentioned some time ago that he run successfully Balsamic with python 3.10. I could do some more testing including the docs generation.


[Python 3.11](https://docs.python.org/3/whatsnew/3.11.html#:~:text=Python%203.11%20is%20between%2010,See%20Faster%20CPython%20for%20details.) is also interesting since it includes `Support for parsing TOML in the Standard Library`

**Comment by pbiology** [comment]
Would there be any issues on the hasta side of things to use a higher version?

**Comment by ivadym** [comment]
Done. `S_balsamic` has been updated accordingly FYI @Clinical-Genomics/cancer-bioinfo.
