### ISSUE TITLE
SV analysis on UMI files

### ISSUE THREAD

**Issue by EmmTha** [Clinical-Genomics/BALSAMIC#1185]
## Need
SV analysis on umi-collapsed data

## Suggested approach
Can you run the current tools (cnvkit, dellycnv/SV, manta, tiddit) on umi-collapsed files instead of the non-umi files in a balsamic umi order?

## Considered alternatives
I do not know

## Requests/suggestions/bugs solved by the feature
We need to see SVs with low frequency (low VAF) in our data. I assume that just as for SNVs/indels, there are a large number of artefacts in the non-use files and these will hopefully disappear in the uni-collapsing so that only true SVs are left.....

## Can be closed when
I cannot answer this

## Blockers
I cannot answer this

Thanks, Emma Tham (Clinical Genetics)

**Comment by pbiology** [comment]
Than you for the request! We will take it up for discussion in the next developers meeting and will give feedback here.

**Comment by pbiology** [comment]
As the current SV callers are not UMI aware, we would not gain anything from running the current analysis on UMI data.
We are however currently focusing on adding more filtering to the pipeline which would reduce the noise when interpreting.

With this we will now close this issue.
