### ISSUE TITLE
Annotate clinically relevant SVs with somatic variant observation frequencies from LoqusDB

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#1193]
## Need
The is the second part continuing from https://github.com/Clinical-Genomics/BALSAMIC/issues/1184 to add the annotation for the somatic SVs from loqusDB somatic SV observation frequencies. 

## Suggested approach
*A few sentences about the intended solution* 

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Requests/suggestions/bugs solved by the feature
*Link any feature requests/bug reports or other issues which this would solve*

## Can be closed when
*Link the issues needed to be closed for this to be implemented*

## Blockers
*Anything preventing this from happening?*

**Comment by ivadym** [comment]
Closing as completed!
