### ISSUE TITLE
Use  f-strings from now on for inputs, outputs, params and messages in rules

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#1208]
**Description**
@ivadym suggested to use f-strings in a comment, but changing only one rule makes the whole structure inconsistent, so it will be nice to add it to the BALSAMIC etiquette and update the rules accordingly and make the overall structure consistent.

_Describe the problem/suggestion_

**Suggested solution**

_Write here if there is a suggested way to solve the issue_

**This can be closed when:**

_Describe what needs to be done for this issue to be closed_

**Blocked by**

_If there are any blocking issues/prs/things in this or other repos. Please link to them._

**Before submitting**
- [ ] Assign Effort/Gain/Urgency labels

**Comment by ivadym** [comment]
Included in: https://github.com/Clinical-Genomics/BALSAMIC/issues/1343
