### ISSUE TITLE
Add SVDB parameters to workflow_params

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#1209]
**Description**
The parameters for `SVDB` from all the relevant commands  should be added to workflow_params.

_Describe the problem/suggestion_

**Suggested solution**

_Write here if there is a suggested way to solve the issue_

**This can be closed when:**

_Describe what needs to be done for this issue to be closed_

**Blocked by**

_If there are any blocking issues/prs/things in this or other repos. Please link to them._

**Before submitting**
- [ ] Assign Effort/Gain/Urgency labels

**Comment by ivadym** [comment]
Closing as there are a more general issue addressing this problem: https://github.com/Clinical-Genomics/BALSAMIC/issues/1301
