### ISSUE TITLE
Add cnvpytor plots to pdf report

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#1223]
**Description**
`BALSAMIC` generates CNV plots, `CNV.somatic.*.cnvpytor.circular.png` and `CNV.somatic.*.cnvpytor.scatter.png` using CNVpytor. A PDF report, similar to the one generated for TN cases from ascatNGS generated plots, will be a nice addition to WGS tumor-only analysis reports.  

_Describe the problem/suggestion_

**Suggested solution**
Create PDF from the plots generated by CNVpytor and upload to Scout for WGS tumor-only cases.

_Write here if there is a suggested way to solve the issue_

**This can be closed when:**

_Describe what needs to be done for this issue to be closed_

**Blocked by**

_If there are any blocking issues/prs/things in this or other repos. Please link to them._

**Before submitting**
- [x] Assign Effort/Gain/Urgency labels

**Comment by ivadym** [comment]
This has been in production since Balsamic v11: https://github.com/Clinical-Genomics/BALSAMIC/pull/1023
