### ISSUE TITLE
Update tool information

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1236]
## Need
We need to have an updated information about which tools are part of BALSAMIC, and which version there is.

## Suggested approach
We have this page, https://balsamic.readthedocs.io/en/latest/bioinfo_softwares.html, but it seems like the versions are out of date. Would be good to have this updated.

## Considered alternatives
We have also talked about breaking out the containers into one per tool, perhaps that is needed before we make this change, so it won't be as manual job?

## Requests/suggestions/bugs solved by the feature
Would be easy to find which versions of tools are used.

## Can be closed when
- [ ] [Readthedocs](https://balsamic.readthedocs.io/en/latest/bioinfo_softwares.html) shows correct information

## Blockers
- #1165 ??

**Comment by pbiology** [comment]
Looking in a case.json file, the versions are not the same as in the documentation

**Comment by khurrammaqbool** [comment]
I checked now and see that the tool versions are upto-date here https://balsamic.readthedocs.io/en/v12.0.2/balsamic_methods.html. Three tools are missed to be updated (vcf2cytosure, svdb, tiddit) here: https://balsamic.readthedocs.io/en/v12.0.2/bioinfo_softwares.html. Please specify if you see the information to be incorrect for the tools other than the three mentioned above.

**Comment by pbiology** [comment]
samtools we also use 1.9, tabix we also use 0.2.6

Missing tools seem to be: genmod, somalier, csvkit, cnvpytor

**Comment by khurrammaqbool** [comment]
samtools and tabix will be unified when we start using htslib container. We do not mention the version of the tool if it is used a dependency of the other main bioinformatic tool. 
cnvpytor is mentioned in balsamic_methods (I will add to the tools as well), csvkit is a dependency so, it is not required to be added as a separate tool. 
genmod and somalier will be added.
