### ISSUE TITLE
[User Story] Delivery report includes delivered files

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1247]
### Need

As a clinician I want to have a comprehensive view of the files delivered for each case, so that I can efficiently communicate and explain case details to new staff members, and easily identify cases that contain specific files.

### Suggested approach

Add a list of files delivered and uploaded to Scout, including which files are delivered, where they can be found, what is in them, and how was the information generated.

### Risk assessment

- [ ] Needed
- [X] Not needed

### System requirements assessed

- [X] Yes, I have reviewed the system requirements

### Can be closed when

- [ ] Delivery report includes which files have been delivered to Caesar and uploaded to Scout

**Comment by ivadym** [comment]
I suppose we can close this: https://github.com/Clinical-Genomics/cg/pull/3029

<img width="555" alt="Screenshot 2024-03-19 at 16 37 32" src="https://github.com/Clinical-Genomics/BALSAMIC/assets/26309194/0cafd764-3a4d-4d2c-b75f-a5340d076be0">

I'll invest some time in this PR: https://github.com/Clinical-Genomics/cg/issues/2955, where I'll also add the link to the order portal where we have the description of the files. I don't think we can use automation to include a description without it becoming messy and potentially ending up hardcoding it

FYI: @Clinical-Genomics/rna
