### ISSUE TITLE
Update Sentieon

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1250]
## Need
There has been a few updates of Sentieon that we have not been keeping up with:
- Last release: [202308](https://support.sentieon.com/manual/appendix/releasenotes/#release-202308)
- Our version in production: [202010.02](https://support.sentieon.com/manual/appendix/releasenotes/#release-202010-02)

The latest versions include updates that are relevant both in terms of TAT of analysis and accuracy of the variant-calling, as well as improvements to the UMI workflow, and it would be very nice if we can update Sentieon to include these changes.

Some relevant changes since version 202010.02:
- Modified TNscope® AF output format.
- Solved issue in duplex umi consensus that results depend on internal data order.
- **Improved speed of bwa mem.**
- **Solved issue in TNscope such that evidence from overlapping read pairs were not adequately accounted for.**
- Solved issue in duplex umi consensus that could output zero-length reads.
- **Added support in Dedup algorithm to perform UMI barcode error correction.**
- **Added support in LocusCollector and Dedup algorithms to perform consensus based deduplication as well as UMI barcode aware deduplication.**
- **Improved machine learning model for TNscope.**
- Improved consensus of INDELs in Dedup algorithm.
- Improved DNAscope pipeline speed and accuracy with a BWA model.

## Suggested approach
- Update Sentieon to latest version available!

## Can be closed when
  - [ ] Sentieon has been updated

**Comment by pbiology** [comment]
Can we re-work this issue using the new user-story template. That way we can have all release 14 issues in the new format.

**Comment by mathiasbio** [comment]
Closing issue, replaced with user story: https://github.com/Clinical-Genomics/BALSAMIC/issues/1384
