### ISSUE TITLE
Keep in line with GATK Best Practices

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1257]
## Need

We should revisit the GATK and Sentieon Best Practices (probably the same), and investigate to what degree our workflows can cohere to these standards, and implement the changes if possible.

One relevant update identified in Best Practices regards the usage of the Realignment step.

It seems that this step has been removed from the GATK best practices (https://github.com/broadinstitute/gatk-docs/blob/master/blog-2012-to-2019/2016-06-21-Changing_workflows_around_calling_SNPs_and_indels.md?id=7847), primarily as the sequencing techniques have improved to a degree where realignment doesn't add much value.

There has also been some updated example pipelines on Sentieon github since we last updated Sentieon, for example here where we can look for inspiration.
- https://github.com/Sentieon/sentieon-scripts/blob/master/example_pipelines/somatic/TNscope/default.sh

## Suggested approach

Look through and compare Best Practices to our current workflows and identify updates that could be done to our workflows:
- **Remove realignment step.**
- [ ] _@khurrammaqbool mentioned some variants that could be particularly affected by removal of the Realignment step, and if that takes too much effort to understand how to address this issue, perhaps removal of the realignment can be moved to a future Feature issue._
- **Other updates**

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Requests/suggestions/bugs solved by the feature
*Link any feature requests/bug reports or other issues which this would solve*

## Can be closed when
*Link the issues needed to be closed for this to be implemented*

## Blockers
*Anything preventing this from happening?*

**Comment by khurrammaqbool** [comment]
Some discussion on `realignment`:
1. [GATK4 realignment](https://sites.google.com/a/broadinstitute.org/legacy-gatk-forum-discussions/2018-04-11-2017-12-02/11324-GATK4-realignment)
2. [https://sites.google.com/a/broadinstitute.org/legacy-gatk-forum-discussions/2016-04-07-2015-11-26/7131-Is-Indel-realignment-removed-from-GATK4](https://sites.google.com/a/broadinstitute.org/legacy-gatk-forum-discussions/2016-04-07-2015-11-26/7131-Is-Indel-realignment-removed-from-GATK4)
3. [Port IndelRealignment pipeline](https://github.com/broadinstitute/gatk/issues/3104)
4. [Changing workflows around calling SNPs and indels](https://github.com/broadinstitute/gatk-docs/blob/master/blog-2012-to-2019/2016-06-21-Changing_workflows_around_calling_SNPs_and_indels.md?id=7847#illustrationB)

**Comment by mathiasbio** [comment]
Replacing this with assessment issue, after that has been assessed we can open up user-stories for the specific features that may or may not need to be changed 
https://github.com/Clinical-Genomics/BALSAMIC/issues/1257
