### ISSUE TITLE
GENS for TGA?

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1267]
**Is your feature request related to a problem? Please describe.**

This is not a request but a customer asked if it was possible to view their TGA cases in balsamic in GENS. I'm just making this issue to bring it up for refinement. Should we make this possible? Is it even useful?

**Describe the solution you'd like**
If possible, a clear and concise description of what you want to happen.

**Describe alternatives you've considered**
If possible, a clear and concise description of any alternative solutions or features you've considered.

**Additional context**
If possible, add any other context or screenshots about the feature request here.

**Expected output for the feature**
If possible, an example of expected output

**Current BALSAMIC version**
`balsamic --version`

**Comment by ivadym** [comment]
User story: https://github.com/Clinical-Genomics/BALSAMIC/issues/1385
