### ISSUE TITLE
[Bug] Variants not in expected sort order

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1277]
**Describe the bug**
Teresita sent in a ticket where she flagged that she doesn't recognise the sort order of the variants in the file SNV.somatic.XXXXXXXXX.vardict.vcf.gz (case name removed). More info in the [ticket](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=61474)

Karl Svärd thought perhaps that this is due to it being a WES case?

**To Reproduce**

**Expected behavior**

**If workflow, which rules**

**Screenshots**

**Version (please complete the following information):**
12

**Additional context**
We need to make sure to answer her back in the ticket.

**Comment by khurrammaqbool** [comment]
I replied in the ticket. Pasting my response below:
It seems that an intermediate process disrupts the sort order, we can add a final sort command to make sure that the VCF is sorted.

**Comment by pbiology** [comment]
Is this something that has changed recently? If it is then I think it makes sense to try to fix this so it doesn't cause confusion. If not, then I got the impression from the ticket that this was not an issue.

**Comment by pbiology** [comment]
Is this something that has changed recently? If it is then I think it makes sense to try to fix this so it doesn't cause confusion. If not, then I got the impression from the ticket that this was not an issue.

**Comment by pbiology** [comment]
Added this to the 13 release just so we don't forget about it. Could be 14 if it's too much work

**Comment by pbiology** [comment]
Could we re-work this issue using the user-story template? Then we can have all release 14 items be in the new format

**Comment by ivadym** [comment]
Never fixed, and now we are replacing vardict with tnscope. Closing the issue and removing from milestone and board
