### ISSUE TITLE
[User Story] Add samtools command for IGH::DUX4 detection

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/BALSAMIC#1281]
### Need
As a clinician I need to be able to detect the IGH::DUX4 SV reliably in all affected samples so I can reliably call it.

This event is generally missed

### Suggested approach
Add the samtools command from https://www.frontiersin.org/journals/oncology/articles/10.3389/fonc.2023.1217712/full

From cited paper:
>  The location of DUX4, within the highly repetitive D4Z4 region (45), results in a high number of copies for DUX4 and DUX4-like genes. This poses challenges for the detection of DUX4-r with short-read WGS. To overcome the limitations of our initial bioinformatics pipeline, we applied a SAMtools command (46, 47) to specifically identify reads supporting an IGH::DUX4 rearrangement. The command identifies discordant reads in the IGH region (14:106032614–107288051, in GRCh37/hg19), and subsequently, these reads were filtered to only include reads that either i) have a mate mapped to one of the regions where DUX4 may map (4:190988100–191007000, 10:135477000–135500000, or GL000228.1:7000–115000 in GRCh37/hg19) or ii) have a secondary alignment in either of the above-mentioned regions. See Supplementary Material for the SAMtools command.

```
samtools view -F 1024 -c -e '(rnext == "4" && pnext > 190988100 && pnext < 191007000) || (rnext == "10" && pnext > 135477000 && pnext < 135500000) || (rnext == "GL000228.1" && pnext > 70000 && pnext < 115000) || ([SA] =~ "10,1354[789][0-9]{4}") || ([SA] =~ "4,19(09[8-9][0-9]|100[0-7])[0-9]{3}" || [SA] =~ "GL000228.1,([7-9][0-9]{4}|1[0-1][0-5][0-9]{3})")' tumor.cram 14:106032614-107288051
```

### Considered alternatives
None

### Deviation
No

### System requirements assessed
System requirements not implemented

### Requirements affected by this story
System requirements not implemented

### Risk assessment needed
- [x] Needed
- [ ] Not needed

### SOUPs
SOUPS not implemented

### Can be closed when
- [ ] Above mentioned samtools command in used for all applicable sample types

### Anything else?
1. There is a case that can be used as true positive
2. Think this is only for WGS, but not entirely sure about WES

**Comment by fevac** [comment]
I did a quick search and, as expected, short-read SV callers currently fail to detect this rearrangement. There is possibly an exception I could find, which is the GRIDSS/GRIDSS2 caller, that uses information from single breakends. I saw [this paper](https://www.sciencedirect.com/science/article/pii/S2473952923001106) where they use GRIDSS followed by BLAT to detect DUX4 rearrangements. 

The other papers I saw they use a similar approach as the samtools  command suggested above (so using read linking information).

This was not the most comprehensive search, so I could have missed things

**Comment by mathiasbio** [comment]
Nice! Great job : )) Do you have any suggestion for how to deliver the result to customers? Just try to mimic the VCF format and add it to the SV vcf?

**Comment by pbiology** [comment]
Re-worked the issue to use the User Story template

**Comment by fevac** [comment]
For refinement: 

Preferred solution
- Add rule that takes the merged alignment (either bam or cram)
- The rule runs the samtools command and generates an SV vcf file (only for tumor or also for normal if present?)
- VCF is included as input in the SVDB merge rule and included in the final SVDB file (need to make sure this entry is NOT filtered in the clinical vcf)

**Comment by khurrammaqbool** [comment]
As I mentioned during the meeting, I am summarising here as well:
- Related to the two options, it will be nice to clearly define the scope of the IGH-DUX4 fusion event in terms for the three mapping positions.
- It may require looking closer into GL000228.1:7000–115000 region to see if any secondary alignment should be considered as part of IGH-DUX4 fusion event (to be included or excluded).
- it will be nice to take a look at how those positions look like. Could you please add the details of those coordinates from the three mapping positions along with the information of the positions of mates.

**Comment by fevac** [comment]
@khurrammaqbool answering your comment:
- The scope of the IGH-DUX4 fusion is clearly defined by the command positions (see the issue description). Which information are you missing specifically?
- Discordant reads in the IGH region having an alignment or secondary alignment to any of the mentioned regions are included. This is a method described in a published paper that we just want to incorporate. It has already being assessed in the cited paper and clinicians find it useful. What is it really what you want to check and what do you expect to see?
- I had looked at the positions of one of the cases but this information can't be shared on the issue. Feel free to check the positions by running the samtools command on the alignment files (without the -c option to avoid the counting and showing the mapping reads instead). I have shared the cases and alignment files in slack.

**Comment by fevac** [comment]
@khurrammaqbool I know that. I just don't think it's needed in this case. If you consider that tests and further investigation are needed feel free to open a document and add your findings there as I won't be doing testing at this point. 

If you don't have any additional comments I will move on and implement the suggested solution next week

**Comment by vwirta** [comment]
I think the key here is to be able to tell the clinicians that there is a likely IGH::DUX4 fusion event. The exact details of the molecular event are not as important. I think they would order for example a FISH analysis to confirm an NGS finding. 
I can help putting you in contact with key clinical colleagues to discuss their needs, if needed.

**Comment by fevac** [comment]
@vwirta I don't think this is needed. We got this feature request from them and had already communicate with them. They wanted to add this command to be able to detect this rearrangement. The only pending question was how to report the results. The solution we discussed last week was to include it in the SV vcf with fixed coordinates and flag the uncertainty of the breakpoint coordinates

**Comment by ivadym** [comment]
Feature added to develop, and the hg38 implementation will be tracked here https://github.com/Clinical-Genomics/BALSAMIC/issues/1421
