### ISSUE TITLE
Correct tool name in Sentieon Dedup metrics

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1290]
## Need

In order to make multiqc pick up the Sentieon Dedup metrics file containing the PERCENT_DUPLICATES I had to trick it that it was a report from picard markduplicates (which produce a similar report). This at least allowed us to trace the duplicates in the multiqc_data.json, but was a not the ideal solution.

I have made an issue on multiqc for request that Sentieon Dedup be added as a module. 
https://github.com/ewels/MultiQC/issues/2144

## Suggested approach
- [x] Remove the line in the sentieon dedup rule in BALSAMIC which adds the picard line to the metrics report!

## Blockers
- [x] MultiQC has added Sentieon Dedup as a module (when this is merged https://github.com/ewels/MultiQC/pull/2110 we can update MultiQC and remove the sed-line from the dedup rule)
- [x] Latest version of MultiQC does not pick up Somalier output. Bug report opened (https://github.com/MultiQC/MultiQC/issues/2596) However, version 1.18 does seem to work, and also contains the changes related to Sentieon metrics. So I will proceed with this older version.

**Comment by mathiasbio** [comment]
Multiqc has been updated with the required feature, so we can update multiqc and test if it now picks up Sentieon QC reports

**Comment by ivadym** [comment]
Adressed here: https://github.com/Clinical-Genomics/BALSAMIC/pull/1441
