### ISSUE TITLE
Wrong metrics name for TGA cases from qc/picard.rule 

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1294]
**Describe the bug**

After removing realignment in: https://github.com/Clinical-Genomics/BALSAMIC/pull/1272 the name of the QC files from picard.rule was forgotten to be renamed to reflect this change.

"samplename.dedup.realign.alignmetric" should be --> "samplename.dedup.alignmetric" etc...

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**If workflow, which rules**
If possible, and using the Snakemake workflows, the name of the affected rules and workflows.

**Screenshots**

**Version (please complete the following information):**
`balsamic --version` develop version

**Additional context**

**Comment by ivadym** [comment]
Done https://github.com/Clinical-Genomics/BALSAMIC/pull/1288 🎉
