### ISSUE TITLE
Investigate and revise QC thresholds in balsamic

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1297]
## Need

The current QC thresholds in BALSAMIC result in an increased and unnecessary burden on the production workflow which increases TAT and makes the work more tedious. We need to investigate the current QC thresholds and identify ways that they can be improved without reducing the quality of the analyses we deliver.

A discussion has been created for the work that will be done to address this issue here:
https://github.com/Clinical-Genomics/BALSAMIC/discussions/1259

## Suggested approach
- Investigate current QC distributions for relevant QC-threshold parameters 
- Document results in above discussion
- Discuss with colleagues the revision of the QC-thresholds
- Communicate with lab if relevant discoveries are made that influence the QC thresholds to see if improvements can be made

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Requests/suggestions/bugs solved by the feature
*Link any feature requests/bug reports or other issues which this would solve*

## Can be closed when
*Link the issues needed to be closed for this to be implemented*

## Infrastructure changes
*Create/Link issues in cg or servers needed for this feature*

## Blockers
*Anything preventing this from happening?*

**Comment by pbiology** [comment]
I added this to the release 14 milestone, as discussed at the cancer weekly meeting. If we do find thresholds which if updated immediately would improve life for the production team we should consider adding them to the deployed release.

**Comment by beatrizsavinhas** [comment]
A note on this: We should think about making the QC checks dependant on the apptags of the samples as well. For example normal samples are often ordered with apptag `WGSPCFC030` which aims at 30X coverage but balsamic only checks PCT_15X for these samples.

**Comment by pbiology** [comment]
> A note on this: We should think about making the QC checks dependant on the apptags of the samples as well. For example normal samples are often ordered with apptag `WGSPCFC030` which aims at 30X coverage but balsamic only checks PCT\_15X for these samples.

Good feedback!

**Comment by mathiasbio** [comment]
Replacing this issue with the assessment issue: https://github.com/Clinical-Genomics/BALSAMIC/issues/1374
