### ISSUE TITLE
[User Story] Move QC validation to CG

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#1309]
### Need

As a Balsamic developer, I want to simplify the QC extraction and validation workflow, so that I can efficiently manage the increasing complexity of various workflow types, panels, and application tags.

### Suggested approach

Move this logic to CG and start using the new status we have added to Trailblazer with RNAfusion (`AnalysisStatus.QC`).

### Considered alternatives

Keep the QC checks in Balsamic while increasing the CLI complexity.

### Risk assessment

- [ ] Needed
- [X] Not needed

### System requirements assessed

- [X] Yes, I have reviewed the system requirements

### Requirements affected by this story

- Balsamic workflow should be refactored in CG

### Can be closed when

- [ ] QC validation is removed from Balsamic
- [ ] Balsamic QC validations is integrated into CG 

### Blockers

- https://github.com/Clinical-Genomics/BALSAMIC/issues/1297

**Comment by pbiology** [comment]
One thing to take into account here is [Project Maven](https://github.com/Clinical-Genomics/project-planning/issues/453). 
The idea being that QC data should be collected from the pipelines and stored in a centralised database. From there CG would be then doing the QC checks. So it is quite similar as to what you are describing here.

**Comment by ivadym** [comment]
Today, we are generating the `metrics_deliverables.yaml` in Balsamic. The idea here is to move this logic to CG. It appears that Maven only requires the QC file, regardless of its source, so I don't think there is any overlap
