### ISSUE TITLE
Filtering strategy

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/BALSAMIC#1314]
## Need
We should improve the filtering strategy for SVs, ideally with soft-filtering whenever possible. 

We have many open issues regarding this. We should add these changes or close these issues if not relevant:

SNVs/Indels
- Sentieon filters: https://github.com/Clinical-Genomics/BALSAMIC/issues/1258
- Variant in normal: https://github.com/Clinical-Genomics/BALSAMIC/issues/1254
- Max AF: https://github.com/Clinical-Genomics/BALSAMIC/issues/1180 and https://github.com/Clinical-Genomics/BALSAMIC/issues/1166
- Pathogenic; germline: https://github.com/Clinical-Genomics/BALSAMIC/issues/1256

SVs
- Refine maxDepth filtering: https://github.com/Clinical-Genomics/BALSAMIC/issues/1161
- Triallelic sites: https://github.com/Clinical-Genomics/BALSAMIC/issues/1293
- Rescue variants (too vague): https://github.com/Clinical-Genomics/BALSAMIC/issues/1133
- Exclusion list (too vague): https://github.com/Clinical-Genomics/BALSAMIC/issues/1132
- Reduce number of variants and technical artifacts: https://github.com/Clinical-Genomics/BALSAMIC/issues/1131 and https://github.com/Clinical-Genomics/BALSAMIC/issues/1316

UMI workflow
- Reduce number of variants: https://github.com/Clinical-Genomics/BALSAMIC/issues/1149

## Suggested approach
*A few sentences about the intended solution* 

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Requests/suggestions/bugs solved by the feature
*Link any feature requests/bug reports or other issues which this would solve*

## Can be closed when
*Link the issues needed to be closed for this to be implemented*

## Infrastructure changes
*Create/Link issues in cg or servers needed for this feature*

## Blockers
*Anything preventing this from happening?*

**Comment by pbiology** [comment]
This was created as a meta-issue for voting in the pitch round. Let's close this as there are sub-stories for all
