### ISSUE TITLE
dry run worked but not the actual run

### ISSUE THREAD

**Issue by yiyi1247** [Clinical-Genomics/BALSAMIC#1315]
```

mkdir -p /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/tmp/5ldwi727;
export TMPDIR=/proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/tmp/5ldwi727;

fastqc --threads 2 /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastq/G1A1439p24_R_1.fastq.gz --dir /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/tmp/5ldwi727 --outdir /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastqc/;

fastqc --threads 2 /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastq/G1A1439p24_R_2.fastq.gz --dir /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/tmp/5ldwi727 --outdir /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastqc/;

Activating singularity image /proj/sens2023551/wgs_nes/balsamic_cache/12.0.2/containers/align_qc.sif
INFO:    Converting SIF file to temporary sandbox...
FATAL:   while preparing image: while handling /proj/sens2023551/wgs_nes/balsamic_cache/12.0.2/containers/align_qc.sif: while extracting image: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled
: exit status 1
[Wed Nov  1 09:19:37 2023]
Error in rule fastqc:
    jobid: 39
    output: /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastqc/G1A1439p24_R_1_fastqc.zip, /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastqc/G1A1439p24_R_2_fastqc.zip
    shell:

mkdir -p /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/tmp/5ldwi727;
export TMPDIR=/proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/tmp/5ldwi727;

fastqc --threads 2 /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastq/G1A1439p24_R_1.fastq.gz --dir /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/tmp/5ldwi727 --outdir /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastqc/;

fastqc --threads 2 /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastq/G1A1439p24_R_2.fastq.gz --dir /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/tmp/5ldwi727 --outdir /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/analysis/fastqc/;

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/BALSAMIC_run/.snakemake/log/2023-11-01T091906.426950.snakemake.log
(base) [leile@sens2023551-bianca wgs_nes]$ singularity version
3.11.5
(base) [leile@sens2023551-bianca wgs_nes]$
```

**Comment by yiyi1247** [comment]
may i kindly ask what could be the issue>?

```
(base) [leile@sens2023551-bianca wgs_nes]$ cat balsamic.sh
#!/bin/bash -l
#SBATCH -A sens2023551
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 4-00:00:00
#SBATCH -J leilei

export PATH="/home/leile/singularity/bin:$PATH"
export SENTIEON_LICENSE=/proj/sens2023551/wgs_nes/Karolinska_Institute_eval.lic
export SENTIEON_INSTALL_DIR="/proj/sens2023551/wgs_nes/sentieon-genomics-202308"

/home/leile/.local/bin/balsamic --loglevel DEBUG run analysis --sample-config /proj/sens2023551/wgs_nes/BalsamicResult/G1A1439/G1A1439.json  --run-mode local --snakemake-opt "--cores 2" --run-analysis
```

**Comment by ivadym** [comment]
This log line is the key and is related to your Singularity installation:

> FATAL:   while preparing image: while handling /proj/sens2023551/wgs_nes/balsamic_cache/12.0.2/containers/align_qc.sif: while extracting image: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled

The user namespace needs to be enabled on your system, so you can perform root operations inside the container without being an actual root user. You have some information in the [Singularity documentation](https://docs.sylabs.io/guides/3.11/admin-guide/user_namespace.html#user-namespaces-fakeroot) regarding Namespaces and User Namespace Requirements.

I would check with your HPC admins as they may have specific policies and configurations that need to be followed when working with containers. 

Good luck!

**Comment by yiyi1247** [comment]
Thank you so much!!! @ivadym Just FYI, The singularity 3.11.5 is I installed, the singularity from Uppmax's version is very low:
```
(base) [leile@sens2023551-bianca ~]$ singularity version
INFO:    /etc/singularity/ exists; cleanup by system administrator is not complete (see https://apptainer.org/docs/admin/latest/singularity_migration.html)
1.2.3-1.el7
(base) [leile@sens2023551-bianca ~]$
```
That is why in my sbatch script i had this line in hope to use 3.11.5 that I installed
export PATH="/home/leile/singularity/bin:$PATH"

**Comment by ivadym** [comment]
I believe they might need to [enable](https://docs.sylabs.io/guides/3.11/admin-guide/user_namespace.html#user-namespace-requirements) the user namespace on your working node. Since you're attempting to run the analysis locally (`--run-mode local`), it could also be possible that it's already enabled for the compute nodes (have you tried submitting to Slurm/SGE?). For a definitive answer, I would recommend reaching out to them for details, as I'm not aware of the specific Singularity configurations on Bianca.

**Comment by yiyi1247** [comment]
Thank you @ivadym I would contact UPPMAX now regarding this issue, It is very likely the Singularity configuration on uppmax bianca is off.

```
(base) [leile@sens2023551-bianca wgs_nes]$ singularity exec greenvaran_latest.sif smallvars
INFO:    Converting SIF file to temporary sandbox...
FATAL:   while preparing image: while handling greenvaran_latest.sif: while extracting image: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled
: exit status 1
(base) [leile@sens2023551-bianca wgs_nes]$
```

**Comment by pmitev** [comment]
Bianca is running `apptainer`
```bash
singularity --version 
apptainer version 1.2.4-1.el7
# APPTAINER_SUID_INSTALL=1
```
Users can build (as long the sources are available locally - /there is no regular connection to Internet/) and run containers.
Tools like `snakemake` and `nextflow` are running just fine when the containers are brought locally. For conda - there ar elocal mirror of most common channels.

Somewhat relevant question, since one can not access internet from within Bianca how this licensing will work?
```bash
export SENTIEON_LICENSE=IP:Port
```

**Comment by yiyi1247** [comment]
@ivadym If I use singularity as @pmitev mentioned, balsamic would error out during prerequiste check
```
(base) [leile@sens2023551-bianca wgs_nes]$ cat slurm-1243.out
balsamic sens2023551-b9.uppmax.uu.se 2023-11-08 11:48:27 BALSAMIC.commands.base pid:28061 [INFO] Running BALSAMIC version 12.0.2
balsamic sens2023551-b9.uppmax.uu.se 2023-11-08 11:48:27 BALSAMIC.commands.run.analysis pid:28061 [INFO] BALSAMIC started with log level DEBUG.
Building DAG of jobs...
WorkflowError:
Minimum singularity version is 2.4.1.
(base) [leile@sens2023551-bianca wgs_nes]$ singularity --version
apptainer version 1.2.3-1.el7
(base) [leile@sens2023551-bianca wgs_nes]$
```

**Comment by pmitev** [comment]
Seems it is related to snakemake version. The tool installs "snakemake==6.5.3" https://github.com/Clinical-Genomics/BALSAMIC/blob/master/setup.py which might not be enough - look here https://snakemake.readthedocs.io/en/latest/project_info/history.html for issues related to apptainer.

**Comment by ivadym** [comment]
That's unfortunate. We'll be making a new major release at the end of this month, and we've actually updated Snakemake to the latest version. However, you'll still need to find a workaround to use the apptainer containers. Probably, you could first create the `config.json` file and then update it manually to point to the apptainer containers. It seems pretty straightforward based on their [release issue](https://github.com/snakemake/snakemake/commit/bcbdb0bc44746961838f9603e42d0e171407c740), but I'm not aware if more changes will be needed. It's on our roadmap, but we haven't looked into it in more detail yet.

Thanks @pmitev for your input!
