### ISSUE TITLE
Export observations from Loqusdb and start annotating variants in Balsamic

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#1318]
### Need

We would like to start annotating variants in Balsamic using the Loqusdb somatic and germline exported observations. 

### Suggested approach

A method for annotating variants has been added to Balsamic: https://github.com/Clinical-Genomics/BALSAMIC/issues/1146. The next step is to [export germline and somatic variants](https://atlas.scilifelab.se/infrastructure/loqusdb/export/) from their respective databases and start feeding them into the analysis.

### Risk assessment

- [ ] Needed
- [X] Not needed

### System requirements assessed

- [X] Yes, I have reviewed the system requirements

### Can be closed when
- [x] `loqusdb-clinical` variants exported
- [x] `loqusdb-somatic` variants exported
- [x] `loqusdb-tumor` variants exported

### Blockers

Database is currently being filled up. 

`2023-11-02`
- `loqusdb-somatic`: 234 samples
- `loqusdb-tumor`: 271 samples

**Comment by khurrammaqbool** [comment]
The latest version of databases are exported.

|  Databases  | Number of cases  | Variants  | 
|---|---|---|
|  loqusdb-clinical SNV  | 10786   |  273324707 | 
| loqusdb-clinical SV  |  10786 |  3439616 | 
|  loqusdb-somstiv SNV  | 238  | 1131172  | 
|  loqusdb-somatic SV |  238 | 562426  | 
|  loqusdb-germline SNV  | 275  |  38209100 |
