### ISSUE TITLE
[User Story] Replace alt_allele_in_normal filter in TNscope

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1335]
### Need

As a clinician I want to be able to detect somatic variants using a matched normal sample to filter out germline-variants, but I want the filtering-strategy to be appropriately set so that true somatic variants with some minor presence in the normal sample (due to Tumor In Normal Contamination, or artefacts) are not filtered out.

It has been observed specifically for TNscope an issue with the "alt_allele_in_normal filter" for this, and which seems to be way too stringent.

### Suggested approach

Remove alt_allele_in_normal filter, and add a bcftools command which we have more control over. Something like this:

`bcftools filter -s high_normal_frac -e '(FORMAT/AF[1] / FORMAT/AF[0]) >= 0.5' -m`

Where we would set this filter if the normal AF is present at 50% or more of the tumor AF. For example:
IF T_AF = 100%
N_AF = 100% filter
N_AF = 70% filter
N_AF = 50% filter
N_AF = 49% keep

Perhaps it could be more stringent. But we already have a lot of germline filtering applied. 

### System requirements assessed

- [ ] Yes, I have reviewed the system requirements

### Risk assessment needed

- [ ] Needed
- [ ] Not needed

### Can be closed when

 The "alt_allele_in_normal filter" from TNscope has removed / replaced.

### Anything else?

SEE ORIGINAL FEATURE ISSUE FOR MORE INFO!
https://github.com/Clinical-Genomics/BALSAMIC/issues/1254

Example:
Out of 1511 variants in a matched WGS TN case  with only "alt_allele_in_normal" filter se, **1002 of them had a total number of reads supporting the variant = 1**

![t_af_n_af_alt_allele_in_normal_ad1](https://github.com/Clinical-Genomics/BALSAMIC/assets/14308912/fdd5b5b0-4b8a-42a9-bc64-0b8df0ec7d55)

**Comment by mathiasbio** [comment]
Closing original issue.

**Comment by ivadym** [comment]
The PR has been merged, should we close it @mathiasbio?
