### ISSUE TITLE
Improve PR template

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#1356]
**Description**

The current PR template could be more effective in ensuring that all necessary steps and tests are completed during feature development. Often, we overlook integrating changes with other tools (Scout, CG, Hermes, ...), updating documentation, and considering broader impacts on other workflows and variant calling.

**Suggested solution**

Improve the PR template to address these areas more explicitly.

**This can be closed when:**

We have a clear method for documenting all dependencies related to the development of a new feature.

**Comment by mathiasbio** [comment]
I completely agree! Great suggestion. Maybe we should have some standard set of questions we need to answer in the PR description before we're allowed to merge it, or something like that.
