### ISSUE TITLE
[User Story] Update Sentieon

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1384]
### Need

As a hospital geneticist I want:
- As many true variants as possible with as few false positive variants
- As fast as possible
- And as cheaply as possible

The new version of Sentieon:  [202308](https://support.sentieon.com/manual/appendix/releasenotes/#release-202308) contains changes that allow us to affect all of these aspects. 

Our version in production: [202010.02](https://support.sentieon.com/manual/appendix/releasenotes/#release-202010-02)

Some relevant changes since version 202010.02:
- Modified TNscope® AF output format.
- Solved issue in duplex umi consensus that results depend on internal data order.
- **Improved speed of bwa mem.**
- **Solved issue in TNscope such that evidence from overlapping read pairs were not adequately accounted for.**
- Solved issue in duplex umi consensus that could output zero-length reads.
- **Added support in Dedup algorithm to perform UMI barcode error correction.**
- **Added support in LocusCollector and Dedup algorithms to perform consensus based deduplication as well as UMI barcode aware deduplication.**
- **Improved machine learning model for TNscope.**
- Improved consensus of INDELs in Dedup algorithm.
- Improved DNAscope pipeline speed and accuracy with a BWA model.

In summary:
- Changes to variant callers could improve accuracy and sensitivity.
- Changes to bwa mem could decrease the TAT
- Inclusion of UMIs to Dedup could save ~20% of the reads wrongly discarded as duplicates, and improve quality of reads (https://github.com/Clinical-Genomics/BALSAMIC/issues/1361)

### Suggested approach

In an update Sentieon PR temporarily hard-code the changes to the path to the newest version of Sentieon:
- Ensure that all workflows are behaving as normal
- Basically perform a mini-validation in the PR, checking to see that the variant-calling is working as normal and that all files can be produced

### System requirements assessed

- [ ] Yes, I have reviewed the system requirements

### Risk assessment needed

- [ ] Needed
- [ ] Not needed

### Can be closed when

  - [ ] Sentieon has been updated to most recent version, or desired new version.

### Anything else?

Replaces feature issue: https://github.com/Clinical-Genomics/BALSAMIC/issues/1250

**Comment by henrikstranneheim** [comment]
It would also be great to have separate stage and prod binaries. Then you can test and verify before changing production.

**Comment by mathiasbio** [comment]
It would! Right now for testing I have hard-coded the path to the new version of Sentieon in balsamic. But I wonder if I could make a branch in:

https://github.com/Clinical-Genomics/servers

And change here to the new version of Sentieon in a branch to use for my testing.

 https://github.com/Clinical-Genomics/servers/blob/3dafb72335fb28c233d4cebac5e1ea03baec87cc/resources/hasta.scilifelab.se/usestage.sh#L48

**Comment by ivadym** [comment]
> It would! Right now for testing I have hard-coded the path to the new version of Sentieon in balsamic. But I wonder if I could make a branch in:
> 
> https://github.com/Clinical-Genomics/servers
> 
> And change here to the new version of Sentieon in a branch to use for my testing.
> 
> https://github.com/Clinical-Genomics/servers/blob/3dafb72335fb28c233d4cebac5e1ea03baec87cc/resources/hasta.scilifelab.se/usestage.sh#L48

Yes, that's the file we need to update 👍

**Comment by mathiasbio** [comment]
I'm in contact with Sentieon trying to understand when they think the new model will come, and if they think it would be worthwhile to update TNscope regardless and run without the ML model. It could be that we could just remove the model entirely for now and then add it back in once they have deployed the new version.

**Comment by mathiasbio** [comment]
Reply from Sentieon:

> Hi Mathias,
> 
> We've made a number of improvements to TNscope since the 202010.02 release. It should be possible to improve the quality of the analysis by updating Sentieon without the model file. However, you will need to supplement the variant calling with some post-call filtering (effectively replacing the filtering performed by the TNscope model).
> 
> We have some general recommendations for variant calling and filtering without a TNscope model at, [https://support.sentieon.com/appnotes/somatic/](https://support.sentieon.com/appnotes/somatic/#). You might try updating to the latest version of Sentieon and performing filtering according to the recommendations in the app note. Just be aware that you will likely need to tune the filtering for your data.
> 
> Best regards,
> Don

With this in mind I will proceed with my PRs using the updated version of Sentieon, and will keep an eye on the effect on the variant calling from not using the ML model.
