### ISSUE TITLE
[User Story] Create PON for lymphoid 7.3

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1407]
### Need

As a geneticist interpreting samples from the lymphoid panel I want somatic CNV calls with as little noise as possible, currently we offer normal filtering with CNVkit using only matched normals for the lymphoid panel. But it would probably be better to use a PON, and to have this PON available for tumor-only analyses as well where no matching normal is available.

### Suggested approach

Probably we have enough samples now to create a PON, though we might want to create different PONs for different tissue-origins if possible, from blood (cfDNA) or from tissue (gDNA)

https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=66511#reply

One issue is that the lymphoid panel will be updated quite soon to correct for some missing probes on X / Y chromosomes. But it might not be an issue for the PON. Either way, I think we should generate the PON, and if there will be an issue for the new version, try to adjust the PON to work for that panel. 

This topic has been discussed in this ticket: 
https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=66511

I have made a list of all samples currently run with this version of the lymphoid panel, divided into genders: 
https://docs.google.com/spreadsheets/d/1p6fgZXqJq3YOQolyLIjfJkAA5OuWSxesRDabr9mLmdc/edit#gid=982111950

In total 51 male, and 42 female samples have been run that I could find. This should be enough to generate the PON.

### System requirements assessed

- [ ] Yes, I have reviewed the system requirements

### Risk assessment needed

- [ ] Needed
- [ ] Not needed

**Comment by mathiasbio** [comment]
Created cases: 
- helpfulsunfish for male PON
- rationaldogfish for female PON

**Comment by ivadym** [comment]
If we begin generating sex-specific PONs, we will need to update the parsing of these references in CG

**Comment by mathiasbio** [comment]
I could give it a try to implement it : )

**Comment by ivadym** [comment]
Currently, it only takes the latest version that matches the provided panel. So, we need to consider the sex in the file name as well. We can either find a temporary solution to support two different PON parsing structures or regenerate the other PONs considering the sex

**Comment by mathiasbio** [comment]
I think it would make sense to account for the possibility of having 3 possible PONs, as there may sometimes not be enough samples to produce sex-specific PONs, or in the case of some panels, perhaps not exist any genes on the sex-chromosomes. I'll give a try in creating the functionality for the sex-specific PONs and ask for some review later if you don't have any objections : D I'd be happy to learn some more CG

**Comment by ivadym** [comment]
Sounds great! I think the long term solution would be to just have a comprehensive config dictionary in servers where we can group these references by sex, genome version, etc. but yeah for now we can proceed with that ⭐

**Comment by mathiasbio** [comment]
Turns out that CNVkit PON creation already takes into account and corrects for the sex of the samples https://www.biostars.org/p/193938/
So I will close the PR that I made in CG 🥲

**Comment by mathiasbio** [comment]
PON has been created, now testing to see that it works with an example. Reporting results here: https://docs.google.com/spreadsheets/d/1p6fgZXqJq3YOQolyLIjfJkAA5OuWSxesRDabr9mLmdc/edit#gid=1722231255

**Comment by fevac** [comment]
Just making some notes here from this cnvkit issue https://github.com/etal/cnvkit/issues/635:
- The main dev recommends pooling sex together in a single PON as the more samples -> the more accurate
- However sex detection has a history of issues, so it's recommended to have a look at the logs and make sure that the sex detected is what we expect

**Comment by mathiasbio** [comment]
This can be closed as we have this PR in the target panel bed repository: https://github.com/Clinical-Genomics/target_capture_bed/pull/128
