### ISSUE TITLE
Verification Report [v14.0.1]

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#1410]
# Balsamic Verification Report

## Release Information

- Version: `v14.0.1`
- Release Type: `Patch`
- Release Commit: [Release Commit]
- Release Date: [Release Date]

## Person(s) involved in the development of new release
- Developer/s: KM, MJ
- Verification operator/s: KM, MJ
- Verification reviewer/s: VI

## Summary

The purpose of this verification is to fix a bug appeared in PureCN rules crashing due to the purecn command failing to estimate purity and ploidy. This leads to the whole pipeline crash because of the bash strict mode in effect from snakemake. The solution, implemented in the current release, is to bypass the exit code and making the condition associated, in case of failing the command to estimate purity and ploidy, with the output generating default values of purity=0.02 and ploidy=2, with a comment "FAILED PURITY ESTIMATION" to the table.

In addition a small bug fix has been included wherein the wrong container name used in the CNVkit PON creation workflow has been corrected.

These are the goals of this verification:
1. Evaluate the solution performs as expected, the analysis completes without crashing and a default table is generated in case purity and ploidy estimation fails. 

## Changelog

| Type    | Pull Request | Performed tests              |
|---------|--------------|------------------------------|
| Fixed   | https://github.com/Clinical-Genomics/BALSAMIC/pull/1406       | Analysis completed generating the default table  |
| Fixed   |https://github.com/Clinical-Genomics/BALSAMIC/pull/1412       |  CNVkit PON creation rules no longer failing with missing container  |

## Pre-Verification Checklist

Before proceeding with the verification process, ensure that the following tasks have been completed:

- [x] [Install Balsamic in stage and production environments in hasta and build its cache](https://atlas.scilifelab.se/infrastructure/BALSAMIC/balsamic/#instructions-for-installation).
    - BALSAMIC was installed on stage after making the `BALSAMIC release_v14.0.1` branch, from the instructions given above:
     1. `sudo <...>`
     2. `tmux new -s <...>`
     3. Activate stage and conda environments.
     4. `pip uninstall balsamic`
     5. `pip install --no-cache-dir -U git+https://github.com/Clinical-Genomics/BALSAMIC@release_v14.0.1`
     6. `COSMIC_KEY=<...>`
     7. `balsamic init --out-dir <STAGE_PATH>  --account <...> --cosmic-key ${COSMIC_KEY}  --genome-version hg19 --cache-version 14.0.1 --run-mode local --snakemake-opt "--cores 4" -r`
     8. balsamic init --out-dir /home/proj/stage/cancer/balsamic_cache --account development --cosmic-key ${COSMIC_KEY} --genome-version hg38 --cache-version 14.0.1 --run-mode local --snakemake-opt "--cores 8" -r
     9. Merged https://github.com/Clinical-Genomics/BALSAMIC/pull/1412 to the release v14.0.1 branch
     10. Reinstalled BALSAMIC on stage and removed containers from the cache on stage
     11. balsamic init --out-dir /home/proj/stage/cancer/balsamic_cache --account development --cosmic-key ${COSMIC_KEY} --genome-version canfam3 --cache-version 14.0.1 --run-mode local --snakemake-opt "--cores 8" -r

- [x] Confirm the availability of necessary resources, such as test cases.
- [x] Review the changelog and ensure all changes and updates are documented:

    | Document               | Sections to Be Updated | Pull Request |
    |------------------------|------------------------|--------------|
    | Balsamic Documentation | NA   | NA       |
    | Atlas Documentation    | NA        | NA       |

- [x] Set up the stage environment with the necessary software and configurations:

    | Software | Current Version | Pull Request with the Required Updates |
    |----------|-----------------|----------------------------------------|
    | CG       | NA  | NA                                 |
    | Servers  | NA   | NA                                 |
    | Hermes   | NA   | NA                                 |

### Workflow Integrity Verification Cases

| Case ID        | Analysis type      | Expected QC                                           | Status    |
|----------------|--------------------|-------------------------------------------------------|-----------|
| `acetuna`      | QC, tumor-only     | Pass                                                  | Pass |
| `civilsole`    | WGS, tumor-only    | Fail (`PCT_60X=0.004532`)                             | Pass |
| `fleetjay`     | WGS, tumor-normal  | Fail (`PCT_60X=0.00836`)                              | Pass |
| `setamoeba`    | TGA, tumor-only    | Pass                                                  | Pass |
| `unitedbeagle` | TGA, tumor-normal  | Pass                                                  | Pass |
| `uphippo`      | UMI, tumor-only    | Fail (`GC dropout=1.650392`)                          | Pass |
| `equalbug`     | UMI, tumor-normal  | Fail (`GC_DROPOUT=1.087173` and `RELATEDNESS=-0.524`) | Pass |
| `bettertahr` | TGA, tumor-only  | (Fails to compute purity and ploity and uses default)                                                  | Pass |
| `firstlobster` | CNVkit PON test case (myeloid 5.3)  |            Workflow finishes without error and produces PON                                   | Pass |

- [x] This section has been verified successfully

### Storage, Delivery and Upload Integrity Verifications

| Processes                           | Affected in current version | Affected workflows     | 
|-------------------------------------|-----------------------------|------------------------|
| New files to be stored              | No                      | NA  |
| New files to be delivered           | No                      | NA  | 
| New files to be uploaded to Scout   | No                      | NA | 
| Changes to Housekeeper IDs          | No                      | NA | 
| Changes to Scout upload             |  No                      | NA |

| Case ID        | Analysis type       | Storage status | Delivery status | Upload  status |
|----------------|---------------------|----------------|----------------|----------------|
| `acetuna`      | QC, tumor-only      | NA   | NA   | NA   |
| `civilsole`    | WGS, tumor-only     | NA   | NA   | NA   |
| `fleetjay`     | WGS, tumor-normal   | NA   | NA   | NA   |
| `setamoeba`    | TGA, tumor-only     | NA   | NA   | NA   |
| `unitedbeagle` | TGA, tumor-normal   | NA   | NA   | NA   |
| `uphippo`      | UMI, tumor-only     | NA   | NA   | NA   |
| `equalbug`     | UMI, tumor-normal   | NA   | NA   | NA   | 

- [x] This section has been verified successfully, or been identified as irrelevant for the current verification

### Version Specific Verification Cases

| Case ID  | Analysis type     | Expected QC | Status    |
|----------|-------------------|-------------|-----------|
| `bettertahr` | TGA, tumor-only  | (Fails to compute purity and ploity and uses default)                                                  | Pass |
| `firstlobster` | CNVkit PON test case (myeloid 5.3)  |            Workflow finishes without error and produces PON                                   | Pass |
- [x] This section has been verified successfully, or been identified as irrelevant for the current verification

### Issues Identified

No Issues on related to the verification of BALSAMIC, but some challenges running the validation cases on stage. The documentation to install and run BALSAMIC on stage is not up-to-date.

### Recommendations

 - Prioritise the bug related to the validation cases being compressed, as it significantly affects the dynamics of the validation process.
 - Update the documentation to install and run BALSAMIC on stage. 
 - Update validation report to add PON case created for the current verification.

### Conclusion

BALSAMIC patch release v14.0.1 fixes two bugs. One related to the handling of the workflow in case the computation  purity and ploidy fails and second a fix for container name in the PON workflow. The verification process has been conducted successfully. The patch release has been evaluated positively, for both bug fixes, with different QoS scenarios. 

---

## Approval
- Verification review: VI
- Date: 2024-03-19

## Deployment
- Responsible: [Name]
- Date: [Date]

**Comment by ivadym** [comment]
Signed! @khurrammaqbool @mathiasbio

I've marked as NA the section you identified as irrelevant for more clarity and checked the CNV report PDF! Everything looks all right! ⭐

**Comment by ivadym** [comment]
What's the status, @khurrammaqbool? Have we already rerun these cases? Are we deploying tomorrow? It would be good to bump the version today and copy the Balsamic cache from stage to production

**Comment by mathiasbio** [comment]
Have confirmed, equalbug, upphippo and acetuna has been re-run and finished yesterday with the correct workflow 👍 @ivadym

**Comment by ivadym** [comment]
Nice! Thanks @mathiasbio! I've updated the signature date so I think we're good to go 🛫
