### ISSUE TITLE
PoN for GMCKsolid v. 4.2

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/BALSAMIC#1460]
### Need

As we have a PoN for GMCKsolid v 4.1 and now will switch to a new version of the panel in production there is a need for a new PoN. The new version of the design is approximately 60% larger.

### Suggested approach

Generate a new PoN

### System requirements assessed

- [ ] Yes, I have reviewed the system requirements

### Risk assessment needed

- [ ] Needed
- [ ] Not needed

**Comment by mathiasbio** [comment]
Created this ticket to communicate with customers regarding normal samples: https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=71458

**Comment by mathiasbio** [comment]
Hoping to build the PON in this feature issue: https://github.com/Clinical-Genomics/BALSAMIC/pull/1465#issuecomment-2225460673 but let's see if there are any normal samples that we can use
