### ISSUE TITLE
Naming of --sample-id in balsamic config

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#149]
**Is your feature request related to a problem? Please describe.**
When running `balsamic config sample --help` , no description for naming `--sample-id` is written when running paired analysis

**Describe the solution you'd like**
Include in which order the Tumor / Normal should be named in `--sample-id`. For example: "TumorName_NormalName"

**Describe alternatives you've considered**
-

**Additional context**
-

**Expected output for the feature**
-

**Current BALSAMIC version**
All versions

**Comment by hassanfa** [comment]
sample_id is renamed to case_id and fixed in 3.0.0 release
