### ISSUE TITLE
unique sample names to final bam

### ISSUE THREAD

**Issue by imsarath** [Clinical-Genomics/BALSAMIC#243]
**Is your feature request related to a problem? Please describe.**
Sample names or unique IDs should be added to final bam files to track the files later. Now we are using generic sample names such as TUMOR or NORMAL for all samples.

**Describe the solution you'd like**
we can set the sample name as sample id with normal and tumor tag. ie. ACC12345_NORMAL, ACC12346_TUMOR or _N, _T.

**Describe alternatives you've considered**
The naming convention for bam files can be altered.

**Current BALSAMIC version**
`balsamic --version`
balsamic, version 3.3.1

**Comment by hassanfa** [comment]
Checkpoints will be TUMOR and NORMAL in sample name. No need to have unique sample names for now.
