### ISSUE TITLE
Add reference genome sequence as an input for AT/GC dropout calculations

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#264]
**Is your feature request related to a problem? Please describe.**
Picard hsmetrics doesn't report GC/AT dropout because it doesn't have reference genome as input

**Describe the solution you'd like**
Add reference

**Describe alternatives you've considered**
Use CollectGCBias from picard

**Additional context**
https://broadinstitute.github.io/picard/command-line-overview.html#CollectHsMetrics

**Expected output for the feature**
If possible, an example of expected output

**Current BALSAMIC version**
`4.0.1`

**Comment by hassanfa** [comment]
Keyvan, this one's quite straightforward.

**Comment by keyvanelhami** [comment]
Done! closing
