### ISSUE TITLE
Add rhocall / LoH as for RD

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/BALSAMIC#277]
Request from clinicians at Scout for cancer meeting

**Describe the solution you'd like**
Suggest to contact MIP developers and check how they did it

**Expected output for the feature**
Functionality to visualise these already exists in Scout

**Comment by hassanfa** [comment]
related to https://github.com/Clinical-Genomics/BALSAMIC/issues/564 so I'm closing this one and we can use GENS or Chromograph.
