### ISSUE TITLE
Option to deliver results as CRAM instead of BAM for panel runs

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#286]
**Is your feature request related to a problem? Please describe.**
BAM output files take too much storage space and it is a recurring storage issue on Hasta.

**Describe the solution you'd like**
Convert BAM files to CRAM.

**Describe alternatives you've considered**
None.

**Additional context**
CRAM index files should also be readily available

**Expected output for the feature**
`tumor.merged.bam` to `tumor.merged.cram`. And all `bai` files to `crai`

**Current BALSAMIC version**
`4.1.0`

**Comment by henrikstranneheim** [comment]
@hassanfa Now that cg can store old balsamic files in Housekeeper - it would be great if the next version of Balsamic, particularly for WGS, will store CRAM directly and not BAMS. We have made a process that will automatically convert to CRAM from HK BAMS if the case is loaded in Scout. But of course the best thing is to not have to use that process at all for new files.

Do you have a time estimate when you will have time to work on this one?

**Comment by hassanfa** [comment]
Henrik,
I think after 2-3 weeks I'll work on this issue. We don't have that many runs for BALSAMIC in near future.
