### ISSUE TITLE
Bioinformatic workflow

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/BALSAMIC#302]

**Comment by hassanfa** [comment]
I think some text is missing. Is this doc related?

**Comment by annaengstrom** [comment]
Define MVP: 
- QC parameters for pipeline
- Understandable error messages
- Variant filtering strategy / options
etc

https://github.com/Clinical-Genomics/BALSAMIC

**Comment by moonso** [comment]
Hi, I'm moving this to the project repo. I think the issue is to vague to be here.
It now lives here https://github.com/Clinical-Genomics/cgp-cancer-in-weekly-production/issues/6
