### ISSUE TITLE
Deliver BAM files as CRAM for WGS runs

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#303]
**Is your feature request related to a problem? Please describe.**
BAM output files take too much storage space and it is a recurring storage issue on Hasta.

**Describe the solution you'd like**
Convert BAM files to CRAM.

**Describe alternatives you've considered**
None.

**Additional context**
CRAM index files should also be readily available

**Expected output for the feature**
`tumor.merged.bam` to `tumor.merged.cram`. And all `bai` files to `crai`

**Current BALSAMIC version**
`4.2.4`

**Comment by Mropat** [comment]
Can we achieve this by adding BAMtoCRAM step in senteion_dedup rule?

**Comment by hassanfa** [comment]
Yes. Ideally we should have a single bam2cram rule to take care of any bam file.

**Comment by hassanfa** [comment]
@Mropat could you update progress on this some time this week?

I'd like to get a list of things that needs to be done so we can prioritize and inspect the impact.

**Comment by hassanfa** [comment]
This is actually done in BALSAMIC 7.x.x
