### ISSUE TITLE
Variant call workflow start from BAM/CRAM

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#305]
**Is your feature request related to a problem? Please describe.**
Fastq data availability might not be possible all the time, and some commercial data sets are in BAM format. Aligning to genome can also be a lengthy process. Starting from preprocessed BAM file can save computation time.

**Describe the solution you'd like**
`config case --tumor` should accept both fastq.gz and .bam files.

**Describe alternatives you've considered**
None.

**Additional context**
Should we make a new workflow?
Logic in BALSAMIC cli or Snakemake Workflow?

**Expected output for the feature**
A troublefree workflow!

**Current BALSAMIC version**
`4.2.4`

**Comment by hassanfa** [comment]
@Mropat status update on this as well with a wishlist and/or Todo list of what needs to be done.

**Comment by hassanfa** [comment]
Considerations:

1. Do we need to match BAM File with its reference genomes?
2. If we cannot match in step 1, can we ceate ubam from bam and then align back to genome?
3. How should we treat the BAM file? Markdup? Sort?


Complexity vs gain is too much. We should probably close this.

**Comment by ashwini06** [comment]
Closing it, as there is no internal cg requests or priority for this issue
