### ISSUE TITLE
Time LIMIT failure for cases with high amount sequencing reads

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#314]
**BALSAMIC version**
`balsamic --version`
balsamic, version 4.2.4

**References and other implementations**
Several cases with high amount of sequencing reads fails on InDelRealigner: 
`Slurm Job_id=414251 Name=BALSAMIC.honestcollie.IndelRealigner.75.sh Failed, Run time 07:00:11, TIMEOUT, ExitCode 0`

Below are the cases and the amount of reads for each case:

exoticpiglet - 155 M r-p
honestcollie - 170 M r-p
pickedelk - 125 M r-p
selectewe - 106 M r-p
validcrane - 91 M r-p
valuedjaguar - 75 M r-p
rightjaguar - 85 M r-p
epicstag - 180 M r-p
moredoe (T/N) - 62 and 50 M r-p 
mightytahr (T/N) - 55 and 72 M r-p

**Comment by keyvanelhami** [comment]
@hassanfa I have now updated all samples analyzed this week and failed on indel realigner

**Comment by hassanfa** [comment]
A quick fix would be to increase indelrealigner time in `/home/proj/production/cancer/BALSAMIC/BALSAMIC/config/cluster.json` it is line 18, and it is 07:00:00 hours right now if they are urgent:

```
    "IndelRealigner": {
        "time": "07:00:00",
        "n": 10
    },
```

Change the time value to "10:00:00", make sure it is quoted and follows the same format. If it works, then we push "10:00:00" hour to master branch.
