### ISSUE TITLE
Refactor config case

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/BALSAMIC#323]
Some of the functions in balsamic are large and do multiple things. 
A refactoring of those could be beneficial:
--Easier to test
--Easier to explain in documentation on a step-by-step basis
--More robust when adding new features later

**Describe the solution you'd like**
Break up the code into smaller chunks
Implement classes where beneficial

**Describe alternatives you've considered**
An alternative could be to leave it as is, as the works fine at the moment

**Expected output for the feature**
The functionality and interface of the package should remain the same and integrate well with CG

**Comment by hassanfa** [comment]
Let's contain this for `balsamic config case` for now.

The following needs to be refactored:
- [ ] Move all functions in `BALSAMIC/commands/config/case.py`  to `utils/cli.py`
   - [ ] Docstring update
   - [ ] Unit tests

- [ ] Refactor `def case_config`
   - [ ] A builder for various config files that we have
   - [ ] New functions/Classes should be placed in `utils/cli.py`

**Comment by hassanfa** [comment]
We should remember to make it all relevant along side `cg`. All improvement should make it more simple to create a config for an analysis in `cg`

**Comment by Mropat** [comment]
Additional feedback from @moonso:

Regarding config files:
-- Use constants file to hold contents of config/schema files
-- Alternatively, look into marshmallow package to handle json

Regarding tests:
-- Look into cg/crunchy for inspiration on testing classes

Other
-- Use Path library for path handling
-- Use master function to catch exceptions (instead of doing it in each individual function)

**Comment by moonso** [comment]
Just want to add that I would suggest handling exceptions in the CLI code. So classes and functions can just raise exceptions and then catch in CLI and decide what to do with the information

**Comment by hassanfa** [comment]
Good point. Raise early and as close to the source as possible. Always throw early, catch laters.

I suggest to follow the following format: 
http://google.github.io/styleguide/pyguide.html#244-decision
