### ISSUE TITLE
Include detailed Bioinfo tool descriptions, links and citations in BALSAMIC report

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/BALSAMIC#339]
**Is your feature request related to a problem? Please describe.**
The enjoyment of reading the BALSAMIC reports can be improved with inclusion version, detailed descriptions, and citation links for each software included in the analysis

**Describe the solution you'd like**
Create a Pydantic model which would hold this information and can be appended upon delivery

**Additional context**
Currently, we report the software and version in config.json, but we would like to have a more detailed software/package info when delivering results

**Comment by hassanfa** [comment]
- [ ] Add all tools in https://balsamic.readthedocs.io/en/latest/bioinfo_softwares.html to https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/utils/models.py#L289
- [ ] Include description of the bioinfo tools here: https://balsamic.readthedocs.io/en/latest/bioinfo_softwares.html under a description tag.
- [ ] if we use multiple version of a software, add all of them: https://balsamic.readthedocs.io/en/latest/bioinfo_softwares.html

**Comment by ivadym** [comment]
Balsamic reports are not longer generated during Balsamic workflow and the documentation has been updated and restructured. Closing as this seems outdated.
