### ISSUE TITLE
Workflow solution for QC-only runs

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/BALSAMIC#365]
**Is your feature request related to a problem? Please describe.**

Some cases require analysis using only QC step of BALSAMIC workflow. 
In order to support the automation of analysis, storage and delivery of those cases, it would be beneficial to define a qc-only workflow.

**Describe the solution you'd like**
Keep track of analysis type already during config generation
    State that the analysis is QC-only during config generation, and save the value under "analysis_type".
    Build  workflow including only the tools that will be used (QC)

**Expected output for the feature**
DAG graph and Delivery report/status only take into account the relevant tools and outputs. 
Config file config.json contains tag "qc" to be used for CG decision-making
Restrictions such as having one tumor and at most one normal sample as input not to apply for QC cases

**Current BALSAMIC version**
`balsamic --version 4.5.0`

**Comment by hassanfa** [comment]
There is already a QC-only workflow: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/workflows/Alignment 

Do you, by any chance, mean QC only config?

**Comment by hassanfa** [comment]
This will create multiple entry point to the workflow, and add new logic. Closing for now, but lets consider it and find out if we will need it in future.
