### ISSUE TITLE
[ Failed Analysis ] BALSAMIC.meetcod.strelka_tumor_normal

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#367]
**Case or sample information**
Internal sample id or case id: meetcod
Amount read-pairs: normal 145M tumor 112M
Sequence type (WES, TGA, WGS): TGA gmcksolid

**Error message**
> Slurm Job_id=520270 Name=BALSAMIC.meetcod.strelka_tumor_normal.41.sh Failed, Run time 06:00:22, TIMEOUT, ExitCode 0

**Link to the error message**
`/home/proj/production/cancer/cases/meetcod/logs/BALSAMIC.meetcod.strelka_tumor_normal.41.sh_520270.err`

**Reason for failure**
Time out.

**If workflow, which rules**
Variant calling paired analysis. Strelka tumor-normal

**Version (please complete the following information):**
`4.3.0`

**Additional context**
Possible solution: increase analysis time to 12hours.

**Comment by ashwini06** [comment]
Rerun analysis failed again 

`Slurm Job_id=523990 Name=BALSAMIC.meetcod.strelka_tumor_normal.41.sh Failed, Run time 12:00:06, TIMEOUT, ExitCode 0`

```slurmstepd: error: *** JOB 523990 ON compute-0-0 CANCELLED AT 2020-07-23T02:00:26 DUE TO TIME LIMIT ***```

**Comment by hassanfa** [comment]
Increased time to 18hours and 18 threads, up from 12 hours and 12 threads. This is worrying me. Either Strelka fails to use multithreading options, or there are tough to call regions.

@ashwini06 Please restart the once again. Thanks!

**Comment by ashwini06** [comment]
Thanks @hassanfa . Restarted the analysis now.

**Comment by ashwini06** [comment]
Failed again

`Slurm Job_id=525656 Name=BALSAMIC.meetcod.strelka_tumor_normal.41.sh Failed, Run time 18:00:28, TIMEOUT, ExitCode 0`

`slurmstepd: error: *** JOB 525656 ON compute-0-4 CANCELLED AT 2020-07-24T06:42:37 DUE TO TIME LIMIT ***`

**Comment by hassanfa** [comment]
addressed in in PR
