### ISSUE TITLE
[ Failed Analysis ]BALSAMIC.daringmidge.mutect2_tumor_normal

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#370]
**Case or sample information**
Internal sample id or case id: daringmidge
Amount read-pairs: tumor 93 Mreads; normal 124 Mreads
Sequence type (WES, TGA, WGS): TGA GMCKsolid

**Error message**
`Slurm Job_id=521003 Name=BALSAMIC.daringmidge.mutect2_tumor_normal.120.sh Failed, Run time 14:00:13, TIMEOUT, ExitCode 0`

**Link to the error message**
`/home/proj/production/cancer/cases/daringmidge/logs/BALSAMIC.daringmidge.mutect2_tumor_normal.120.sh_521003.err`

**Reason for failure**
`slurmstepd: error: *** JOB 521003 ON compute-0-9 CANCELLED AT 2020-07-21T15:53:12 DUE TO TIME LIMIT ***`

**If workflow, which rules**
`snakemake_rules/variant_calling/somatic_tumor_normal.rule`

**Version (please complete the following information):** 
`4.3.0`

**Additional context**
Possible Solution:
According to err log, mutect2 ran for 14 hours and exited due to time limit
Rerun by increasing compute time for daringmidge tumor normal to 15 hours instead

**Comment by hassanfa** [comment]
Fixed in #440
