### ISSUE TITLE
Filter variants through COSMIC and cBioPortal

### ISSUE THREAD

**Issue by EmmTha** [Clinical-Genomics/BALSAMIC#382]
Balsamic accessed 2020-08-01

CURRENT SITUATION: Cannot filter using cosmic or cBioportal data

FUTURE DEVELOPMENT?: 
It would be nice to be able to filter using “cosmic”
In the future, would it be possible to get a link to cbioportal.org data? They have large modern data sets that are a bit more reliable than cosmic.

**Comment by hassanfa** [comment]
Thank you for reporting this.

Cbioportal addition to BALSAMIC is under development. Next major release will have this feature available.

In regards to how to filter based on cosmic or cbioportal, it is more of a Scout issue. But ill move it to Scout when cbio data is in place.

**Comment by dnil** [comment]
Just to note it somewhere, CIViC can link (https://docs.civicdb.org/en/latest/api/linking.html) on Allele Registry Ids; e.g.
http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_caid?caid=CA000049
That will just solve itself when annotating with it, but if you have to choose between native CIViC ids and AR..

**Comment by hassanfa** [comment]
Thanks for the heads up Daniel.

**Comment by khurrammaqbool** [comment]
This is an ongoing work described in the project below,
https://github.com/Clinical-Genomics/project-planning/issues/292

**Comment by pbiology** [comment]
As I understand. cBioPortal filtering has already been implemented.
As for COSMIC. We have generated a new feature issue for adding COSMIC profiles, #1113 which is considered for future implementation.
