### ISSUE TITLE
Error resolving wildcard in housekeeper report

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/BALSAMIC#384]
**Describe the bug**
Report generation script cannot resolve wildcard for SNV.somatic.case_id.vardict.filtered.pass.vcf file

![image](https://user-images.githubusercontent.com/35531751/89799029-43756600-db2d-11ea-9bbf-206f97871a21.png)

This is the only file where the wildcard resolution fails. Other wildcards in vep_somatic rule are resolved successfully

**To Reproduce**
Generate report for a tgs analysis and examine outputs of vep_somatic rule

**Version (please complete the following information):**
`balsamic 4.5.0 `

**Comment by hassanfa** [comment]
Was the analysis directory wiped before running this? It might be that files exist, and wildcard resolves to old files. If not, then this is a bug.

**Comment by Mropat** [comment]
No the old analysis was not wiped. Will test this and update

**Comment by hassanfa** [comment]
This was fixed #387
