### ISSUE TITLE
Housekeeper report script fails to detect cram index

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/BALSAMIC#385]
**Describe the bug**
Housekeeper report script fails to detect cram index

**To Reproduce**
Generate housekeeper report for a case and examine outputs of mergeBam_tumor or mergeBam_normal rule

**Expected behavior**
cram index included in report

**Version (please complete the following information):**
`balsamic 4.5.0`

**Comment by hassanfa** [comment]
Which cram index files are missing? They are extracted through this: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/utils/cli.py#L294

Is cram file even created?

**Comment by Mropat** [comment]
Ah that explains it.
The cram file is generated and can be found in report, but not the crai index. 
Because we are looking for a cram.cai which it doesn't find 🤦‍♀️

**Comment by hassanfa** [comment]
fixed in #390
