### ISSUE TITLE
Feature request: Goals to reach with housekeeper report

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/BALSAMIC#386]
The balsamic deliverables report currently contains the data which is to be stored in Housekeeper and subsequently delivered to customers

**The files and tags defined in the report are used in following ways:**
I. Long-term storage and audit (self-explanatory)
II. Validation: Each entry in the report is mandatory to upload to HK. All files should exist in order to commit bundle
III. Delivery to customer inbox: cg deliver command should be able to retrieve file names by tag and copy all necessary ones to customer folder
IV. Delivery to scout (not yet implemented): we want to fetch files from housekeeper by tag and upload to scout.

**Feature wishlist:**
**II. Validation**
Establish a way to ensure that report will always contain all files defined in delivery rules. Ideally, report generation should fail unless everything is included. If for some reason jobs are not planned correctly or aren't finished, but exited with status OK in SLURM anyhow, this should fail the report creation process. 
If some core files aren't accessible to BALSAMIC workflow (as it could happen with reference path in singularity), we should not be able to create analysis_finish file, or generate an empty/incomplete report.
When calling balsamic report deliver manually, we will see log output notifying us that rules are missing. However, if this process is automated with cg, cg will not be aware of the log output, or have checks in place to know that anything went wrong. Which is why it would be good to have those safeguards already on balsamic level.

**III. Delivery to customer inbox**
As I understand this, the customer is generally interested in either of the following:
QC bundle: fastq, bam/cram, multiqc
Analysis bundle: [QC bundle], variant calling, plots
Analysis bundle+: [analysis bundle], cnv

Ideally for automation of this process though CG, we would want those files labeled with unique, discriminatory delivery tags:
QC delivery : inbox-qc
Analysis bundle: inbox-analysis
Analysis bundle+: inbox-cnv

Additionally we perhaps would like to re-construct the folder structure of the files we initially upload to HK, as we copy them to customer inbox. For this, I suggest we add tags indicating which folder to create in order to store them. Suggestions:
dir-bam, dir-fastq, dir-vep, dir-cnv, dir-qc

**IV. Delivery to SCOUT**
Similarly, it is crucial that we first upload the files to housekeeper before linking them to scout! This is important, because if the balsamic directories are to be cleaned in the future, the scout config will be pointing at something that doesn't exist anymore!
Additionally, I would also like to see unique discriminatory tags for each file to be uploaded to scout. This way we can automate report generation and upload with cg in the future. Suggestions:

scout-report
scout-tumor-cram
scout-normal-cram
scout-snv
scout-sv

This way we can retrieve the exact files from HK and spare the production folk the squinting and typing hopefully!

**Additional note:**
I also realized that some samples will be analyzed with both mip and balsamic. Because of that, i think it would be even beneficial to prepend the delivery tags with "balsamic-" to avoid mix-ups

This of course if only a suggestion, would be great to start a discussion on this topic

**Current BALSAMIC version**
`balsamic 4.5.0`

**Comment by hassanfa** [comment]
Very nice summary and comments of the feature. 👍

For validation it is coupled deeply with Snakemake to report output files. Although I think this might be unnecessary. SLURM will not exit with 0 if files are missing, this is due to Snakemake making sure files are created.

Delivery specific tags for customer is a good idea. It is similar to the UDF bundle in goals. I generally agree with all of the tags, except tags like inbox-cnv for being too specific. We should try to avoid these tags as much as possible.

+1 on delivery directories. We could add a simple autogenerated readme for each delivery directory. Additionally, we could also store the file. We could use report functionality of Snakemake.

Scout tags should be easy. We can append these to housekeeper tags in rules. 👍

**Comment by hassanfa** [comment]
Most of these are in place. We are missing wgs bam/cram part.

I think it is done.

Delivery and store are cg and housekeeper issue. And i think this is done.

**Comment by moonso** [comment]
Let's reopen this as @hassanfa and me have agreed on the fact that we should use unique tags that explains where each file should be used within CG, if it is mandatory etc. CG will provide a reference where the available tags are specified, which ones that are mandatory, which ones are going to be be delivered etc.

The mandatory tags should be produced by talking between pipeline and CG infrastructure.

The available tags should exist as a version controlled json files somewhere, either in CG but preferably in another repository.

**Note that the tags will not necessarily correspond to the given tags above**

**Comment by hassanfa** [comment]
Closing this with better description here: https://github.com/Clinical-Genomics/BALSAMIC/issues/487
