### ISSUE TITLE
Update installation document

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#391]
Installation document is not up to date and it is causing problems. It should reflect the most recent version of balsamic

**Comment by ashwini06** [comment]
Following are few deviations I noticed from the current documentation

Current branch version tags are prefixed with 'v' 

```
./install.sh -s D -v v4.5.0 -p conda_prefix_path
```

Also while generating reference need to specify snakemake --core option

```
balsamic run reference --configfile BALSAMIC_reference/config.json --run-analysis  --snakemake-opt "--cores 8" ```

**Comment by hassanfa** [comment]
Thanks for the feedback. i'll add those.
