### ISSUE TITLE
Create QC model for approving an analysis

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#394]
The purpose is to create a data model of QC values to be able to know whether an analysis is of good quality to be delivered:

Create a QC model :
- [x] Select QC parameters to include no matter sample type. 
- [x] As a dictionary in https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/utils/constants.py
- [x] Consider ranges of values with regards to sequence depth. E.g. A higher sequence depth for the same panel will end up with higher duplication rate

Version controlling this QC model will be tied to version of BALSAMIC.

**Comment by hassanfa** [comment]
Relevant publications: TBD

Relevant internal documents from AM doc: TBD

**Comment by keyvanelhami** [comment]
Below QC parameters will be used, no matter sample type. This will be in json format (nested dictionary) as the VARDICT_SETTINGS module [here](https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/utils/constants.py). For each QC parameters, a key with the bait-set will be added and the value for that key will be the threshold. 
- Coverage
- Fold-80

**Comment by hassanfa** [comment]
This is done in #401
