### ISSUE TITLE
Step by step guide to setup BALSAMIC and up and running.

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#400]
Currently online doc: https://balsamic.readthedocs.io/en/latest/ does not support step by step guide to setup BALSAMIC. To make it easier to deploy and prepare required files, documentation needs to be as transparent as possible.

Items to consider to mentioned in Docs:
1. create conda env
1. get correct version
1. get correct container
1. prepare reference dataset

All 4 points above are already in the docs, it needs a bit of refactoring and beautifying.

**Comment by ivadym** [comment]
Closing. Documentation improved in this project: https://github.com/Clinical-Genomics/project-planning/issues/158
