### ISSUE TITLE
Allocate a dynamic amount of resources depending on analysis type

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#414]
**Is your feature request related to a problem? Please describe.**
Depending on the application type, analysis type, and quality type there will be need for allocate a dynamic amount of resources. Scatter-gather solution for variant callers based on chromosome is not efficient, resources need to be allocated based on read count, and region size.

**Describe the solution you'd like**
Allocate dynamic amount of resources for SLURM jobs on need basis rather than one for all. Define a small task resource type and then scale up.

**Describe alternatives you've considered**
Re-design workflow, but it is a major undertaking and won't be an easy task. It won't scale up either.

**Additional context**
All GATK applications are allocated improper amount of resources.

**Expected output for the feature**
Reduced workflow runtime, and more efficient use of resources.

**Current BALSAMIC version**
`5.1.0`

**Comment by pbiology** [comment]
Refinement 2022-12-13:
- Still need to add memory allocations for a lot of rules
- Analysis specific resources

**Comment by pbiology** [comment]
So can we consider this blocked by #1139 ?

**Comment by ivadym** [comment]
I think they are independent  of each other. Here we need to add a new layer of complexity to the `config.json` (`analysis_type` on top of the rule names for example ): https://github.com/Clinical-Genomics/BALSAMIC/blob/0263a983156fae468155be9a189d4c4a0502aacd/BALSAMIC/config/cluster.json#L9-L13

While in https://github.com/Clinical-Genomics/BALSAMIC/issues/1139 is just about adding a new key with memory, ...

**Comment by ivadym** [comment]
Added to user story: https://github.com/Clinical-Genomics/BALSAMIC/issues/1312
