### ISSUE TITLE
Failed VarDict och Mutect2 on Java memory

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#427]
**Case or sample information**
Internal sample id or case id: wittyworm and soundmoth
Amount read-pairs: 83 (wittyworm), 81 (soundmoth)
Sequence type (WES, TGA, WGS): TGA

**Error message**
`java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code`

**Link to the error message**
`wittyworm/logs/BALSAMIC.wittyworm.vardict_tumor_only.94.sh_621551.err`

**Comment by hassanfa** [comment]
Solution: Increase memory for `vardict-java` from `8G` to `32G`.

**Comment by hassanfa** [comment]
Fixed in #440
