### ISSUE TITLE
Germline variant uploaded to Scout for paired analysis

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#435]
**Is your feature request related to a problem? Please describe.**
For case `guidedboxer` which was analyzed as paired analysis , the normal sample was a FF sample from tumor biopsy, and the tumor sample was a FFPE sample. The idea from the clinician was to filter for the FFPE artifacts. 

However, below TP53 variant was uploaded in Scout and shouldn't have been uploaded since the reported VAF for germline and somatic were very similar. This variantwas tagged as germline in the vcf but it was also put as "Pass"

```
17	7579319	.	G	A	326	PASS	STATUS=Germline;SAMPLE=guidedboxer;TYPE=SNV;DP=923;VD=440;AF=0.4767;SHIFT3=0;MSI=1;MSILEN=1;SSF=0.29012;SOR=1.05356;LSEQ=CAGGGCAACTGACCGTGCAA;RSEQ=TCACAGACTTGGCTGTCCCA	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	0/1:923:440:62,378:52,430:482,440:0.4767:2,2:32.7:1:36.3:1:0.13399:1.36:60:145.667:0.4755:0.0108:1.1	0/1:1212:562:165,397:151,496:647,562:0.4637:2,2:33.9:1:35.7:1:0.01825:1.36:60:61.444:0.4612:0.0091:1.1
```
![image003](https://user-images.githubusercontent.com/26735714/95565465-8914b900-0a20-11eb-935b-5f988a2e65db.jpg)

**Current BALSAMIC version**
`balsamic v5.1.0`

**Comment by hassanfa** [comment]
This is fixed in the tumor normal and tumor only filters.
