### ISSUE TITLE
Allocate memory for SGE/UGE/QSUB and SLURM 

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#447]
In `cluster.json` no memory allocation is assigned, and both slurm&qsub can handle memory reservation. This is important for Mutect2 and Haplotypecaller.

**Comment by hassanfa** [comment]
Only applicable for Java applications where they need `-Xmx`

**Comment by ivadym** [comment]
@khurrammaqbool 

Closing. Overlaps with https://github.com/Clinical-Genomics/BALSAMIC/issues/414.
