### ISSUE TITLE
prefix for tmp directory

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#449]
Currently tmp directory is in `<case_name>/analysis/tmp`, but it would be useful prefix in runtime. `balsamic run --tmp-dir PREFIX_TMPDIR analysis`

**Comment by hassanfa** [comment]
I'll work on this.

**Comment by pbiology** [comment]
Refinement 2022-12-13:
- Would require quite a lot of refactoring
