### ISSUE TITLE
cleansquid

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/BALSAMIC#457]
**Case or sample information**
Internal sample id or case id: cleansquid
Amount read-pairs: 91
Sequence type (WES, TGA, WGS): EXOKTTR040 

**Error message**
Copy either the error message from the e-mail or copy **only the relevant** line(s) in the error log showing the error message(s). Please do not paste the whole error text.
BALSAMIC.cleansquid.mutect2_tumor_normal.124.sh
BALSAMIC.cleansquid.vardict_tumor_normal.129.sh

**Link to the error message**
Copy the path for the error file in Hasta which includes the error message(s). In order to get path to the file, run the following command on Hasta: `ejobinfoprint jobid` (replace job id with actual job id).
/home/proj/production/cancer/cases/cleansquid/logs/BALSAMIC.cleansquid.vardict_tumor_normal.129.sh_640235.err
/home/proj/production/cancer/cases/cleansquid/logs/BALSAMIC.cleansquid.mutect2_tumor_normal.124.sh_640322.err

**Reason for failure**
Provide any theories regarding why the error message arises.
Time-out

**If workflow, which rules**
If possible, and using the Snakemake workflows, the name of the affected rules and workflows.

**Version (please complete the following information):**
`balsamic --version` output
5.1.0

**Additional context**
Add any other context about the problem here. For e.g. amount sequencing reads or other parameters that are of interest.

**Comment by hassanfa** [comment]
I'll look into vardict part, but mutect2 needs to be disabled for wes cases through cg.

**Comment by hassanfa** [comment]
mutect2 is now disabled for all WES runs. This shouldn't be an issue for future cases.
