### ISSUE TITLE
upwardhawk

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/BALSAMIC#458]
**Case or sample information**
Internal sample id or case id: upwardhawk
Amount read-pairs: 112 and 79
Sequence type (WES, TGA, WGS):EXOKTTR060

**Error message**
Copy either the error message from the e-mail or copy **only the relevant** line(s) in the error log showing the error message(s). Please do not paste the whole error text.
BALSAMIC.upwardhawk.mutect2_tumor_normal.103.sh

**Link to the error message**
Copy the path for the error file in Hasta which includes the error message(s). In order to get path to the file, run the following command on Hasta: `ejobinfoprint jobid` (replace job id with actual job id).
/home/proj/production/cancer/cases/upwardhawk/logs/BALSAMIC.upwardhawk.mutect2_tumor_normal.103.sh_664337.err

**Reason for failure**
Provide any theories regarding why the error message arises.
Time-out

**If workflow, which rules**
If possible, and using the Snakemake workflows, the name of the affected rules and workflows.

**Version (please complete the following information):**
`balsamic --version` output
5.1.0

**Additional context**
Add any other context about the problem here. For e.g. amount sequencing reads or other parameters that are of interest.

**Comment by hassanfa** [comment]
Similar to #461, closing it. This needs cg integration.
