### ISSUE TITLE
neatviper

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/BALSAMIC#459]
**Case or sample information**
Internal sample id or case id: (only anonymized ids are allowed)
Amount read-pairs:
Sequence type (WES, TGA, WGS):

**Error message**
Copy either the error message from the e-mail or copy **only the relevant** line(s) in the error log showing the error message(s). Please do not paste the whole error text.
Error in rule BaseRecalibrator:
    jobid: 0
BALSAMIC.neatviper.BaseRecalibrator.99.sh

**Link to the error message**
Copy the path for the error file in Hasta which includes the error message(s). In order to get path to the file, run the following command on Hasta: `ejobinfoprint jobid` (replace job id with actual job id).
/home/proj/production/cancer/cases/neatviper/logs/BALSAMIC.neatviper.BaseRecalibrator.99.sh_676294.err

**Reason for failure**
Provide any theories regarding why the error message arises.

**If workflow, which rules**
If possible, and using the Snakemake workflows, the name of the affected rules and workflows.

**Version (please complete the following information):**
`balsamic --version` output

**Additional context**
Add any other context about the problem here. For e.g. amount sequencing reads or other parameters that are of interest.

**Comment by hassanfa** [comment]
This job seems like to be aborted:
```
INFO  18:41:51,624 ProgressMeter -     21:34100323   3.25031763E8    44.5 m       8.0 s       90.8%    49.0 m       4.5 m 
INFO  18:42:21,631 ProgressMeter -     21:47987512   3.28332026E8    45.0 m       8.0 s       91.2%    49.3 m       4.3 m 
INFO  18:42:51,641 ProgressMeter -     22:24622773   3.31604496E8    45.5 m       8.0 s       92.0%    49.4 m       3.9 m 
bash: line 1: 176119 Aborted               
```

This doesn't seem like BALSAMIC error. Closing.
