### ISSUE TITLE
immunefinch

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/BALSAMIC#460]
**Case or sample information**
Internal sample id or case id: immune finch
Amount read-pairs: 70M and 70M
Sequence type (WES, TGA, WGS): EXOKTTR040 

**Error message**
Copy either the error message from the e-mail or copy **only the relevant** line(s) in the error log showing the error message(s). Please do not paste the whole error text.
BALSAMIC.immunefinch.mutect2_tumor_normal.106.sh

**Link to the error message**
Copy the path for the error file in Hasta which includes the error message(s). In order to get path to the file, run the following command on Hasta: `ejobinfoprint jobid` (replace job id with actual job id).
immunefinch/logs/BALSAMIC.immunefinch.mutect2_tumor_normal.106.sh_677282.err

**Reason for failure**
Provide any theories regarding why the error message arises.
Time-out

**If workflow, which rules**
If possible, and using the Snakemake workflows, the name of the affected rules and workflows.

**Version (please complete the following information):**
`balsamic --version` output

**Additional context**
Add any other context about the problem here. For e.g. amount sequencing reads or other parameters that are of interest.

**Comment by hassanfa** [comment]
Again, mutect2 and cg has to tell balsamic to disable it. https://github.com/Clinical-Genomics/cg/issues/785
