### ISSUE TITLE
realboa

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/BALSAMIC#461]
**Case or sample information**
Internal sample id or case id: realboa
Amount read-pairs:227M and 70M
Sequence type (WES, TGA, WGS):

**Error message**
Copy either the error message from the e-mail or copy **only the relevant** line(s) in the error log showing the error message(s). Please do not paste the whole error text.
BALSAMIC.realboa.mutect2_tumor_normal.114.sh
BALSAMIC.realboa.mutect2_tumor_normal.121.sh

**Link to the error message**
Copy the path for the error file in Hasta which includes the error message(s). In order to get path to the file, run the following command on Hasta: `ejobinfoprint jobid` (replace job id with actual job id).
realboa/logs/BALSAMIC.realboa.mutect2_tumor_normal.114.sh_677427.err
realboa/logs/BALSAMIC.realboa.mutect2_tumor_normal.121.sh_677481.err

**Reason for failure**
Provide any theories regarding why the error message arises.
Time-out

**If workflow, which rules**
If possible, and using the Snakemake workflows, the name of the affected rules and workflows.

**Version (please complete the following information):**
`balsamic --version` output

**Additional context**
Add any other context about the problem here. For e.g. amount sequencing reads or other parameters that are of interest.

**Comment by hassanfa** [comment]
This is whole exome right? We need to disable mutect2 for whole exome through cg. There is an open issue in CG for it: https://github.com/Clinical-Genomics/cg/issues/785

I am closing this for now.
