### ISSUE TITLE
Yaml file for Trailblazer

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/BALSAMIC#463]
**Is your feature request related to a problem? Please describe.**
In order to track BALSAMIC cases with trailblazer, we need a sacct file in a unified format between all pipelines

**Describe the solution you'd like**
Balsamic workflow should create a yaml file in pre-defined location (preferably somewhere obvious like cancer/cases/bosssponge/slurm_jobs.yaml). The path to the file should be declared either in case config or in cg constants if it can be generalized. The file should be overwritten if the run is restarted from scratch, or  updated if re-started at intermediate step

**Expected output for the feature**

Format of yaml file with jobs:
```
---
justhusky:
  - '686841'
  - '686842'
  - '686843'
  - '686844'
  - '686845'
  - '686846'
  - '686847'
  - '686848'
  - '686849'
  - '686850'
  - '686851'
  - '686852'
```

**Current BALSAMIC version**
`balsamic --version 5.1.0`

**Comment by Mropat** [comment]
I can do this myself then

**Comment by hassanfa** [comment]
I already added to my calendar to work on it, but if you want to dive in, you are very welcome.

**Comment by hassanfa** [comment]
Let me know if you're going to work on it, so I can tell what needs to be done and where.

**Comment by Mropat** [comment]
I am blocked by this currently, so sure why not!
Go ahead and give me the details!

**Comment by hassanfa** [comment]
Obvious stuff:
1. `sacct` file name&path generated here: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/commands/run/scheduler.py#L264
2. job ids are written here: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/commands/run/scheduler.py#L297  using https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/commands/run/scheduler.py#L136

To do is to:
I want to have it in `<case_id>/logs` But currently at each re-run a new `sacct` file is generated in the new `logs` dir. Example:
![image](https://user-images.githubusercontent.com/1086877/96603323-34145500-12f4-11eb-881a-877bc2dea51b.png)

First step, is to have a master logs dir: `<case_id>/logs` and have `logs.0`, `logs.1` there. Which is handled via https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/commands/run/analysis.py#L130-L137  .  `scripts` should have the same behavior.

Second step, is to write new `sacct` file to `<case_id>/logs/<case_id>.yaml`

No major new functionality is need beyond adding a main path for `logs` and `scripts`.

`scheduler.py` is an stand alone script and please keep it that way (i.e. there should be no coupling between `scheduler.py` and `BALSAMIC` beyond what already exists).

**Comment by hassanfa** [comment]
Also, on event on rerun, previous sacct file should move to a new file.

Alternative solution that I was going to explore is to have `sacct` file in `<case_id>/logs/logs.0/<case_id>.yaml` and `<case_id>/logs/logs.1/<case_id>.yaml` and softlink latest one to ``<case_id>/logs/<case_id>.yaml`. (which I prefer to do it this way).

**Comment by emmser** [comment]
Can this sacct-file be used to show which programs that have failed, cancelled or finished? Can the names of the jobs be written to the file? I find MIP's sacct-file very useful when working with failed cases and would be happy for something similar in Balsamic.

**Comment by hassanfa** [comment]
It is for trailblazer, which will query these jobs ids for their status. Maria and I were talking about it moments ago, and `trailblazer scan` will work in a similar way.
