### ISSUE TITLE
Docs: Description of output vcf

### ISSUE THREAD

**Issue by alvaralmstedt** [Clinical-Genomics/BALSAMIC#467]
I would like to have documented which vcf files have gone though which filters and software. Also, which vcfs that are recommended to give to downstream variant analysis software for different types of samples. For example: panel/WES/WGS & germline/TN/TO. Just a little table or something :)

**Comment by hassanfa** [comment]
This is also related to deliverable files described here: https://github.com/Clinical-Genomics/BALSAMIC/issues/386

A general delivery file that describe the purpose of what is final result.

**Comment by ashwini06** [comment]
This document adds the details of VCF file and included filters. The https://balsamic.readthedocs.io/en/latest/balsamic_filters.html#table-1 serves the general description of files delivered to customer. Changes from BALSAMIC >v9.0
