### ISSUE TITLE
BUG: IGNORE creation of .sacct file in local mode

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#479]
**Issue:**

While running BALSAMIC in `local` mode, do not create '.sacct' file

**Screenshot**
<img width="1297" alt="Screenshot 2020-11-02 at 10 53 55" src="https://user-images.githubusercontent.com/6302819/97854547-e6d3b280-1cf9-11eb-8c21-8953cf5741a7.png">

**Fix**
https://github.com/Clinical-Genomics/BALSAMIC/blob/bb84ea08401b3ad49dd8e6a00903754644ace69e/BALSAMIC/commands/run/analysis.py#L197

**Comment by hassanfa** [comment]
done in #497
