### ISSUE TITLE
VarDict's and Sentieon's output SV/SNV mix. They should be split up

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#485]
**Describe the bug**
VarDict and Sentieon TNScope are caling SVs _with_ SNVs/INDELs. This is causing some trouble in uploading to Scout, and possibly it can be an issue during annotation. 

**To Reproduce**
Any workflow run since `4.0.0`

**Expected behavior**
SNV/INDEL and SVs should be in separate files.

**If workflow, which rules**
All VarDict and Sentieon TNScope rules

**Screenshots**
N/A

**Version (please complete the following information):**
`4.x.x`, `5.x.x` and `6.0.1`

**Additional context**
None

**Comment by ashwini06** [comment]
@hassanfa : 
Solution: Can we include this option `--disable_detector= 'sv’ ` variant_settings in params. This should disable calling 'sv' in sentieon TNscope variant calling?

https://github.com/Clinical-Genomics/BALSAMIC/blob/3edac37c75736e5734708c3e97d8d5fe6ba824d4/BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule#L122

**Comment by hassanfa** [comment]
That's a good solution, but we will miss SVs called from sentieon.

Manta developers will stop developing it further, and until then we need to have a second SVcaller.

We should take the steeper road of splitting SVs from VarDict and Sentieon, and then merge them with CNVkit and Mantas output.

Implementting it using  svdb is a good solution.

**Comment by ashwini06** [comment]
So to say, prior to vep annotation there should be an extra rule after TNscope/vardict variant calling which could filter the vcf files based on type (SNV/INDELS or SVs) (eg: bcftools filter -i "TYPE="snv"). The resultant filtered SV file(s) needs to be merged with CNVkit and manta vcf files using `svdb merge`.

**Comment by hassanfa** [comment]
That is correct. This way we will have a single snv, indel, and SV file.

**Comment by ashwini06** [comment]
Cool.. I will look into this implementation then :)

**Comment by hassanfa** [comment]
WGS done and finished in #540
