### ISSUE TITLE
Failed analysis on BaseRecalibrator, VarDict and Manta for ticket 821450

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#493]
Following cases failed on Vardict: 

**neatviper** (normal 180 M r-p, tumor 110 M r-p)
**goodbobcat** (normal: 190 Mr-p, tumor 103 Mr-p)
**cleansquid** (normal 75 Mr-p, utmor 90 M r-p)
**comicmole** (normal 120 M r-p, tumor 70 Mr-p)
**immunedragon** (normal 35 M r-p, tumor 60 M r-p)
**usablecoral** (normal 35 M r-p, tumor 65 M r-p)
**aptminnow** (normal 125 M r-p, tumor 110 M r-p)

Following cases also failed on Manta:
**usablecoral** (normal 35 M r-p, tumor 65 M r-p)
**goodbobcat** (normal: 190 Mr-p, tumor 103 Mr-p)

Following case failed on BaseRecalibrator:
**movedjay** (normal 70 M r-p, tumor 200 M r-p)

Sequence type (WES, TGA, WGS): **WES**

**Error message**
Below is an example of an error message. The same error appears aslo for the other failed cases.

**Manta error message**:
`Failed to complete command task: 'generateCandidateSV_0069' launched from master workflow, error code: 1`

`ERROR: exception while fetching BAM/CRAM region: '14:23855455-35783181' from file '/home/proj/production/cancer/cases/usablecoral/analysis/bam/normal.merged.bam'`

**VarDict error message:**
`Critical exception occurs on region: 2:231042772-231043071, program will be stopped.
Critical exception occurs on region: 2:231048187-231048456, program will be stopped.
Critical exception occurs on region: 2:231036094-231036583, program will be stopped.`

**BaseRecalibrator error message:**
`ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/usr/local/miniconda/envs/varcall_py36/opt/gatk-3.8/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties`

**Link to the error message**
`goodbobcat/logs/BALSAMIC.goodbobcat.manta_tumor_normal.42.sh_719271.err`
`goodbobcat/logs/BALSAMIC.goodbobcat.vardict_tumor_normal.101.sh_719351.err`
`movedjay/logs/BALSAMIC.movedjay.BaseRecalibrator.98.sh_720410.err`

Balsamic `v6.0.1`

**Additional context**
**NOTE:** Several samples in this project were very degraded and the above cases might include these degraded samples.

**Comment by keyvanelhami** [comment]
After talking to HFA, the Vardict error is related to memory issues and the memory should be increase to match the core allocation. All cases will be restarted once more to check if the same error appears or not

**Comment by keyvanelhami** [comment]
**All cases passed** after restarting. @hassanfa If you don't have any comments regarding why they passed, please close this issue

**Comment by hassanfa** [comment]
Thanks! I'll close this.
