### ISSUE TITLE
Somatic caller: Varlociraptor

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#495]
https://github.com/varlociraptor/varlociraptor

Varlociraptor is the new cool kid in the town. It's quite easy to setup and run. It is fairly fast, and has the features we're looking for: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-01993-6 (ease of use, FFPE artifact detection, sensitivity to noise, and more importantly calling variants from RNASeq)

**Comment by hassanfa** [comment]
As discussed with @keyvanelhami , we'll run one of our HD829 samples through this to see the results.

Important questions:
1. Can it reliably call FLT3 tandem duplications?
1. How are the results compared to VarDict?
1. Is it compatible with Scout? (DP, AD, etc)

**Comment by keyvanelhami** [comment]
I have started to look into the [docs](https://varlociraptor.github.io/docs/calling/) and have some questions:

**Preprocessing:**
1) What bam-file should I use, is it `tumor.merged.bam` ?
2) Should I use `human_g1k_v37.fasta` as `reference.fa` ?
3) What should I use for the candidate variants `candidates.bcf` ? 
4) Should I split the `candidates.bcf` with `rbt vcf-split` before running `varlociraptor preprocess variants` ?

**Comment by keyvanelhami** [comment]
5. Do we know the "normal contamination" when running tumor-only as described in **Single sample tumor-only calling**? If so, what values should be applied for the normal in the yaml-file?
6. Please provide some feedbacks on what values that I should use in the yaml-file

**Comment by hassanfa** [comment]
> I have started to look into the [docs](https://varlociraptor.github.io/docs/calling/) and have some questions:
> 
> **Preprocessing:**
> 
> 1. What bam-file should I use, is it `tumor.merged.bam` ?

Yes. This is marked duplicated and sorted.

> 2. Should I use `human_g1k_v37.fasta` as `reference.fa` ?

Yes.

> 3. What should I use for the candidate variants `candidates.bcf` ?

VarDict's output

> 4. Should I split the `candidates.bcf` with `rbt vcf-split` before running `varlociraptor preprocess variants` ?

Could you clarify what does `rbt vcf-split` does?

> 5. Do we know the "normal contamination" when running tumor-only as described in **Single sample tumor-only calling**? If so, what values should be applied for the normal in the yaml-file?

For HD829, we could set it at 10% and 0% normal contamination.

> 6. Please provide some feedbacks on what values that I should use in the yaml-file

Could you clarify specifically which values? We could start with default values from Varlociraptor

**Comment by hassanfa** [comment]
I'm closing this one. As it is stale.
