### ISSUE TITLE
Customer sample name in the scout.yaml file instead of internal case names (pet names)

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#506]
**Is your feature request related to a problem? Please describe.**
When uploading a case in scout with `balsamic plugins scout` our internal pet names are shown in Scout for the customer. This is a problem since the customer cannot connect which pet names that correlates to which sample/family names. Furthermore, this could be considered unprofessional towards the customers.

**Describe the solution you'd like**
Add the customer family name in the yaml-file instead of the pet name

**Current BALSAMIC version**
6.0.1

**Comment by hassanfa** [comment]
This is fixed in `cg`. closing,
