### ISSUE TITLE
[ Failed Analysis ] Missing vcfanno in balsamic container

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#515]
**Issue** 

rule `vep_somatic` fails. Because `vcfanno` command not found in the conda environment `annotate`

<img width="630" alt="vcfanno_issue" src="https://user-images.githubusercontent.com/6302819/100242923-9edd2f80-2f35-11eb-86af-b43fdcf3fdbc.png">

<img width="618" alt="vcfannomissing" src="https://user-images.githubusercontent.com/6302819/100242912-9c7ad580-2f35-11eb-95e5-dc0371048461.png">

Solution:

`conda install -c bioconda vcfanno`

**Comment by ashwini06** [comment]
@hassanfa : Have you encountered this issue while running the main balsamic workflow?

**Comment by hassanfa** [comment]
Current release doesn't have VCFAnno feature yet. Are you using develop container? https://hub.docker.com/r/hassanf/balsamic/tags?page=1&ordering=last_updated

Since next release, as we discussed, we'll have annotation in its own container.

**Comment by ashwini06** [comment]
> Current release doesn't have VCFAnno feature yet. Are you using develop container? https://hub.docker.com/r/hassanf/balsamic/tags?page=1&ordering=last_updated
> 
> Since next release, as we discussed, we'll have annotation in its own container.

I was using the .sif file from the previous release (_v6.0.1).

**Comment by hassanfa** [comment]
Then you should singularity pull the develop tag I linked above. latest release doesn't have vcfanno.

**Comment by ashwini06** [comment]
Solved!
