### ISSUE TITLE
Input information as a CSV/yaml/json/tsv files

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#521]
Title is pretty much descriptive.

Input for balsamic for analysis should be done via a structured data format. This will simplify cli options, provide opportunity for batch analysis, and storing these files.

Currently it is all done via 'balsamic case config' command. Which has 15(!) cli options (mandatory or optional).

Wish list:
1. Contain information about read number. This related to dynamic allocation of resources. See previous issue regarding this point.
2. Sample type, FFPE, FF, etc.
3. Expected tumor %
4. Expected coverage
5. Sample names and aliases
6. Read structure (for UMI cleanup)
7. Bed file for panel seq or in silico filtering
8. Application type: WES, TGA, or WGA

**Comment by Mropat** [comment]
So if possible, perhaps you would prefer to create the config in cg and pass it directly to BALSAMIC when executing `balsamic run analysis`?

**Comment by hassanfa** [comment]
Yes, just like a scout config.

case config command is a tad bit more complex, that has to be reduced first, then I will merge config case and run analysis into one command.

**Comment by Mropat** [comment]
Sounds good! Let me know all the fields you want to propagate from cg as part of the config!

**Comment by hassanfa** [comment]
CLI works just fine now. Closing this. If it needed we'll open.
