### ISSUE TITLE
[ Failed Analysis ] manta_tumor and vardict_tumor failed for 3 cases

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#545]
**Case or sample information**
**Internal sample id or case id:** firstfoal, smoothmutt, lightfly
**Amount read-pairs:** 41, (19N + 74T), 32
**Sequence type (WES, TGA, WGS):** TGA 

**Error message and links**
<ins>manta error:<ins>

`lightfly/logs/BALSAMIC.lightfly.manta_tumor_only.27.sh_927209.err `
```
FATAL_ERROR: BAM/CRAM index is not available for file: /home/proj/production/cancer/cases/lightfly/analysis/bam/tumor.merged.bam
```

<ins>Vardict error:<ins>

`smoothmutt/logs/BALSAMIC.smoothmutt.vardict_tumor_normal.143.sh_926924.err`
`firstfoal/logs/BALSAMIC.firstfoal.vardict_tumor_only.102.sh_927581.err`
```
Caused by: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
```

**Reason for failure**
The java memory issue have been observed before and the cases usually completed the pipelines by restarting the analaysis.

**Version (please complete the following information):**
`v6.0.1`

**Additional context**
@hassanfa `lightfly` this is a prioritized case and I will restart the case since other cases have passed after restarting them. Please come back to regarding this case if I should proceed in another way.

**Comment by hassanfa** [comment]
This is a known issue with Manta. Restarting the analysis should resolve the issue.

**Comment by keyvanelhami** [comment]
> This is a known issue with Manta. Restarting the analysis should resolve the issue.

I will restart all cases then, even the two with VarDict error

**Comment by keyvanelhami** [comment]
All cases are now completed after restarting them.
