### ISSUE TITLE
Sentieon TNScope PCR-free WGS

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#566]
**Describe the bug**
TNScope has default value of PCR model to conservative. In Clinical Genomics we are using PCR-free WGS, and it is important to provide an option to do so OR set `--pcr_indel_model NONE`.

**To Reproduce**
Regular WGS run using Sentieon

**Expected behavior**
When running WGS PCR-free, `--pcr_indel_model` should be set to `NONE`.

**If workflow, which rules**
`sentieon_TNscope` rule(s).

**Screenshots**
N/A

**Version (please complete the following information):**
`6.1.0`

**Additional context**
None.

**Comment by ashwini06** [comment]
Fixed in #603 . Closing it.
