### ISSUE TITLE
Wrong naming for bam-files in WGS workflow

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#577]
**Describe the bug**
The name of the final bam-file that will be delivered to the customer is wrong: `/home/proj/production/housekeeper-bundles/holyyak/2021-02-19/concatenated_ACC7589A1_XXXXXX_R.dedup.bam` 

**Expected behavior**
The name should be: `tumor.merged.bam`

**Version (please complete the following information):**
`balsamic, version 6.1.2`

**Comment by hassanfa** [comment]
resolved in #581
