### ISSUE TITLE
[ Failed Analysis ] BaseRecalibrator fails on Log4j2

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#583]
**Case or sample information**
Internal sample id or case id: `uniquefinch`
Amount read-pairs: 275 
Sequence type (WES, TGA, WGS): WES

**Error message**
```
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/usr/local/miniconda/envs/varcall_py36/opt/gatk-3.8/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/usr/local/miniconda/envs/varcall_py36/opt/gatk-3.8/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Error in rule BaseRecalibrator:
Exiting because a job execution failed. Look above for error message
```

**Link to the error message**
`/home/proj/production/cancer/cases/uniquefinch/logs/BALSAMIC.uniquefinch.BaseRecalibrator.54.sh_985480.err`

**Reason for failure**
Too much sequencing reads?

**If workflow, which rules**
`BaseRecalibrator` 

**Version (please complete the following information):**
`v6.0.1` 

**Additional context**
I have already restarted the case once, but I again got the same error.

**Comment by keyvanelhami** [comment]
@hassanfa FYI the case has already been restarted but I again got the same error.

**Comment by hassanfa** [comment]
I'm closing this since it is not a BALSAMIC error, but JVM bug.
