### ISSUE TITLE
[ Failed Analysis ] TIMEOUT for WGS case

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#594]
**Case or sample information**
Internal sample id or case id:  realmarten
Amount read-pairs: 365 (Normal), 1.300 (Tumor)
Sequence type (WES, TGA, WGS): WGS

**Error message**
`slurmstepd: error: *** JOB 1027159 ON compute-0-3 CANCELLED AT 2021-03-17T20:35:07 DUE TO TIME LIMIT ***`

**Link to the error message**
`/home/proj/production/cancer/cases/realmarten/logs/BALSAMIC.realmarten.cnvkit_paired.24.sh_1027159.err`

**Reason for failure**
TIME OUT

**Comment by hassanfa** [comment]
That's a lot of reads :-) After Hasta's maintenance, lets submit the job and we'll increase time limit manually.

**Comment by keyvanelhami** [comment]
Yes, I think it's because of the new app tags aiming to 120X coverage for tumors

**Comment by keyvanelhami** [comment]
Hasta maintenance is now done. Let me know when you have increased the time for cnv-kit

**Comment by keyvanelhami** [comment]
Restarting the analysis

**Comment by hassanfa** [comment]
I increased time limit, but also made a request to add you as an admin on slurm so you can handle these cases independently.

**Comment by hassanfa** [comment]
Let us close this issue for now.
