### ISSUE TITLE
[ Failed Analysis ] 

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/BALSAMIC#600]
**Case or sample information**
Internal sample id or case id: daringamoeba
Amount read-pairs: 
3990270376/2 ~ 2000 M
Sequence type (WGS):

**Error message**
```shell
fastp --thread 8 --in1 /home/proj/production/cancer/cases/daringamoeba/analysis/fastq/concatenated_ACC7702A1_XXXXXX_R_1.fastq.gz --in2 /home/proj/production/cancer/cases/dari    ngamoeba/analysis/fastq/concatenated_ACC7702A1_XXXXXX_R_2.fastq.gz --out1 /home/proj/production/cancer/cases/daringamoeba/analysis/fastq/concatenated_ACC7702A1_XXXXXX_R_1.int    erm.fastq.gz --out2 /home/proj/production/cancer/cases/daringamoeba/analysis/fastq/concatenated_ACC7702A1_XXXXXX_R_2.interm.fastq.gz --json /home/proj/production/cancer/cases    /daringamoeba/analysis/fastq/concatenated_ACC7702A1_XXXXXX_R_interm_fastp.json --html /home/proj/production/cancer/cases/daringamoeba/analysis/fastq/concatenated_ACC7702A1_XX    XXXX_R_interm_fastp.html --overrepresentation_analysis --trim_tail1 1 --n_base_limit 5 --length_required 25 --low_complexity_filter --trim_poly_g --detect_adapter_for_pe
 fastp v0.20.0, time used: 20901 seconds
 slurmstepd: error: *** JOB 1048195 ON compute-0-5 CANCELLED AT 2021-03-26T08:09:03 DUE TO TIME LIMIT ***
 Will exit after finishing currently running jobs.
 [Fri Mar 26 08:09:03 2021]
 Error in rule fastp:
 jobid: 0
 output: /home/proj/production/cancer/cases/daringamoeba/analysis/fastq/concatenated_ACC7702A1_XXXXXX_R_1.fp.fastq.gz, /home/proj/production/cancer/cases/daringamoeba/anal    ysis/fastq/concatenated_ACC7702A1_XXXXXX_R_2.fp.fastq.gz, /home/proj/production/cancer/cases/daringamoeba/analysis/qc/fastp/concatenated_ACC7702A1_XXXXXX_R_fastp.json, /home/    proj/production/cancer/cases/daringamoeba/analysis/qc/fastp/concatenated_ACC7702A1_XXXXXX_R_fastp.html
```

**Link to the error message**
`/home/proj/production/cancer/cases/daringamoeba/logs/BALSAMIC.daringamoeba.fastp.18.sh_1048195.err`

**Reason for failure**
A ton of read pairs and the script for fastp is not altered to the increase of work to be done

**If workflow, which rules**
Dont know.

**Version (please complete the following information):**
`version 6.0.0`

**Comment by hassanfa** [comment]
Some information for future reference and tracking new issues:

BALSAMIC uses default 8 core and 12:00:00 hour for any process that is not listed here: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/config/cluster.json Fastp rules are located here: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/snakemake_rules/quality_control/fastp.rule

Solution: Either to increase fastp process to 18:00:00 hours manually as an exception or make a hotfix. I suggest to restart the run once more. Then Keyvan or I will manually change the time allocation.

Does trailblazer show which jobs fail? I think it was added at some point but then removed. Maybe if trailblazer can help us to understand which jobs are failing often, we can allocate resources properly. I'll open an issue on cigrid/tb.

**Comment by hassanfa** [comment]
@karlnyr I see that the analysis is mostly done and only issue is the permission in the analysis dir. I'll close this one.
