### ISSUE TITLE
Incorrect table header in QC report

### ISSUE THREAD

**Issue by vwirta** [Clinical-Genomics/BALSAMIC#601]
**Describe the bug**
Two first columns in second  and third table (Sammanfattning and Täckningsgrad)´ of QC report are swapped.

**To Reproduce**
Open a QC report and check

**Expected behavior**
The order of columns is Sample ID (prov ID) followed by sample type (provtyp)

**Version (please complete the following information):**
at least in outpout genereated by version 6.1.2

**Comment by hassanfa** [comment]
Order is correct in version 7.+

![image](https://user-images.githubusercontent.com/1086877/123751356-f1aa0b80-d8b7-11eb-8f39-ef6322c5b85b.png)


Order is `prov ID` and `provtyp`

**Comment by hassanfa** [comment]
fixed in #659
