### ISSUE TITLE
Three cases failes on sentieon_consensuscall_umi

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/BALSAMIC#621]
**Case or sample information**
Internal sample id or case id: immunepossum, meetmouse, setbear
Amount read-pairs: 26M, 31M, 38.5M 
Sequence type (WES, TGA, WGS): TGA

**Error message**
Immunepossum:
```
*** Error in `/home/proj/bin/sentieon/sentieon-genomics-201911/libexec/util': free(): invalid next size (normal): 0x00007f3571c91d30 ***
```

meetmouse:
```
*** Error in `/home/proj/bin/sentieon/sentieon-genomics-201911/libexec/util': free(): invalid next size (normal): 0x00007f6c5aaaa270 ***
```

setbear:
```
*** Error in `/home/proj/bin/sentieon/sentieon-genomics-201911/libexec/util': double free or corruption (!prev): 0x00007fb9abdf56e0 ***
```

**Link to the error message**
```
/home/proj/production/cancer/cases/immunepossum/logs/BALSAMIC.immunepossum.sentieon_consensuscall_umi.87.sh_1173307.err
/home/proj/production/cancer/cases/meetmouse/logs/BALSAMIC.meetmouse.sentieon_consensuscall_umi.87.sh_1173211.err
/home/proj/production/cancer/cases/setbear/logs/BALSAMIC.setbear.sentieon_consensuscall_umi.87.sh_1173118.err
```

**Reason for failure**
Provide any theories regarding why the error message arises.

**If workflow, which rules**
If possible, and using the Snakemake workflows, the name of the affected rules and workflows.

**Version (please complete the following information):**
`balsamic --version` output

**Additional context**
I tried to restart case immunepossum after checking that sentieon was working to see if it was a temporarily error, that's why there is extra files for that case.

SampleIDs: ACC7117A13, ACC7117A14 and ACC7117A23, comment on samples: "Reference sample for tga-batches to study prep performance."

**Comment by moahaegglund** [comment]
@hassanfa @ashwini06  I removed the entire case folders under `/home/proj/production/cancer/cases` and restarted all three cases, `cg workflow balsamic start <caseID> -r`. They all fail with the same error message. 

(The pipeline is still running for the cases.)

**Comment by hassanfa** [comment]
@moahaegglund thanks for rerunning it. We need to contact Sentieon with this bug. These samples look like some sort internal tests as it says NA24143 in statusdb. I guess we can share this data with Sentieon. Do you know if it possible?

**Comment by vwirta** [comment]
if they are hapmap samples, we can share with sentieon
