### ISSUE TITLE
Does TWIST lymfoid panel work in scout cancer view? 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/BALSAMIC#622]
Hi, 

I would like some help as something seems to be strange for this case: https://scout.scilifelab.se/cust087/F0039757. I have ordered it to be run with the TWIST lymfoid panel (in orderportalen), so I really hope it is correct uploaded in scout. 

Here is first of all the variant list https://scout.scilifelab.se/cust087/F0039757/cancer/variants?variant_type=clinical which has suspiously few variants (one of my colleages has emailed Hassan regarding few varaints in a separate email, but for the myeloid panel were we also had very few varaints compared to normal this time around). 

1 st question: What type of variant is it in the 2nd row? when I click into it it says "displaying only the 30 first variants (!?)

2nd question: If I use this filtering and it seems to work... but gives me roughly ~200 variants. 
![image](https://user-images.githubusercontent.com/62098218/117663415-f0eed600-b1a0-11eb-8ebe-b6a1e221ade2.png) 

however, when I use a "preset" filter which has the same filter as above, it gives me 25 variants?
![image](https://user-images.githubusercontent.com/62098218/117663935-7a9ea380-b1a1-11eb-835b-8529c27aeb6f.png)

What am I missing here? Thankful for any help, or if someone can tell me what mistakes I am doing... 

Hälsningar Hero

**Comment by hassanfa** [comment]
1. First of all about number of variants: I replied to the email, and variant lists are correct. We just applied a relaxed filter of Gnomad filter at cut off of 0.005, or 0.5%. Results are from the new release of BALSAMIC, release 7.

2. Second about SV: Yeap, Sentieon output is fixed but not VarDict. VarDict is the only variant caller that can reliably call FLT3-ITD, and of course calls other similar InDels of the similar size (<600bp). It is unfortunate we ended up with this large deletion in VarDict results. Interesting enough this particular deletion is also called in Manta. Unfortunately until we separate SVs without missing FLT3, we have to kinda tolerate these artifacts (if they can be called so...). Hopefully we will have a FLT3 specific caller (TIDDIT is a very candidate) and use SVs in Scout to show these.


## Summary:

1. Number of variants are alright, it is result of the new Gnomad filter.
2. The unusual variant is a SV that didn't get filtered out from VarDict results.

**Comment by dnil** [comment]
The difference is likely in Region annotations. They are set to "exonic" or "splicing" in your saved filter. If I toggle them out to search for any region I get from about 25 to about 200. Perhaps you simply did not set them when you filled in the numbers manually, or had them off for testing something:
![Screenshot 2021-05-11 at 07 25 29](https://user-images.githubusercontent.com/758570/117762991-5935ca00-b22a-11eb-8a0a-d40231fad4cc.png)

**Comment by dnil** [comment]
And for @hassanfa: I am somewhat aware of the FTL3-ITD situation. Couldn't you in the meantime "just" bcftools filter or awk out all vars that hail as variant type DEL, DUP, CNV, INV, BND, into a separate cancer_sv VCF, duplicating most of the header, and doing the opposite for SNV and possibly INDEL for the cancer (snv) vcf? You could even reuse that later when you have more callers and `svdb merge` them. I know this means one more file to pass to housekeeper, set in the scout load yaml config, but you presumably have that set up for the sentieon track anyway?

**Comment by hassanfa** [comment]
That's what I did for TNScope, but VarDict is supposed to not to call any InDel larger than 600bp.

ps: we won't make it for the release today, but the next one I'll make sure this is fixed. Any SV called by VarDict larger than 1Kbp will be filtered out.

**Comment by dnil** [comment]
Quite understand that, and also about making sure programs do what they are supposed to. Just suggesting why not make the best of it and allow VarDict to call larger variants if it can - and as it happens uniquely well for at least one region - just sort them into a separate file? From the VCF line above it seems to set the type ok, and has the likes of small A>AGTA as <INDEL> but . G length=8000000 SVTYPE=DEL as <DEL>. Anyway, looking forward to it!

**Comment by dnil** [comment]
Thanks, that should work just fine for the VarDict as well. Again, looking forward to it!

**Comment by heronikdin** [comment]
> The difference is likely in Region annotations. They are set to "exonic" or "splicing" in your saved filter. If I toggle them out to search for any region I get from about 25 to about 200. Perhaps you simply did not set them when you filled in the numbers manually, or had them off for testing something:
> ![Screenshot 2021-05-11 at 07 25 29](https://user-images.githubusercontent.com/758570/117762991-5935ca00-b22a-11eb-8a0a-d40231fad4cc.png)

haha and I was sooo sure everything was the same... thank you! and sorry for wasting your time  :)

**Comment by dnil** [comment]
Not a waste - stay vigilant! 🧐
