### ISSUE TITLE
Refactor rules according BALSAMIC's Snakemake etiquette 

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#636]
- [x] align/bwa_mem.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] align/sentieon_alignment.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] annotation/rankscore.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] annotation/varcaller_filter_tumor_normal.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] annotation/varcaller_filter_tumor_only.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] annotation/varcaller_wgs_filter_tumor_normal.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] annotation/varcaller_wgs_filter_tumor_only.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] annotation/vep.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
 - [x] annotation/varcaller_sv_filter.rule
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] dragen_suite/dragen_dna.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/contest.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/fastp.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/fastqc.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/GATK.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/mosdepth.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/multiqc.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/picard.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/picard_wgs.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/sambamba_depth.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/samtools.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] quality_control/sentieon_qc_metrics.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] umi/generate_AF_tables.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] umi/mergetype_normal_umi.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] umi/mergetype_tumor_umi.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] umi/qc_umi.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] umi/sentieon_consensuscall.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] umi/sentieon_umiextract.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] umi/sentieon_varcall_tnscope.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] umi/sentieon_varcall_tnscope_tn.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/cnvkit_paired.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/cnvkit_single.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/germline.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/mergetype_normal.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/mergetype_tumor.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/sentieon_germline.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/sentieon_split_snv_sv.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/sentieon_tn_varcall.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/sentieon_t_varcall.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/somatic_sv_tumor_normal.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/somatic_sv_tumor_only.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/somatic_tumor_normal.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/somatic_tumor_only.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette 
- [x] variant_calling/split_bed.rule 
   - [x] rule name 
   - [x] shell triple quote 
   - [x] Snakemake etiquette

**Comment by ashwini06** [comment]
One huge effort 172/172 tasks done :sweat_drops:  Closing this PR :heart_eyes_cat:

**Comment by hassanfa** [comment]
Well done @ashwini06 You did the heavy lifting on this one.
