### ISSUE TITLE
Add Sentieon to its own container

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#640]
To enable Sentieon in BALSAMIC, the host machine should have the following environmental variables set: SENTIEON_INSTALL_DIR and SENTIEON_LICENSE. This becomes tricky when we want to update or use a different version of Sentieon. Testing becomes hindered and we can't really update Sentieon to new release within a PR or branch in BALSAMIC.

Solution:
- Add Sentieon to its own container, remember to do port forwarding!

**Comment by pbiology** [comment]
Will be dealt with on server side
