### ISSUE TITLE
Cancer scout

### ISSUE THREAD

**Issue by AleksandraKrstic** [Clinical-Genomics/BALSAMIC#642]
Hi, we wonder about the variants in the WT1, case F0040117:
Are two insertions actually same variant? c.1144_1150dup (vaf 10%) and c.1151_54dup (vaf3%)? Or are they artefact?

Thanks,
Aleksandra

**Comment by hassanfa** [comment]
@AleksandraKrstic can you please share the link for the variant? Two insertions look like they should be the merged.

Also agreed with Daniel, this also looks like an artifact.

**Comment by hassanfa** [comment]
@AleksandraKrstic 

They are distinct variants, and it seems the variant at:

https://scout.scilifelab.se/cust087/F0040117/61f25d5cd07a298090ccd0b44e17be34?cancer=yes
Position 11:32417912	Change C→CCGTA

has higher strand bias compared to the other one, 1.06 compared to 0.36 in the other one. Both of them are within acceptable range.

Unfortunately there is no strict threshold for the strand bias cut off, and we only exclude obvious outliers. i.e. those that have 0 reads in one strand.

Besides strandbias, variant caller also reports an adjusted allelic fraction of 0.0007 for "Position 11:32417912	Change C→CCGTA" and 0.012. Adjusted AF is a value that is calculated after indel local realignment. While we don't use this value in filtering, but definitely it is a sign of some of sort of bias/artifact.

**Comment by AleksandraKrstic** [comment]
Thank you Hassan,
If I understand correct: Both variants are true, but one have lower vaf because of bias, so in reality that one is actually with higher vaf?


Aleksandra Krstic, PhD
Bitr Sjukhusgenetiker
Klinisk Genetik, L5:03
Karolinska Universitetssjukhus, Solna
0851770453
0760782721

Från: Hassan Foroughi ***@***.***>
Skickat: den 10 juni 2021 14:20
Till: Clinical-Genomics/BALSAMIC ***@***.***>
Kopia: Aleksandra Krstic ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/BALSAMIC] Cancer scout (#642)


@AleksandraKrstic<https://github.com/AleksandraKrstic>

They are distinct variants, and it seems the variant at:

https://scout.scilifelab.se/cust087/F0040117/61f25d5cd07a298090ccd0b44e17be34?cancer=yes
Position 11:32417912 Change C→CCGTA

has higher strand bias compared to the other one, 1.06 compared to 0.36 in the other one. Both of them are within acceptable range.

Unfortunately there is no strict threshold for the strand bias cut off, and we only exclude obvious outliers. i.e. those that have 0 reads in one strand.

Besides strandbias, variant caller also reports an adjusted allelic fraction of 0.0007 for "Position 11:32417912 Change C→CCGTA" and 0.012. Adjusted AF is a value that is calculated after indel local realignment. While we don't use this value in filtering, but definitely it is a sign of some of sort of bias/artifact.

**Comment by hassanfa** [comment]
You are correct. At this point, I'd mark the second one a low quality variant because of very low adjust VAF (=0.0007) and thus exclude it from the rest of variants.

I see that you also marked the case as solved. If this issue is not of concern anymore, shall we close it?

**Comment by AleksandraKrstic** [comment]
Yes, thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
