### ISSUE TITLE
singularity shell actions 

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#654]
**Describe the bug**
While activating singularity container for `varcall_cnvkit`; shell command-line return following message :

`/.singularity.d/actions/shell: /.singularity.d/env/10-docker2singularity.sh: line 1: ash\: not found`

<img width="631" alt="ss1" src="https://user-images.githubusercontent.com/6302819/122553421-efce8580-d037-11eb-9ae9-54709d995838.png">

**To Reproduce**
Try this command
`singularity shell /home/proj/stage/cancer/balsamic_cache/7.2.0/containers/varcall_cnvkit.sif`

**Additional context**
contents of `/.singularity.d/env/10-docker2singularity.sh`.
```
!/bin/sh
export PATH="/opt/conda/bin/:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export LANG=${LANG:-"C.UTF-8"}
export LC_ALL=${LC_ALL:-"C.UTF-8"}
export ENV=${ENV:-"/root/.shinit   # set path to \\`ash\\` equivalent of ~/.bashrc"}
```

**Comment by hassanfa** [comment]
I confirmed this on all containers.

Things i found:

1. Env vars in container are the culprit.
2. This is the result of base docker image we have for all containers.
3. Singularity entry point might be the solution.

**Comment by ashwini06** [comment]
While checking with #870, updating the alphine image will fix `ash\ not found` message.

**Comment by ashwini06** [comment]
This is solved by updating the container base image to `4.10.3-alphine`
