### ISSUE TITLE
[ Failed Analysis ] sentieon umi consensus

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/BALSAMIC#656]
**Case or sample information**
Internal sample id or case id: ACC7239A101, rulinglynx 
Amount read-pairs: 85481021
Sequence type (WES, TGA, WGS): TGS

**Error message**
```
export MALLOC_CONF=lg_dirty_mult:-1
/home/proj/bin/sentieon/sentieon-genomics-202010.01/bin/sentieon umi consensus -t 24 -i /home/proj/production/cancer/cases/rulinglynx/analysis/umi/concatenated_ACC7239A101_XXXXXX_R.align.umi.bam -o /home/proj/production/cancer/cases/rulinglynx/analysis/umi/concatenated_ACC7239A101_XXXXXX_R.consensuscall.umi.fastq.gz --input_format BAM --umi_tag XR --read_name_prefix 'UMI-'; 
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Link to the error message**
/home/proj/production/cancer/cases/rulinglynx/logs/BALSAMIC.rulinglynx.sentieon_consensuscall_umi.134.sh_1327963.err

**Reason for failure**
-

**If workflow, which rules**
sentieon_consensuscall_umi

**Version (please complete the following information):**
balsamic, version 7.2.2

**Additional context**
-

**Comment by hassanfa** [comment]
@henningonsbring I deleted old analysis, and restarted after new patch release. Could you monitor the analysis let us know if it fails again?

**Comment by henningonsbring** [comment]
It has failed again

**Comment by hassanfa** [comment]
> It has failed again

No it is not. 😉  This particular UMI step finished successfully. Closing it.

Try running `balsamic report status -s rulinglynx.json -m`.
