### ISSUE TITLE
[ Failed Analysis ] vardict_tumor_normal

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/BALSAMIC#660]
**Case or sample information**
Internal sample id or case id: causalowl, ACC7239A70 and ACC7239A21
Amount read-pairs: 44045714 (ACC7239A70) and 104500508 (ACC7239A21)
Sequence type (WES, TGA, WGS): TGS

**Error message**
```
WARNING: BAM index file /home/proj/production/cancer/cases/causalowl/analysis/bam/tumor.merged.bam.bai is older than BAM /home/proj/production/cancer/cases/causalowl/analysis/bam/tumor.merged.bam
Critical exception occurs on region: 15:42028278-42028996, program will be stopped.
java.util.concurrent.CompletionException: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
```

**Link to the error message**
/home/proj/production/cancer/cases/causalowl/logs/BALSAMIC.causalowl.vardict_tumor_normal.115.sh_1344586.err

**Reason for failure**
-

**If workflow, which rules**
vardict_tumor_normal

**Version (please complete the following information):**
balsamic, version 7.2.2

**Additional context**
Same problem for case aboverhino: `/home/proj/production/cancer/cases/aboverhino/logs/BALSAMIC.aboverhino.vardict_tumor_normal.117.sh_1346510.err`

**Comment by hassanfa** [comment]
Try rerunning this case. With VarDict reruns usually solve the issue.

**Comment by henningonsbring** [comment]
causalowl and aboverhino delivered to customer after restarting the analysis
