### ISSUE TITLE
Auto download reference and check the URLs are valid.

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#675]
**Is your feature request related to a problem? Please describe.**
Reference file availability is a bottleneck for updating and releases. Sources can disappear, or temporarily go offline.

**Describe the solution you'd like**
To check resource availability regularly.

**Describe alternatives you've considered**
Self hosting reference file: Not possible due to licensing issues.

**Additional context**
- Alternative is to create a cronjob on Hasta to check the download process.

**Expected output for the feature**
Warn when a reference file is missing or it is not available.

**Current BALSAMIC version**
`7.2.5`

**Comment by hassanfa** [comment]
TODO:
- [ ] Dry run workflow
- [ ] Only container download
- [ ] Validated URL: is it possible to partially download to check it is working? or Just download the whole thing?

**Comment by pbiology** [comment]
Refinement 2022-12-13:
- A GitHub action could check the URLs
- A new issue for the action will be done (@ivadym ) and this can be closed

**Comment by ivadym** [comment]
Closing https://github.com/Clinical-Genomics/BALSAMIC/issues/1054
