### ISSUE TITLE
Estimate gender from BAM coverage output of mosdepth

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#684]
**Is your feature request related to a problem? Please describe.**
Estimate gender and match it with reported gender.

**Describe the solution you'd like**
1. CLI option to accept a reported gender with a default value
2. Estimate gender from mosdepth/samtools idxstats and match with reported

**Describe alternatives you've considered**
- mosdepth coverage
- samtools idxstats
- ascatNgs's chrY loci

**Additional context**
This is useful for both WES, WGS, and TGS. Although for TGS it's tricky, cause we don't always have chrX or chrY in target regions.

**Expected output for the feature**
- In the final QC/Coverage report
- Supply this info for ascatNgs

**Current BALSAMIC version**
`7.2.6`

**Comment by ashwini06** [comment]
Gender information is parsed from the statusdb to balsamic config json via cg. Done in #955
