### ISSUE TITLE
Submit reference jobs to cluster

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#686]
**Is your feature request related to a problem? Please describe.**
reference generation workflow takes a long time to complete. It is a single workflow that cannot be submitted to cluster.

**Describe the solution you'd like**
It can be parallelized and optimized to submit each individual rules as jobs to cluster.

**Describe alternatives you've considered**
None.

**Additional context**
Relevant workflow is: `reference.smk` 

**Expected output for the feature**
`balsamic init` should be able to submit the jobs to the cluster.

**Current BALSAMIC version**
`7.2.6`

**Comment by ashwini06** [comment]
Done in #762
