### ISSUE TITLE
add assembly to bam header

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#688]
**Is your feature request related to a problem? Please describe.**
The bam header is missing assembly 

**Describe the solution you'd like**
BALSAMIC uses GRCh37 or hg38 so the bam header should contain one of them

**Describe alternatives you've considered**
If possible, a clear and concise description of any alternative solutions or features you've considered.

**Additional context**
If possible, add any other context or screenshots about the feature request here.

**Expected output for the feature**
If possible, an example of expected output

**Current BALSAMIC version**
`7.2.6`

**Comment by hassanfa** [comment]
is this still an issue @khurrammaqbool ? Could you describe it a bit further.

**Comment by khurrammaqbool** [comment]
Although it would be nice to have a well defined bam header, currently BALSAMIC is working fine with alternative solutions. This issue can be opened again if needed so closing it now.
