### ISSUE TITLE
Delly failing on tumor-normal with wrong sample name error in sample.csv

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#749]
**Describe the bug**
Delly failing on tumor-normal with wrong sample name error in sample.csv

**To Reproduce**
Run delly in in tn wgs and panel mode.

**Expected behavior**
Delly to call variants sucessfully

**If workflow, which rules**
delly_tumor_normal in balsamic.smk

**Screenshots**
N/A

**Version (please complete the following information):**
8.0.2

**Additional context**
N/A

**Comment by ashwini06** [comment]
Delly fails on this panel-TN case error. log here `/home/proj/long-term-stage/cancer/UMI_analysis_runs_APJ/cancer_test_datasets/panel_TN/equalbug2/logs.35/BALSAMIC.equalbug2.delly_tumor_normal.110.sh_1836472.err`
<img width="1385" alt="dlly" src="https://user-images.githubusercontent.com/6302819/135598309-e8d31920-5e67-49c9-ab63-55ef6acff734.png">
