### ISSUE TITLE
Remove activating environments from reference+PON workflow

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#764]
W.R.T the latest implementation of removing source activate https://github.com/Clinical-Genomics/BALSAMIC/pull/759
Reference.smk/PON.smk needs to be refactored as well

https://github.com/Clinical-Genomics/BALSAMIC/blob/a792f6f77a07b16ef6585dad62d1a93126cce4c6/BALSAMIC/workflows/reference.smk#L230

https://github.com/Clinical-Genomics/BALSAMIC/blob/a792f6f77a07b16ef6585dad62d1a93126cce4c6/BALSAMIC/workflows/reference.smk#L262

https://github.com/Clinical-Genomics/BALSAMIC/blob/a792f6f77a07b16ef6585dad62d1a93126cce4c6/BALSAMIC/workflows/reference.smk#L283

https://github.com/Clinical-Genomics/BALSAMIC/blob/a792f6f77a07b16ef6585dad62d1a93126cce4c6/BALSAMIC/workflows/reference.smk#L303

https://github.com/Clinical-Genomics/BALSAMIC/blob/a792f6f77a07b16ef6585dad62d1a93126cce4c6/BALSAMIC/workflows/reference.smk#L325

https://github.com/Clinical-Genomics/BALSAMIC/blob/a792f6f77a07b16ef6585dad62d1a93126cce4c6/BALSAMIC/workflows/reference.smk#L348

https://github.com/Clinical-Genomics/BALSAMIC/blob/a792f6f77a07b16ef6585dad62d1a93126cce4c6/BALSAMIC/workflows/PON.smk#L71

https://github.com/Clinical-Genomics/BALSAMIC/blob/a792f6f77a07b16ef6585dad62d1a93126cce4c6/BALSAMIC/workflows/PON.smk#L90

https://github.com/Clinical-Genomics/BALSAMIC/blob/a792f6f77a07b16ef6585dad62d1a93126cce4c6/BALSAMIC/workflows/PON.smk#L108

**Comment by hassanfa** [comment]
PoN workflow needs `source activate` to be removed as well.

**Comment by ashwini06** [comment]
Done in #769
