### ISSUE TITLE
Problems running vep_install with develop-annotate container

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#768]
Reference generation with using `develop` container exits on `vep_install` job 

<img width="461" alt="red" src="https://user-images.githubusercontent.com/6302819/134156520-3f7d2c50-4be6-4025-a11f-16698cb56546.png">

Problems 
While building `develop-annotate` container, conda failed with vep installation

<img width="373" alt="vep" src="https://user-images.githubusercontent.com/6302819/134156206-3cb9c215-82c7-48b9-a0ba-d9ae4b8af02f.png">

**Comment by hassanfa** [comment]
done in #770
