### ISSUE TITLE
[Failed Analysis]: Wrong manta install_path

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#776]
While running the case `equalbug` (TN), the workflow fails with manta rule. Check the screenshot for error
<img width="1438" alt="Screenshot 2021-09-28 at 11 10 10" src="https://user-images.githubusercontent.com/6302819/135060349-0d2d5dae-faa8-474d-be2b-d4919f198505.png">

Solution:

The path here https://github.com/Clinical-Genomics/BALSAMIC/blob/dd4e99ebe67d541aa3d889037447ffc4f5ee0de3/BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule#L32 needs to corrected with proper one. 

**References and other implementations**
Also T-only manta
https://github.com/Clinical-Genomics/BALSAMIC/blob/dd4e99ebe67d541aa3d889037447ffc4f5ee0de3/BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule#L28

**Comment by hassanfa** [comment]
The new path should be: ` /opt/conda/share/manta-1.6.0-1/libexec/convertInversion.py `

**Comment by ashwini06** [comment]
Fixed un #781
