### ISSUE TITLE
[Failed Analysis]: wrong path for gatk install 

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#777]
While running the case equalbug (TN), the workflow fails with  rule `gatk_haplotypecaller`. Check the screenshot for error
<img width="1435" alt="Screenshot 2021-09-28 at 11 51 14" src="https://user-images.githubusercontent.com/6302819/135065193-c18df236-279e-434d-9a6c-e3baab89c70d.png">

**Solution**

https://github.com/Clinical-Genomics/BALSAMIC/blob/66ee0ca7f7626207230c9f374c06773f511a7ef0/BALSAMIC/snakemake_rules/variant_calling/germline.rule#L30

replace with correct gatk install path (`/opt/conda/pkgs/gatk-3.8-hdfd78af_11/opt/gatk-3.8/GenomeAnalysisTK.jar`)

**Comment by hassanfa** [comment]
Correct path should be `/opt/conda/opt/gatk-3.8/GenomeAnalysisTK.jar`

**Comment by ashwini06** [comment]
Fixed in #781
