### ISSUE TITLE
Increase slurm TIME_LIMIT for cnvkit_paired when running WGS samples

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/BALSAMIC#779]
**Is your feature request related to a problem? Please describe.**
When running WGS samples in balsamic, cnvkit_paired sometimes times out after 720 min (12h). These are then restarted and the time limit increased manually. This often results in delivery delays up to two days.

**Describe the solution you'd like**
Increase slurm TIME_LIMIT for cnvkit_paired when running WGS samples.

**Additional context**
Example case: calmcaiman
![Screenshot 2021-09-28 at 15 46 11](https://user-images.githubusercontent.com/69356202/135099400-0c8eb289-482c-4c54-b650-fca0c73ad2f3.png)

**Current BALSAMIC version**
balsamic, version 7.2.5

**Comment by vwirta** [comment]
I think we are in the process of switching off CNVkit in BALSAMIC WGS...  @hassanfa can confirm
We will instead have ascatNGS delivering CNA data

**Comment by hassanfa** [comment]
That is correct. CNVKit is already turned off in the latest release and will be replaced with ascatNgs.

@Vince-janv please increase the resources for CNVKit job manually if possible until we deploy v 8.X.X in prod.

I'll close this issue if that's ok, please open again if increasing timelimit is not agreeable.
