### ISSUE TITLE
Balsamic container installation fails unexpectedly

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#791]
**Describe the bug**
Balsamic container GitHub action build fails unexpectedly. However, after rerunning the jobs, the image is installed correctly.

Complete log: https://github.com/Clinical-Genomics/BALSAMIC/pull/786/checks?check_run_id=3856453591

**Possible causes/solutions**
- https://github.com/pydata/bottleneck/issues/281
- pip install fails due to race condition
- Lock version of **pygraphviz**

**Comment by ashwini06** [comment]
Its hard to understand why balsamic container builds fails on certain occasions. In the above log, it points to the numpy installation issues. One solution could be upgrading the `python-version` greater that `3.7.1` might help.
<img width="1335" alt="s1" src="https://user-images.githubusercontent.com/6302819/137706371-6c5aa18f-d496-4f71-9b1a-63f85e34be52.png"> 

For this [PR](https://github.com/Clinical-Genomics/BALSAMIC/pull/797), balsamic build failed dues to `musl-locales`
https://github.com/Clinical-Genomics/BALSAMIC/pull/797/checks?check_run_id=3908766204

```
#6 1.835 Cloning into 'musl-locales'...
#6 2.185 warning: redirecting to https://gitlab.com/rilian-la-te/musl-locales.git/
#6 2.302 error: RPC failed; HTTP 503 curl 22 The requested URL returned error: 503
#6 2.304 fatal: expected flush after ref listing
#6 ERROR: executor failed running [/bin/ash -eo pipefail -c apk add --no-cache --virtual .locale_tmp cmake make gettext-dev &&     git clone https://gitlab.com/rilian-la-te/musl-locales &&     cd musl-locales && cmake -DLOCALE_PROFILE=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr . && make && make install &&     cd .. && rm -r musl-locales &&     apk del .locale_tmp]: exit code: 128
------
 > [3/7] RUN apk add --no-cache --virtual .locale_tmp cmake make gettext-dev &&     git clone https://gitlab.com/rilian-la-te/musl-locales &&     cd musl-locales && cmake -DLOCALE_PROFILE=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr . && make && make install &&     cd .. && rm -r musl-locales &&     apk del .locale_tmp:

```

@ivadym: Can you have a look into this issue?

**Comment by ivadym** [comment]
New failure after merging into develop:

https://github.com/Clinical-Genomics/BALSAMIC/runs/4066860187?check_suite_focus=true

**Comment by ivadym** [comment]
This issue persists over time (#860), further actions are required:

> Sometimes generating the balsamic container via git actions fails due to python dependency issues. For eg: https://github.com/Clinical-Genomics/BALSAMIC/runs/5095568999?check_suite_focus=true
> 
> One needs to figure out every single time, the required system dependencies and runtime unexpected bugs.
> 
> Currently, we have `miniconda3:4.9.2-alpine` as the base image for docker and alpine might be the culprit for this issue. Check/update to other supporting base images to resolve this issue.

**Comment by ashwini06** [comment]
The base image of the docker balsamic container will be updated to `miniconda3:4.10.3-alpine` from v9.0.0. Current changes in [develop](https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/containers/balsamic/Dockerfile). So far, there is no occurence of balsamic container failure. Reopen the issue if its not the case
