### ISSUE TITLE
Generate metrics delivery YAML for Vogue

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#798]
**Feature**
The workflow should produce a YAML file (`<case>_metrics_deliverables.yaml`) containing 1 to n specific metrics, having each of them a set of mandatory keys and values:
- **header**: data (optional)
- **id**: sample ID
- **input**: input file
- **name**: metric name
- **step**: step that generated metric
- **value**: metric value

**Additional context**
- Format: [Atlas docs](https://github.com/Clinical-Genomics/atlas/blob/6170edaae66fa70bf25b478f2ea6ae2f0cd78572/docs/infrastructure/dataflow/workflow/metrics_delivery.md)
- [Original issue](https://github.com/Clinical-Genomics/project-planning/issues/26)
- [Metrics](https://github.com/Clinical-Genomics/cgp-implementation-KAPA-second-generation/issues/8) 

**Expected output for the feature**
```
- header: null
  id: ACC8837A1
  input: concatenated_ACC8837A1_XXXXXX_R.umi.collect_hsmetric
  name: PCT_TARGET_BASES_1000X
  step: picard_CollectHsMetrics
  value: 0.000228
- header: null
  id: ACC8837A1
  input: concatenated_ACC8837A1_XXXXXX_R.sorted.insertsizemetric
  name: MEAN_INSERT_SIZE
  step: picard_CollectInsertSizeMetrics
  value: 201.813166
```

**Current BALSAMIC version**
`balsamic version 8.1.0`

**Comment by ivadym** [comment]
👍

And what about retrieving these metrics from an already analysed case? I was thinking about including a CLI command to the delivery report one, something like this: `balsamic report deliver -s case.json --metrics-delivery`.

**Comment by hassanfa** [comment]
This is a better solution, go for it! 👌

**Comment by ivadym** [comment]
Merged!
