### ISSUE TITLE
Problems with multiqc HSmetrics dict

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#804]
**Describe the bug**
Issue reported by @ivadym 
From balsamic v8.1.0, the reported HSmetrics in `multiqc_data.json` is not correct, where only umi_hsmetrics is being reported. The correct format should include reporting of both picard_hsmetrics from the main workflow and umi workflow. Currently, in production (v7.2.5) we have the correct format. Check these 2 files for more details. 

Production version (v7.2.5)
`/home/proj/production/cancer/cases/sweetelf/analysis/qc/multiqc_data/multiqc_data.json`

Develop version (v 8.1.x)
`/home/proj/stage/cancer/cases/sweetelf/analysis/qc/multiqc_data/multiqc_data.json`

**Expected behavior**
Current develop should generate multiqc_data.json same as the v7.2.5, where both HSmetrics from both workflows are listed in HSmetric dict

**Comment by ivadym** [comment]
Addressed in #805.
