### ISSUE TITLE
Testing of Balsamic v8.2 on stage

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#818]
### Background

Balsamic version 8.2.1 is the latest release. Before deploying it to production, this newest release needs to be adequately tested with different analysis types for various [validation cases](https://github.com/Clinical-Genomics/cg/blob/370319c84bc7263a3f5279796cd67b1a5cd4a808/cg/constants/compression.py#L30-L41)

### balsamic --version
balsamic, version 8.2.1

### Steps to reproduce

1. Allocate stage resources for `balsamic-stage` via `paxa`
2. Change Conda environment: `conda activate S_BALSAMIC` 
2. Install the latest version of balsamic: `pip install --no-cache-dir -U git+https://github.com/Clinical-Genomics/BALSAMIC`
3. Check the version installed: `balsamic --version`
4. Free up the resources for `paxa`
5. Generate balsamic cache: `balsamic init --outdir /home/proj/stage/cancer/balsamic_cache --cosmic-key ${COSMIC_KEY} --genome-version hg19 --account development -r` 
5. Run the validation cases through CG command line: `cg workflow balsamic start $caseid -r`
6. Check the status of the runs on [trailbazer_stage](https://cigrid-stage.scilifelab.se/analyses)
7. When the analysis is finished. Store cases in housekeeper: `cg workflow balsamic store $caseid`
************************

#### Analysis run successfully finished

- [x] PANEL TUMOR_ONLY CASE (bosssponge)
- [x] PANEL TUMOR_NORMAL CASE (unitedbeagle)
- [x] PANEL_UMI TUMOR_ONLY CASE (uphippo)
- [x] PANEL_UMI TUMOR_NORMAL CASE (equalbug)
- [x] WGS TUMOR_ONLY CASE (civilsole)
- [x] WGS TUMOR_NORMAL CASE (fleetjay)

#### Storing of results in housekeeper 

- [x] PANEL TUMOR_ONLY CASE (bosssponge)
- [x] PANEL TUMOR_NORMAL CASE (unitedbeagle)
- [x] PANEL_UMI TUMOR_ONLY CASE (uphippo)
- [x] PANEL_UMI TUMOR_NORMAL CASE (equalbug)
- [x] WGS TUMOR_ONLY CASE (civilsole)
- [x] WGS TUMOR_NORMAL CASE (fleetjay)

**Comment by ashwini06** [comment]
I will close this issue, when the `cg store` part is also finished

**Comment by hassanfa** [comment]
I accidentally opened and closed it again...

**Comment by ashwini06** [comment]
Need to update housekeeper tags in hermes. Create hermes PR and  update tags[ here ](https://github.com/Clinical-Genomics/hermes/blob/main/cg_hermes/config/balsamic.py)

**Comment by ashwini06** [comment]
Type of Deliverables in housekeeper:

 **Panel Cases**

#### QC and reports
```
*_report.html
.json
_BALSAMIC_8.2.0_graph.pdf
multiqc_report.html
multiqc_data.json
fastp.json
fastp.html
```

### Raw data files  and Aligned files

```
concatenated_*.fp.fastq.gz
tumor.merged.bam
tumor.merged.bam.bai
tumor.merged.cram
tumor.merged.cram.crai
```

If TN analysis:
```
normal.merged.bam
normal.merged.bam.bai
normal.merged.cram
normal.merged.cram.crai
```

### Variant-called vcf files
#### Somatic-callers SNV/INDELs
```
.vardict.all.filtered.vcf.gz
.vardict.all.filtered.vcf.gz.tbi
.vardict.all.filtered.pass.vcf.gz
.vardict.all.filtered.pass.vcf.gz.tbi
.vardict.all.vcf.gz_summary.html
.vardict.all.stats
.TNscope_umi.all.filtered.vcf.gz
.TNscope_umi.all.filtered.vcf.gz.tbi
.TNscope_umi.all.filtered.pass.vcf.gz
.TNscope_umi.all.filtered.pass.vcf.gz.tbi
.TNscope_umi.all.vcf.gz_summary.html
.TNscope_umi.all.stats
.tnhaplotyper.all.filtered.vcf.gz, 
.tnhaplotyper.all.filtered.vcf.gz.tbi
.tnhaplotyper.all.filtered.pass.vcf.gz,
.tnhaplotyper.all.filtered.pass.vcf.gz.tbi
.tnhaplotyper.all.vcf.gz_summary.html
.tnhaplotyper.all.stats
```
#### Somatic-callers SV
```
.delly.all.filtered.pass.vcf.gz
.delly.all.filtered.pass.vcf.gz.tbi
.delly.all.vcf.gz
.delly.all.vcf.gz.tbi
.delly.all.vcf.gz_summary.html
.delly.all.stats
.manta.all.filtered.pass.vcf.gz
.manta.all.filtered.pass.vcf.gz.tbi
.manta.all.vcf.gz
.manta.all.vcf.gz.tbi
manta.all.vcf.gz_summary.html
.manta.all.stats
```

#### Somatic-callers CNV
```
cnvkit.all.vcf.gz
cnvkit.all.vcf.gz.tbi
.cnvkit.all.filtered.pass.vcf.gz
.cnvkit.all.filtered.pass.vcf.gz.tbi
tumor.merged-scatter.pdf
tumor.merged-diagram.pdf
tumor.merged.cns
tumor.merged.cnr
gene_metrics
.gene_breaks
.cnvkit.all.vcf.gz_summary.html
.cnvkit.all.stats
```

### Germline callers

### SNV germline 
```
.haplotypecaller.vcf.gz
.haplotypecaller.vcf.gz.tbi
haplotypecaller.vcf.gz_summary.html
.germline.tumor.haplotypecaller.all.stats

.dnascope.vcf.gz
.dnascope.vcf.gz.tbi
.dnascope.vcf.gz_summary.html
.tumor.dnascope.all.stats
```

#### SV germline 
```
.manta_germline.vcf.gz
.manta_germline.vcf.gz.tbi
.manta_germline.vcf.gz_summary.html
.manta_germline.all.stats
```
@ivadym: These are required panel outputs for storing in hk. I will update for WGS cases in a while.

**Comment by ashwini06** [comment]
WGS cases:

`QC and reports` and `Raw data files and Aligned files` remain the same as the panel cases.


**Variant-called vcf files**

#### Somatic SNV

```
tnscope.all.vcf.gz",
.tnscope.all.vcf.gz.tbi",
.tnscope.all.vcf.gz_summary.html",
.tnscope.all.filtered.vcf.gz",
.tnscope.all.filtered.vcf.gz.tbi",
.tnscope.all.filtered.pass.vcf.gz",
.tnscope.all.filtered.pass.vcf.gz.tbi",
.tnhaplotyper.all.vcf.gz",
.tnhaplotyper.all.vcf.gz.tbi",
.tnhaplotyper.all.vcf.gz_summary.html",
.tnhaplotyper.all.filtered.vcf.gz",
.tnhaplotyper.all.filtered.vcf.gz.tbi",
.tnhaplotyper.all.filtered.pass.vcf.gz",
.tnhaplotyper.all.filtered.pass.vcf.gz.tbi",

```

### Somatic SV

```
.manta.all.vcf.gz",
.manta.all.vcf.gz.tbi",.
.manta.all.vcf.gz_summary.html"
.manta.all.filtered.pass.vcf.gz",
.manta.all.filtered.pass.vcf.gz.tbi",
.delly.all.vcf.gz",
.delly.all.vcf.gz.tbi",
.delly.all.vcf.gz_summary.html",
.delly.all.filtered.pass.vcf.gz",
.delly.all.filtered.pass.vcf.gz.tbi"
```


### Somatic CNVs

```
.ascat.all.vcf.gz",
.ascat.all.vcf.gz.tbi",
.ascat.all.vcf.gz_summary.html",
.ascat.all.filtered.pass.vcf.gz",
.ascat.all.filtered.pass.vcf.gz.tbi",
```
  
 ### Germline SV
```
.normal.manta_germline.vcf.gz",
.normal.manta_germline.vcf.gz.tbi",
.tumor.manta_germline.vcf.gz",
.tumor.manta_germline.vcf.gz.tbi",  
.normal.manta_germline.vcf.gz_summary.html",
.tumor.manta_germline.vcf.gz_summary.html",
```

### Germline SNV
```
.normal.dnascope.vcf.gz",
.normal.dnascope.vcf.gz.tbi",
.tumor.dnascope.vcf.gz",
.tumor.dnascope.vcf.gz.tbi",    
.normal.dnascope.vcf.gz_summary.html",
.tumor.dnascope.vcf.gz_summary.html"
```

also  include: 
```
*.all.stats
*__summary.html

```
## Additional new WGS plots to include
```
/home/proj/stage/cancer/cases/$wgs_caseid/analysis/vcf/*.ascat.ascatprofile.png
/home/proj/stage/cancer/cases/$wgs_caseid/analysis/vcf/*.ascat.ASPCF.png
/home/proj/stage/cancer/cases/$wgs_caseid/analysis/vcf/*.ascat.germline.png
/home/proj/stage/cancer/cases/$wgs_caseid/analysis/vcf/*.ascat.rawprofile.png
/home/proj/stage/cancer/cases/$wgs_caseid/analysis/vcf/*.ascat.sunrise.png
/home/proj/stage/cancer/cases/$wgs_caseid/analysis/vcf/*..ascat.tumor.png
/home/proj/stage/cancer/cases/$wgs_caseid/analysis/vcf/*.ascat.samplestatistics.txt
```

@khurrammaqbool : Can you please check the above list of  WGS deliverables and remove the files you think are not necessary.

**Comment by khurrammaqbool** [comment]
@ashwini06 we are delivering files mainly from vep folder. I suggest we should include files before vep from vcf folder as well. Those are unfiltered and may be requested to be looked into for variants missing in filtered, vep annotated outputs.
