### ISSUE TITLE
Improve CNV calling for followup samples by reducing noise

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#832]
**Is your feature request related to a problem? Please describe.**
CNVKit's analysis is pretty accurate for high tumor %, but working with the output data reveals it can be inaccurate on calling in followup samples. Of course this can happen due to variation in data quality, and/or input material's quality.

In figure below, coverage for these two samples are same. Quality of samples are fairly equal, but intensity of loss/gain is different. This could either be explained by biological dif
![image](https://user-images.githubusercontent.com/1086877/145047340-7a62d822-ea51-430f-a5cb-43e529874314.png)

**Describe the solution you'd like**
Investigate parameters in CNVKit to find out what's causing this.

**Describe alternatives you've considered**
None yet.

**Additional context**
None yet.

**Expected output for the feature**
Same verified CNV calling process to output similar magnitude of CNV calls.

**Current BALSAMIC version**
`balsamic 8.2.0`

**Comment by ashwini06** [comment]
Can this be due to the variability of tumor cell fractions in the two samples?

**Comment by hassanfa** [comment]
They actually have a very similar tumor cell fraction, and the CNV calls should not change. This issue can be closed if such artifact can't be seen in any other sample(s) or followup sample(s).

**Comment by pbiology** [comment]
Refinement in 2022-12-13:
- Need to see if this problem is still in latest version of CNV kit

**Comment by khurrammaqbool** [comment]
I am not sure if this could be solved by adding PON to the analysis. We are in a process of improving cnvkit and other variant calling methods by adding PON. The problem was not reported in any other sample so we may take up the investigation after observing this in sufficient number of samples to be able to investigate and fix the issue.
