### ISSUE TITLE
Dynamic CADD calculation for INDELs

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#834]
**Is your feature request related to a problem? Please describe.**
More about CADD scores https://cadd.gs.washington.edu/

**Describe the solution you'd like**
 - [ ] INDELs annotated with CADD scores as part of BALSAMIC
- [ ] CADD scores for INDELs visualized in Scout

**Comment by ashwini06** [comment]
MIP dockerfile: https://github.com/Clinical-Genomics/MIP/blob/fd1df22d5a4b40fd6fc16a5987fb5f92dc127c51/containers/cadd/Dockerfile

**Comment by pbiology** [comment]
Part of https://github.com/Clinical-Genomics/project-planning/issues/342

**Comment by pbiology** [comment]
This is now added as a new feature issue (#1106) planned for BALSAMIC v12.
Closing this issue and tracking in the feature.
