### ISSUE TITLE
Inconsistent BALSAMIC tag generation

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#848]
The tags should be consistent between CG, Housekeeper and BALSAMIC.

<details>
<summary>OUTDATED</summary>
The tag assignment for some `ascat` (TN_WGS), `delly`, `manta`, `TNscope_umi` (PANEL), `tnhaplotyper` files is inconsistent:

- [x] `delly` and `manta` filtered vcfs have different tags depending on the sequencing type. For PANEL analysis there is and additional `sv` field.

> `delly` tags for `SV.somatic.<case_id>.delly.all.filtered.pass.vcf.gz` file are different for WGS(`{"research-vcf-sv-pass", "vcf-sv-pass"}`) and PANEL (`{"research-vcf-sv-pass", "sv", "vcf-sv-pass"}`).
> 
> `manta` tags for the `SV.somatic.<case_id>.manta.all.filtered.pass.vcf.gz` file are different for WGS (`{"vcf-sv-pass", "clinical-vcf-sv-pass"}`) and PANEL (`{"vcf-sv-pass", "sv", "clinical-vcf-sv-pass"}`).

- [x] BALSAMIC generates the same tags for `ascat` and `delly` filtered vcfs.

> The `CNV.somatic.<case_id>.[ascat/delly].all.filtered.pass.vcf.gz` file has the same tags for both cases: `{"research-vcf-sv-pass", "vcf-sv-pass"}`.

- [x] `TNscope_umi` and `tnhaplotyper` filtered files (`*.all.filtered` and `*.all.filtered.pass`) have the same tags.

> They share the following BALSAMIC tags: `["research-vcf-filtered", "vcf-filtered", "snv"]` and `["research-vcf-pass", "vcf-pass", "snv"]`.
</details>

**Comment by ashwini06** [comment]
@ivadym : I think it's good to stick with one format for tags, either 2 or 3 columns.

**Comment by ashwini06** [comment]
Fixed!
