### ISSUE TITLE
CNVkit misses monosomy 7 in 100% of the cells

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#852]
**Problem:**
 Issue reported from one of the balsamic customers:

Case_name: setperch
For instance, in F0041870 we expect to find monosomy 7, present in 100% of the cells.
However, cnvkit generates no such call, not a single CNV on chr7.
We notice however that the log ratios of 7 are low, and that chromosome 7 is highlighted in blue in the pdf.

Can you confirm? how is this data filtered? How come the variant is clear in the pdf, but not present in vcf?

**BALSAMIC version**
`balsamic 7.2.5`

**Investigation**
CNVkit has correctly reported this missing monosomy 7 in `/home/proj/production/cancer/cases/setperch/analysis/cnv/tumor.merged.vcf.gz`. However vep results have filtered out this cnv `/home/proj/production/cancer/cases/setperch/analysis/vep/CNV.somatic.setperch.cnvkit.all.vcf.gz`

**Solution:**
This could be due to single large monosomy and vep have filtered due to max_sv_limit size settings. 
Right now, in BALSAMIC we don't have settings for this parameter, set this size to the largest chromosome size (chr1) in order to capture such monosomies in the future.

**Comment by pbiology** [comment]
Refinement in 2022-12-13:
- This should perhaps be a deviation and investigated there. Any fixes for BALSAMIC should be in this repo then

**Comment by mathiasbio** [comment]
We need to verify if this is solved in current version of production since the updated max size setting, and add it to validation cases.

**Comment by khurrammaqbool** [comment]
The analysis using current develop branch identifies monosomy 7.
