### ISSUE TITLE
vep requires runtime optimization

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#857]
**Describe the bug**
`vep` currently occupies whole node and uses fraction of it.  

**To Reproduce**

**Expected behavior**

**If workflow, which rules**
`vep_somatic`
`vep_germline`

**Screenshots**

**Version (please complete the following information):**
`balsamic, version 8.2.5` 

**Additional context**

**Comment by khurrammaqbool** [comment]
`BALSAMIC v8.2.5` uses the following parameters for `vep`:

` --compress_output bgzip --vcf --everything --hgvsg --allow_non_variant --dont_skip --buffer_size 20000 --format vcf --offline --variant_class --merged --cache --verbose --force_overwrite"`

`ensembl-vep` suggests the following relevant points for [getting VEP to run faster](<https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster>) :

- Make sure you have the [latest version](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#download) of VEP and the Ensembl API. We regularly introduce optimisations, alongside the new features and bug fixes of a typical new release.
  - `BALSAMIC v8.2.5` installs `ensembl-vep=100.2`

- Download a [FASTA file](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta) (and use the flag [--fasta](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fasta)) if you use [--hgvs](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_hgvs) or [--check_ref](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_check_ref). Again, this will prevent VEP accessing the database unnecessarily (in this case to retrieve genomic sequence).
  - This is could be enabled
- Install the [Set::IntervalTree](http://search.cpan.org/~benbooth/Set-IntervalTree/lib/Set/IntervalTree.pm) Perl package. This package speeds up VEP's internals by changing how overlaps between variants and transcript components are calculated.
- Install the Ensembl::XS package. This contains compiled versions of certain key subroutines used in VEP that will run faster than the default native Perl equivalents. Using this should improve runtime by 5-10%. 
  - This could be checked/evaluated BALSAMIC is currently installing from bioconda default vep and no additional perl modules.
- Add the [--no_stats](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_no_stats) flag. Calculating summary statistics increases VEP runtime, so can be switched off if not required
- Using forking enables VEP to run multiple parallel "threads", with each thread processing a subset of your input. Most modern computers have more than one processor core, so running VEP with forking enabled can give huge speed increases (3-4x faster in most cases). Even computers with a single core will see speed benefits due to overheads associated with using object-oriented code in Perl. 
- buffer size is 20000 in `BALSAMIC v8.2.5`. 

--buffer_size [number] |   | Sets the internal buffer size, corresponding to the number of         variants that are read in to memory simultaneously. Set this         lower to use less memory at the expense of longer run time, and         higher to use more memory with a faster run time. Default =         5000
-- | -- | --

**Comment by khurrammaqbool** [comment]
JobName|State|Timelimit|Elapsed|ReqMem|MaxRSS|MaxVMSize|NCPUS|
|-|-|-|-|-|-|-|-|
|TN.fastp_umi.7.sh|COMPLETED|12:00:00|02:05:26|5222Mc|||8|
|batch|COMPLETED||02:05:26|5222Mc|2645884|4556904|8|
|TN.fastp_umi.13.sh|COMPLETED|12:00:00|01:00:46|5222Mc|||8|
|batch|COMPLETED||01:00:46|5222Mc|2058480|3685684|8|
|TN.fastqc.14.sh|COMPLETED|12:00:00|01:52:07|5222Mc|||8|
|batch|COMPLETED||01:52:07|5222Mc|403704|4093240|8|
|TN.fastqc.15.sh|COMPLETED|12:00:00|03:18:23|5222Mc|||8|
|batch|COMPLETED||03:18:23|5222Mc|401816|4025884|8|
|TN.fastp.12.sh|COMPLETED|12:00:00|01:01:32|5222Mc|||8|
|batch|COMPLETED||01:01:32|5222Mc|737992|2806916|8|
|TN.fastp.6.sh|COMPLETED|12:00:00|02:00:54|5222Mc|||8|
|batch|COMPLETED||02:00:54|5222Mc|743800|2874244|8|
|TN.sentieon_align_sort.5.sh|COMPLETED|1-00:00:00|03:21:51|5222Mc|||24|
|batch|COMPLETED||03:21:51|5222Mc|24415264|29696732|24|
|TN.sentieon_align_sort.11.sh|COMPLETED|1-00:00:00|01:51:34|5222Mc|||24|
|batch|COMPLETED||01:51:34|5222Mc|24562900|29919228|24|
|TN.sentieon_dedup.4.sh|COMPLETED|1-00:00:00|00:27:03|5222Mc|||24|
|batch|COMPLETED||00:27:03|5222Mc|7196520|9603832|24|
|TN.sentieon_dedup.10.sh|COMPLETED|1-00:00:00|00:17:27|5222Mc|||24|
|batch|COMPLETED||00:17:27|5222Mc|4971680|7513520|24|
|TN.sentieon_wgs_metrics.20.sh|COMPLETED|12:00:00|00:39:54|5222Mc|||8|
|batch|COMPLETED||00:39:54|5222Mc|1049488|4579252|8|
|TN.sentieon_realign.9.sh|COMPLETED|1-00:00:00|00:15:46|5222Mc|||24|
|batch|COMPLETED||00:15:46|5222Mc|4599632|7583968|24|
|TN.picard_CollectWgsMetrics.17.sh|COMPLETED|12:00:00|03:54:49|5222Mc|||8|
|batch|COMPLETED||03:54:49|5222Mc|7165328|21523136|8|
|TN.picard_CollectMultipleMetrics.19.sh|COMPLETED|12:00:00|03:00:45|5222Mc|||8|
|batch|COMPLETED||03:00:45|5222Mc|3822120|21647268|8|
|TN.sentieon_wgs_metrics.21.sh|COMPLETED|12:00:00|00:57:43|5222Mc|||8|
|batch|COMPLETED||00:57:43|5222Mc|1437176|7645340|8|
|TN.sentieon_realign.3.sh|COMPLETED|1-00:00:00|00:31:14|5222Mc|||24|
|batch|COMPLETED||00:31:14|5222Mc|5972948|8763644|24|
|TN.picard_CollectWgsMetrics.16.sh|COMPLETED|12:00:00|01:54:21|5222Mc|||8|
|batch|COMPLETED||01:54:21|5222Mc|6390424|21515224|8|
|TN.picard_CollectMultipleMetrics.18.sh|COMPLETED|12:00:00|01:30:04|5222Mc|||8|
|batch|COMPLETED||01:30:04|5222Mc|5439916|21514788|8|
|TN.mergeBam_tumor.2.sh|COMPLETED|10:00:00|03:29:10|5222Mc|||16|
|batch|COMPLETED||03:29:10|5222Mc|1126824|7443648|16|
|TN.mergeBam_normal.8.sh|COMPLETED|10:00:00|01:56:01|5222Mc|||16|
|batch|COMPLETED||01:56:01|5222Mc|1102124|7377252|16|
|TN.sentieon_base_calibration.22.sh|COMPLETED|1-00:00:00|00:51:14|5222Mc|||24|
|batch|COMPLETED||00:51:14|5222Mc|2312204|5507144|24|
|TN.sentieon_base_calibration.23.sh|COMPLETED|1-00:00:00|00:28:16|5222Mc|||24|
|batch|COMPLETED||00:28:16|5222Mc|1791308|4918980|24|
|TN.manta_germline.29.sh|COMPLETED|05:00:00|00:32:41|5222Mc|||16|
|batch|COMPLETED||00:32:41|5222Mc|1964248|5586928|16|
|TN.manta_germline.31.sh|COMPLETED|05:00:00|00:17:26|5222Mc|||16|
|batch|COMPLETED||00:17:26|5222Mc|1842492|5462384|16|
|TN.delly_tumor_normal.42.sh|COMPLETED|08:00:00|03:58:41|5222Mc|||36|
|batch|COMPLETED||03:58:41|5222Mc|8397568|10620608|36|
|TN.ascat_tumor_normal.44.sh|COMPLETED|08:00:00|00:15:24|5222Mc|||36|
|batch|COMPLETED||00:15:24|5222Mc|4338744|8501556|36|
|TN.manta_tumor_normal.39.sh|COMPLETED|10:00:00|00:48:31|5222Mc|||12|
|batch|COMPLETED||00:48:31|5222Mc|2541092|5494992|12|
|TN.sentieon_TNscope.34.sh|COMPLETED|1-00:00:00|00:59:10|5222Mc|||24|
|batch|COMPLETED||00:59:10|5222Mc|7192216|11078188|24|
|TN.sentieon_TN_corealign.37.sh|COMPLETED|1-00:00:00|01:12:34|5222Mc|||24|
|batch|COMPLETED||01:12:34|5222Mc|11542620|14540152|24|
|TN.sentieon_DNAscope.25.sh|COMPLETED|1-00:00:00|00:51:58|5222Mc|||24|
|batch|COMPLETED||00:51:58|5222Mc|9088316|11596076|24|
|TN.sentieon_DNAscope.27.sh|COMPLETED|1-00:00:00|00:28:11|5222Mc|||24|
|batch|COMPLETED||00:28:11|5222Mc|6217916|8554412|24|
|TN.ascat_tumor_normal_merge_output.52.sh|COMPLETED|00:15:00|00:00:19|5222Mc|||1|
|batch|COMPLETED||00:00:19|5222Mc|||1|
|TN.vep_somatic.38.sh|COMPLETED|1-00:00:00|00:25:06|5222Mc|||12|
|batch|COMPLETED||00:25:06|5222Mc|14491572|16980368|12|
|TN.bcftools_bcf2vcf_delly.41.sh|COMPLETED|12:00:00|00:00:19|5222Mc|||8|
|batch|COMPLETED||00:00:19|5222Mc|||8|
|TN.multiqc.1.sh|COMPLETED|00:15:00|00:00:36|5222Mc|||4|
|batch|COMPLETED||00:00:36|5222Mc|179952|1890688|4|
|TN.vep_germline.28.sh|COMPLETED|1-00:00:00|00:02:58|5222Mc|||12|
|batch|COMPLETED||00:02:58|5222Mc|3335212|4991052|12|
|TN.vep_germline.30.sh|COMPLETED|1-00:00:00|00:00:00|5222Mc|||12|
|batch|COMPLETED||00:00:00|5222Mc|4061568|5882668|12|
|TN.vep_somatic.43.sh|COMPLETED|1-00:00:00|00:00:00|5222Mc|||12|
|batch|COMPLETED||00:00:00|5222Mc|32952668|35430928|12|
|TN.sentieon_TNhaplotyper.36.sh|COMPLETED|1-00:00:00|02:28:01|5222Mc|||24|
|batch|COMPLETED||02:28:01|5222Mc|6839188|8987540|24|
|TN.bcftools_filter_ascat.51.sh|COMPLETED|12:00:00|00:00:18|5222Mc|||8|
|batch|COMPLETED||00:00:18|5222Mc|||8|
|TN.vep_somatic.40.sh|COMPLETED|1-00:00:00|00:00:00|5222Mc|||12|
|batch|COMPLETED||00:00:00|5222Mc|10888788|13375804|12|
|TN.bcftools_view_split_variant.33.sh|COMPLETED|12:00:00|00:00:23|5222Mc|||8|
|batch|COMPLETED||00:00:23|5222Mc|||8|
|TN.bcftools_filter_manta.49.sh|COMPLETED|12:00:00|00:00:22|5222Mc|||8|
|batch|COMPLETED||00:00:22|5222Mc|||8|
|TN.vep_germline.24.sh|COMPLETED|1-00:00:00|00:00:00|5222Mc|||12|
|batch|COMPLETED||00:00:00|5222Mc|11619348|14318604|12|
|TN.vep_germline.26.sh|COMPLETED|1-00:00:00|01:07:32|5222Mc|||12|
|batch|COMPLETED||01:07:32|5222Mc|11653536|14422728|12|
|TN.vep_somatic.35.sh|COMPLETED|1-00:00:00|02:42:40|5222Mc|||12|
|batch|COMPLETED||02:42:40|5222Mc|6185284|8527840|12|
|TN.vep_somatic.32.sh|COMPLETED|1-00:00:00|03:00:07|5222Mc|||12|
|batch|COMPLETED||03:00:07|5222Mc|7643596|10001020|12|
|TN.bcftools_filter_delly.50.sh|COMPLETED|12:00:00|00:00:20|5222Mc|||8|
|batch|COMPLETED||00:00:20|5222Mc|||8|
|TN.tmb_calculation.45.sh|COMPLETED|12:00:00|00:00:36|5222Mc|||8|
|batch|COMPLETED||00:00:36|5222Mc|161660|2151700|8|
|TN.tmb_calculation.46.sh|COMPLETED|12:00:00|00:00:32|5222Mc|||8|
|batch|COMPLETED||00:00:32|5222Mc|||8|
|TN.bcftools_filter_tnscope_tumor_normal.47.sh|COMPLETED|12:00:00|00:00:33|5222Mc|||8|
|batch|COMPLETED||00:00:33|5222Mc|140644|1813584|8|
|TN.bcftools_filter_tnhaplotyper_tumor_normal.48.sh|COMPLETED|12:00:00|00:00:20|5222Mc|||8|
|batch|COMPLETED||00:00:20|5222Mc|||8|
|TN.all.0.sh|COMPLETED|00:15:00|00:00:19|5222Mc|||1|
|batch|COMPLETED||00:00:19|5222Mc|||1|
|TO.fastqc.8.sh|COMPLETED|12:00:00|03:35:43|5222Mc|||8|
|batch|COMPLETED||03:35:43|5222Mc|401784|4025840|8|
|TO.fastp_umi.7.sh|COMPLETED|12:00:00|02:07:41|5222Mc|||8|
|batch|COMPLETED||02:07:41|5222Mc|2608972|4427452|8|
|TO.fastp.6.sh|COMPLETED|12:00:00|02:01:59|5222Mc|||8|
|batch|COMPLETED||02:01:59|5222Mc|816488|2874200|8|
|TO.sentieon_align_sort.5.sh|COMPLETED|1-00:00:00|03:09:48|5222Mc|||24|
|batch|COMPLETED||03:09:48|5222Mc|24318408|29900368|24|
|TO.sentieon_dedup.4.sh|COMPLETED|1-00:00:00|00:28:42|5222Mc|||24|
|batch|COMPLETED||00:28:42|5222Mc|8011748|10750624|24|
|TO.sentieon_realign.3.sh|COMPLETED|1-00:00:00|00:30:31|5222Mc|||24|
|batch|COMPLETED||00:30:31|5222Mc|4711848|7584060|24|
|TO.picard_CollectMultipleMetrics.10.sh|COMPLETED|12:00:00|02:48:38|5222Mc|||8|
|batch|COMPLETED||02:48:38|5222Mc|4118232|21645560|8|
|TO.sentieon_wgs_metrics.11.sh|COMPLETED|12:00:00|00:47:07|5222Mc|||8|
|batch|COMPLETED||00:47:07|5222Mc|1186388|4709980|8|
|TO.picard_CollectWgsMetrics.9.sh|COMPLETED|12:00:00|03:31:30|5222Mc|||8|
|batch|COMPLETED||03:31:30|5222Mc|8167544|21513188|8|
|TO.mergeBam_tumor.2.sh|COMPLETED|10:00:00|03:46:46|5222Mc|||16|
|batch|COMPLETED||03:46:46|5222Mc|1093748|7443604|16|
|TO.manta_germline.16.sh|COMPLETED|05:00:00|00:32:30|5222Mc|||16|
|batch|COMPLETED||00:32:30|5222Mc|1885060|5609296|16|
|TO.delly_tumor_only.24.sh|COMPLETED|08:00:00|02:20:14|5222Mc|||36|
|batch|COMPLETED||02:20:14|5222Mc|8333632|10554376|36|
|TO.sentieon_base_calibration.12.sh|COMPLETED|1-00:00:00|00:53:40|5222Mc|||24|
|batch|COMPLETED||00:53:40|5222Mc|2896744|5966532|24|
|TO.manta_tumor_only.26.sh|COMPLETED|10:00:00|00:32:27|5222Mc|||12|
|batch|COMPLETED||00:32:27|5222Mc|1519756|4618660|12|
|TO.vep_germline.15.sh|COMPLETED|1-00:00:00|00:00:00|5222Mc|||12|
|batch|COMPLETED||00:00:00|5222Mc|4433044|6255120|12|
|TO.sentieon_DNAscope.14.sh|COMPLETED|1-00:00:00|00:56:03|5222Mc|||24|
|batch|COMPLETED||00:56:03|5222Mc|9220232|11472160|24|
|TO.sentieon_TNscope_tumor_only.19.sh|COMPLETED|1-00:00:00|02:22:05|5222Mc|||24|
|batch|COMPLETED||02:22:05|5222Mc|8057572|11272420|24|
|TO.multiqc.1.sh|COMPLETED|00:15:00|00:00:29|5222Mc|||4|
|batch|COMPLETED||00:00:29|5222Mc|||4|
|TO.sentieon_TNhaplotyper_tumor_only.21.sh|COMPLETED|1-00:00:00|02:27:22|5222Mc|||24|
|batch|COMPLETED||02:27:22|5222Mc|5691568|7974260|24|
|TO.bcftools_bcf2vcf_delly.23.sh|COMPLETED|12:00:00|00:00:18|5222Mc|||8|
|batch|COMPLETED||00:00:18|5222Mc|||8|
|TO.vep_somatic.25.sh|COMPLETED|1-00:00:00|10:51:53|5222Mc|||12|
|batch|COMPLETED||10:51:53|5222Mc|33297688|35774800|12|
|TO.bcftools_view_split_variant.18.sh|COMPLETED|12:00:00|00:01:35|5222Mc|||8|
|batch|COMPLETED||00:01:35|5222Mc|145864|1745948|8|
|TO.vep_somatic.20.sh|COMPLETED|1-00:00:00|04:44:34|5222Mc|||12|
|batch|COMPLETED||04:44:34|5222Mc|12516524|15391432|12|
|TO.vep_somatic.22.sh|COMPLETED|1-00:00:00|17:50:40|5222Mc|||12|
|batch|COMPLETED||17:50:40|5222Mc|33199144|35611340|12|
|TO.bcftools_filter_manta.33.sh|COMPLETED|12:00:00|00:00:23|5222Mc|||8|
|batch|COMPLETED||00:00:23|5222Mc|||8|
|TO.vep_germline.13.sh|COMPLETED|1-00:00:00|00:00:00|5222Mc|||12|
|batch|COMPLETED||00:00:00|5222Mc|11299044|13914376|12|
|TO.bcftools_filter_delly.32.sh|COMPLETED|12:00:00|00:00:23|5222Mc|||8|
|batch|COMPLETED||00:00:23|5222Mc|||8|
|TO.bcftools_filter_tnhaplotyper_tumor_only.31.sh|COMPLETED|12:00:00|00:01:37|5222Mc|||8|
|batch|COMPLETED||00:01:37|5222Mc|221244|5123240|8|
|TO.vep_somatic.17.sh|COMPLETED|1-00:00:00|04:23:59|5222Mc|||12|
|batch|COMPLETED||04:23:59|5222Mc|11385248|13979264|12|
|TO.tmb_calculation.28.sh|COMPLETED|12:00:00|00:23:38|5222Mc|||8|
|batch|COMPLETED||00:23:38|5222Mc|209836|2244152|8|
|TO.bcftools_filter_tnscope_tumor_only.30.sh|COMPLETED|12:00:00|00:02:30|5222Mc|||8|
|batch|COMPLETED||00:02:30|5222Mc|230004|5450252|8|
|TO.tmb_calculation.27.sh|COMPLETED|12:00:00|00:39:33|5222Mc|||8|
|batch|COMPLETED||00:39:33|5222Mc|203924|2177604|8|
|TO.bcftools_intersect_tumor_only.29.sh|COMPLETED|12:00:00|00:00:00|5222Mc|||8|
|batch|COMPLETED||00:00:00|5222Mc|208864|1813456|8|
|TO.all.0.sh|COMPLETED|00:15:00|00:00:16|5222Mc|||1|
|batch|COMPLETED||00:00:16|5222Mc|||1|

**Comment by khurrammaqbool** [comment]
# `vep` `--fork` and `--buffer_size` optimization:

## Tumor only vep_somatic delly 


fork/CPU=24 buffer=30000
real    4m57.596s
user    16m40.556s
sys     1m23.412s

fork/CPU=36 buffer=20000
real    5m0.409s
user    16m42.957s
sys     1m23.999s

fork=72 buffer=100000
real    5m2.546s
user    17m6.713s
sys     1m31.122s

fork=18 buffer=40000
real    6m2.459s
user    16m41.855s
sys     1m23.239s


## Tumor only vep_somatic tnscope

fork/CPU=36 buffer_size 100000
real    36m22.150s
user    636m5.952s
sys     184m45.478s


fork/CPU=36 buffer=30000
real    38m48.958s
user    705m51.602s
sys     121m28.918s


fork/CPU=36 buffer=30000
real    39m3.529s
user    708m34.971s
sys     124m14.178s


fork/CPU=18 buffer=40000
real    41m14.086s
user    506m11.754s
sys     69m6.543s

**Comment by khurrammaqbool** [comment]
# vcfanno
[vcfanno](http://brentp.github.io/vcfanno/) is included in `vep_somatic` rule. In `BALSAMIC v8.2.5`, threading for vcfanno is not activated. vcfanno suggests [performance tips](http://brentp.github.io/vcfanno/performance_tips/). 
- GOGC can allow go to use more memory
- CSI index for vcf files and optimizing for Max Gap / Chunk Size

## vcfanno: Tumor normal, tnhaplotyper.vcf.gz

threads=default GOGC=default
real    153m33.284s
user    287m10.085s
sys     8m52.777s

threads=18 GOGC=default
real    54m12.220s
user    396m51.329s
sys     17m23.002s

threads=18 GOGC=1000
real    46m7.699s
user    330m42.042s
sys     19m0.135s

threads=18 GOGC=10000
real    43m2.190s
user    306m8.485s
sys     20m23.349s

threads=18 GOGC=60000
real    48m49.135s
user    314m45.809s
sys     28m59.214s

threads=36 GOGC=60000
real    40m53.818s
user    326m7.671s
sys     31m41.901s

**Comment by henrikstranneheim** [comment]
Nice! 18 threads and GOGC=10000 seems like a good balance

**Comment by khurrammaqbool** [comment]
> Nice! 18 threads and GOGC=10000 seems like a good balance





Although, it works well for SNVs, but fails for SVs. Until we implement annotSV, for SVs, GOGC should be reduced.

## vcfanno: Tumor only, delly

threads=18 GOGC=10000
Failed

threads=18 GOGC=1000
real    190m23.375s
user    640m15.084s
sys     89m34.425s
but consumes large amount of memory >164G
