### ISSUE TITLE
vcf2cytosure

### ISSUE THREAD

**Issue by AleksandraKrstic** [Clinical-Genomics/BALSAMIC#858]
Hi,
We would like to get vcf2cytosure in balsamic in order to see large CNVs based on the panel backbone. 
Tips from Jesper: 
 vcf2cytosure works well with cnvkit output!
I run it like this:
vcf2cytosure --vcf CNV.somatic.setperch.cnvkit.vcf.gz --cn 740694/F0041870/tumor.merged.cnr --bins 1
where --vcf is the cnvkit annotated vcf, and cnr is cnvkit cnr file

Thanks, Aleksandra

**Comment by ashwini06** [comment]
This is now fixed for panel cases in PR #880, From BALSAMIC release v9.0, for all panel cases .CGH will be generated.
