### ISSUE TITLE
Problems with balsamic container generation

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#860]
Sometimes generating the balsamic container via git actions fails due to python dependency issues. For eg: https://github.com/Clinical-Genomics/BALSAMIC/runs/5095568999?check_suite_focus=true

One needs to figure out every single time, the required system dependencies and runtime unexpected bugs. 

Currently, we have `miniconda3:4.9.2-alpine` as the base image for docker and alpine might be the culprit for this issue. Check/update to other supporting base images to resolve this issue.

**Comment by ivadym** [comment]
Closing this issue as there is another that already addresses this topic (#791 ). I've also included this comment in that thread.
