### ISSUE TITLE
[ Failed Analysis ]

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/BALSAMIC#861]
**Case or sample information**
Internal sample id or case id: toughcondor, honestpoodle, mainrat 
Amount read-pairs: 1200Mrp target reads
Sequence type (WES, TGA, WGS): WGS

**Error message**

```Shell
.....
Approx 80% complete for concatenated_ACC9328A5_XXXXXX_R_2.fastq.gz
Approx 85% complete for concatenated_ACC9328A5_XXXXXX_R_2.fastq.gz
slurmstepd: error: *** JOB 2519864 ON gpu-compute-0-1 CANCELLED AT 2022-02-07T22:50:01 DUE TO TIME LIMIT ***
Will exit after finishing currently running jobs.
[Mon Feb  7 22:50:02 2022]
.....
```

**Link to the error message**

Multiple arror logs

**Reason for failure**

Similar reason, large amounts of data extends the fastq step.

**If workflow, which rules**
If possible, and using the Snakemake workflows, the name of the affected rules and workflows.

fastgc and multiqc affected

**Version (please complete the following information):**
`balsamic, version 8.2.5`

**Additional context**
Add any other context about the problem here. For e.g. amount sequencing reads or other parameters that are of interest.

All is well with the data, but time allocation is needed for these jobs. It seems to affect WGS mainly, perhaps only increase the amount of time allocated for those type of samples?

**Comment by ashwini06** [comment]
Currently, we have a common [fastqc rule](https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/snakemake_rules/quality_control/fastqc.rule#L7) for running the panel and WGS samples. This fastqc rule has an allocation of 8 cores and time limit of 12 hrs. If WGS cases are taking a long time to run, we can increase the time-limit settings for this rule to ~18 hrs, but then it's gonna be a common implementation i.e., for panel cases also time-limit set for 18 hrs, which means longer waiting times for the panel cases to start the fastqc jobs.


An alternative solution  to avoid panel jobs waiting for longer times (i.e. set time_limit for panels: 12 hrs) is to separate the rule names (fastqc_panel, fastqc_wgs). Redundancy of same code! 

It would be nice to have a framework that works fine with a single fastqc rule, and depending on sequencing_type, slurm resource allocation can be changed. Right now, with snakemake sbatch scheduler, the resource allocations are picked based on the rulename in [cluster.json](https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/config/cluster.json). So with same rule name, different resource allocation is not possible.

**Comment by henrikstranneheim** [comment]
I think the quick fix is just to increase the time for the rule

But it would be good in the long run to be able to be more dynamic in resource allocation and use less for panels and more for wgs.

**Comment by ashwini06** [comment]
Testing use of --threads in fastqc cmdline `fastqc --threads ....`. Following tests shows that no need to increase time allocation of fastqc runs, but we can parallelize fastqc jobs with adding --threads option to fastqc commandline

**Test1:** `fastqc ....` running with default 8 cores and 12 hrs time (Current BALSAMIC default)
start time: `[Wed Feb  9 22:54:17 2022]`
end time:
```
Approx 85% complete for concatenated_ACC9328A1_XXXXXX_R_2.fastq.gz
slurmstepd: error: *** JOB 2528704 ON compute-0-9 CANCELLED AT 2022-02-10T10:54:15 DUE TO TIME LIMIT ***
Will exit after finishing currently running jobs.
[Thu Feb 10 10:54:15 2022]
Error in rule fastqc:
```
Related log: /home/proj/stage/cancer/cases/toughcondor/logs.1/BALSAMIC.toughcondor.fastqc.15.sh_2528704.err

----------------
**Test2:** `fastqc .....` running with increased core allocation: n=12 cores

start time: `[Thu Feb 10 13:43:22 2022]`
end time: 
```
Started analysis of concatenated_ACC9328A1_XXXXXX_R_2.fastq.gz
Approx 5% complete for concatenated_ACC9328A1_XXXXXX_R_2.fastq.gz
slurmstepd: error: *** JOB 2529457 ON compute-0-22 CANCELLED AT 2022-02-10T22:34:57 ***
Will exit after finishing currently running jobs.
```
Related log: /home/proj/stage/cancer/cases/toughcondor/logs.2/BALSAMIC.toughcondor.fastqc.15.sh_2529457.err

------------------------

**Test3:** `fastqc --threads 10 ...` 
start time: `[Wed Feb  9 15:10:45 2022]`
end time: `[Wed Feb  9 22:41:42 2022]`  
Runtime: ~7.5 hrs
Related log: /home/proj/stage/cancer/cases/toughcondor/logs/BALSAMIC.toughcondor.fastqc.15.sh_2528036.err
 
--------------------

**Test4:** `fastqc --threads 12 ...` 
start time: `[Thu Feb 10 22:36:24 2022]`
end time: `[Fri Feb 11 06:02:06 2022]`  
Runtime: 7.5 hrs
Related log: /home/proj/stage/cancer/cases/toughcondor/logs/BALSAMIC.toughcondor.fastqc.15.sh_2528036.err
 
--------

**Comment by henrikstranneheim** [comment]
Looks promising! 👍 . Seems like you hit the roof - what about `--threads 5`
