### ISSUE TITLE
Log file for BALSAMIC

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/BALSAMIC#862]
**Is your feature request related to a problem? Please describe.**
Today we don't keep track of the input files in BALSAMIC. We need to have a log file where the input fastq files are stated.

**Describe the solution you'd like**
The goal is to have a log file for each case that is saved to housekeeper bundles. This would make it a lot easier to follow up analyses.

**Describe alternatives you've considered**
An alternative solution, while waiting for the case specific log file, could be to have a common log file for all BALSAMIC cases that are started. 

**Current BALSAMIC version**
8.2.5

**Comment by khurrammaqbool** [comment]
balsamic generates a log file BALSAMIC_run/.snakemake/log/*.snakemake.log, but do we need to store it in housekeeper everytime balsamic run on the case?

**Comment by vwirta** [comment]
Let's discuss this on next meeting. 
It would be nice to have a log file of each analysis that keeps track of what has been analysed and how.

**Comment by ivadym** [comment]
Closing!

Changes in develop are actually reflecting the request here since we've started to add a more detailed sample dictionary to the `config.json` file, including the linked fastq files (`{lane}_{date_str}_{flowcell}_{sample}_{index}_R_{read}.fastq.gz`). The `config.json` file is also saved in HK, so it would be possible to trace which files have been used for passed analyses.

```
"samples": [
        {
            "type": "tumor",
            "name": "ACC5821A7",
            "fastq_info": {
                "2_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R": {
                    "fwd": "/home/proj/stage/cancer/cases/fleetjay/fastq/2_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R_1.fastq.gz",
                    "rev": "/home/proj/stage/cancer/cases/fleetjay/fastq/2_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R_2.fastq.gz"
                },
                "4_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R": {
                    "fwd": "/home/proj/stage/cancer/cases/fleetjay/fastq/4_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R_1.fastq.gz",
                    "rev": "/home/proj/stage/cancer/cases/fleetjay/fastq/4_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R_2.fastq.gz"
                },
                "3_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R": {
                    "fwd": "/home/proj/stage/cancer/cases/fleetjay/fastq/3_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R_1.fastq.gz",
                    "rev": "/home/proj/stage/cancer/cases/fleetjay/fastq/3_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R_2.fastq.gz"
                },
                "2_171015_HKL7FDMXX_ACC5821A7_XXXXXX_R": {
                    "fwd": "/home/proj/stage/cancer/cases/fleetjay/fastq/2_171015_HKL7FDMXX_ACC5821A7_XXXXXX_R_1.fastq.gz",
                    "rev": "/home/proj/stage/cancer/cases/fleetjay/fastq/2_171015_HKL7FDMXX_ACC5821A7_XXXXXX_R_2.fastq.gz"
                },
                "1_171015_HKL7FDMXX_ACC5821A7_XXXXXX_R": {
                    "fwd": "/home/proj/stage/cancer/cases/fleetjay/fastq/1_171015_HKL7FDMXX_ACC5821A7_XXXXXX_R_1.fastq.gz",
                    "rev": "/home/proj/stage/cancer/cases/fleetjay/fastq/1_171015_HKL7FDMXX_ACC5821A7_XXXXXX_R_2.fastq.gz"
                },
                "1_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R": {
                    "fwd": "/home/proj/stage/cancer/cases/fleetjay/fastq/1_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R_1.fastq.gz",
                    "rev": "/home/proj/stage/cancer/cases/fleetjay/fastq/1_171015_HKWN2DSXX_ACC5821A7_XXXXXX_R_2.fastq.gz"
                }
            }
        },

```
And for version tracking, we already have an open feature request:

- https://github.com/Clinical-Genomics/BALSAMIC/issues/1138
