### ISSUE TITLE
Do we need clinical.delivery.cancer@scilifelab.se?

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/BALSAMIC#866]
A lot of emails are sent to clinical.delivery.cancer@scilifelab.se, we in prod bioinfo monitor the analyses in Trailblazer and not through these emails, so I would say that they are unnecessary for us. Do you, @ashwini06, @khurrammaqbool, @ivadym, follow these emails? Or should we remove this group? Or reduce the amount of emails sent through it?

**Comment by ashwini06** [comment]
@moahaegglund: I agree it's a lot of emails. I usually have a look at bridged emails of this group to get an idea, if many BALSAMIC cases are getting FAILED or working as smooth in production. 

BTW, if you don't wish to see each and every email from this group, you can change the subscription settings to either `Digest` or `Abridged`
<img width="1434" alt="Screenshot 2022-02-24 at 14 17 05" src="https://user-images.githubusercontent.com/6302819/155531151-62bd1fde-0688-4499-8e86-14ace2ce5efb.png">

**Comment by ashwini06** [comment]
Its redundant with Trailbrailzer. Lets remove this group. @keyvanelhami Can you please delete this google group `Clinical delivery for cancer samples at Clinical Genomics`?

**Comment by keyvanelhami** [comment]
The group is now deleted. Closing
