### ISSUE TITLE
No Balsamic plots in Vogue since june 2021

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/BALSAMIC#884]
Text from Maria:

Balsamic was removed from list of pipelines to upload to vogue, ever since Balsamic stopped producing a qcmetrics file compatible with upload to Vogue. The author and responsible for this upload and trending no longer works on Vogue and the fix to this is not planned in the near future

**Comment by ivadym** [comment]
Balsamic generates and stores in HK a multiQC json file and a metrics YAML file for each case, so I think this should be addressed on the Vogue and CG side.

**Comment by keyvanelhami** [comment]
@hassanfa Can you provide an update regarding why Vogue no longer is updating Balsamic results? What file is Maria referring to?

**Comment by hassanfa** [comment]
I have not seen Maria's comments/note. Where was it posted? Is that the one you quoted in the first comment?

Regardless of that, it is still possible to upload to Vogue. I don't if there is another private repository or not, but according to https://github.com/Clinical-Genomics/vogue/ No CLI changes has been implemented. That means, Vogue still accepts `multiqc.json` file from BALSAMIC which until the time I was at CG, it was stored in Housekeeper. And BALSAMIC still produces `multiqc.json`. `cg` needs to properly provide this to Vogue.

So all you need to do is to provide `multiqc.json` to Vogue and it'll work.

I remember vaguely Henrik had some sort of plan to not use multiqc.json, and replace multiqc.json with that. Which won't matter either, cause balsamic's multiqc.json is still compatible with Vogue.

Hope this helps.

**Comment by hassanfa** [comment]
@keyvanelhami forgot to tag you in the comment above.

**Comment by pbiology** [comment]
I think we can close this issue for now as vogue is on ice

**Comment by ivadym** [comment]
Yes,  https://github.com/Clinical-Genomics/vogue-ui, closing
