### ISSUE TITLE
redundant BALSAMIC files 

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#890]
Purpose of this files in BALSAMIC. I think, these files are no longer used, can we remove them safely? @hassanfa Can you comment on this?

https://github.com/Clinical-Genomics/BALSAMIC/tree/master/BALSAMIC/assets/sentieon_models

https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/config/MSK_impact.json

https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/config/MSK_impact_noStrelka.json

**Comment by hassanfa** [comment]
MSK impact files can be removed. But Sentieon models are in use for the ML model. I'd keep them.
