### ISSUE TITLE
Mutation tumor burden

### ISSUE THREAD

**Issue by terestahl** [Clinical-Genomics/BALSAMIC#894]
Hi 
I wonder if it will be possible to get a meassure of the mutational tumor burden in balsamic pipeline
It is very useful for specific diagnoses

thanks

Teresita

**Comment by ivadym** [comment]
Closing this issue as it is a duplicate of https://github.com/Clinical-Genomics/BALSAMIC/issues/912, which is an ongoing project.

@Clinical-Genomics/cancer-bioinfo
