### ISSUE TITLE
ASCAT additional files missing

### ISSUE THREAD

**Issue by terestahl** [Clinical-Genomics/BALSAMIC#897]
Hi

It is good that you have included ASCAT in balsamic, thanks! good improvement

But I wonder if it would be possible to include additional CNV tools.
CNVs are very important for pediatric cancer and sometimes I see discrepancies with the results produced by ascat and other tools, then it will be good not te depend on only one tool.
We are using ascat and control-freec, other people use canvas and there is new CNV pipeline from GATK if I am not wrong

But I wonder now if you could include more files in the delivery of ascat results
We get a pdf report, and a vcf file
But to investigate the results properly we will need the txt files with log ratio and BAF
These files ase called something like

XXX.BAF och XXX.BAF.PCFed.txt och XXX.LogR och XXX.LogR.PCFed.txt.

I have been in contact with Moa who informed me that these files are deleted when the pipeline is completed
I would need these files, I would appreciate if you start saving them

thanks

teresita

**Comment by khurrammaqbool** [comment]
A file is added that contains BAF and log ratio.

**Comment by terestahl** [comment]
OK tack så mycket!
What is the name of this file? Will be added for old cases or only the new ones ?
Thanks

teresita
