### ISSUE TITLE
stats files for end point VCFs

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#898]
**Is your feature request related to a problem? Please describe.**
`vep` rules generate stats for VCFs. The stats files should be removed from vep rule and added to the end point VCF files *.all.filtered.pass.vcf.gz. The stats files from end point VCFs can be used to add a check before automatic uploads.

**Describe the solution you'd like**
remove *_stats files from vep rules and add for each *.all.filtered.pass.vcf.gz 

**Expected output for the feature**
For each end point VCF file *.all.filtered.pass.stats file is generated.

**Current BALSAMIC version**
`balsamic, version 8.2.8`

**Comment by ashwini06** [comment]
As we discussed in the meeting today, we don't really need to generate bcftools stats file. If required bioinfo prod team can generate the stats file from the required vcf file (either from raw or final vcf file), based on customer requests in the future. 
But before we proceed further either to include or exclude from balsamic, lets's talk with prod-bioinfo if there is any purpose/necessity of this file

**Comment by khurrammaqbool** [comment]
> As we discussed in the meeting today, we don't really need to generate bcftools stats file. If required bioinfo prod team can generate the stats file from the required vcf file (either from raw or final vcf file), based on customer requests in the future. But before we proceed further either to include or exclude from balsamic, lets's talk with prod-bioinfo if there is any purpose/necessity of this file

@ashwini06 , I agree that we don't need the stats files from vep rules. I spoke to @karlnyr and he suggested that these files will be good to have to add some checks for automatic uploads. So I removed stats files from vep rules and added to the filtered.pass VCF files.

**Comment by ashwini06** [comment]
@karlnyr @khurrammaqbool :  These stats file (for eg: `/home/proj/stage/cancer/validation/20211125/sweetelf/analysis/vep/SNV.somatic.sweetelf.vardict.all.stats`) includes stats by non-reference allele frequency, quality, depth distrubution, subsitution changes.. something relevant to generate this kind of [plots](https://genomics.sschmeier.com/ngs-variantcalling/index.html#id7) to the customer. But so far, do we have any such requests from customers? We developers are not plotting and using those results.. @karlnyr @moahaegglund : Your feedback from prod bioinfo is important here :)  If these  `*.all.stats` are important then we need to store and deliver to the customer as well right? Right now we decided to remove this from the HK tag list here https://github.com/Clinical-Genomics/hermes/issues/44

**Comment by karlnyr** [comment]
As @khurrammaqbool mentioned, him and I discussed these files yesterday and I have never seen them requested by a customer. In the "normal" balsamic delivery we do not deliver them, and customers are able to run bcftools on the vcfs if such files are inquired. However, just as Khurram mentioned, the number of variants we upload to Scout is quite fragile - we do NOT want to upload 20k variants per case as the database will get clogged - and a even higher number like 300k might indicate on sample mixups. So, we could use said files to create a sanity check before upload, with a threshold that probably should be discovered but could primarily be set to 10k.

**Comment by keyvanelhami** [comment]
I agree with @karlnyr that customers never request this file and can run bcftools themself to generate it. 

For sample mix-up, this will be addressed in [this issue](https://github.com/Clinical-Genomics/project-planning/issues/375) where we will add NGScheckmate or Somalier?

How often do we have cases with 20K variants uploaded to Scout? And for what panels (or is it WGS)?

**Comment by ashwini06** [comment]
@khurrammaqbool: I spoke with @moahaegglund and it is good to have the information about the number of variants called for the final vcf before uploading to scout/caesar. @ivadym Can also automate this by adding this information of the number of variants called to the QC metrics and fail it if the number exceeds above >10-12K variants. `bcftools +counts` can serve our purpose in your [PR ](https://github.com/Clinical-Genomics/BALSAMIC/pull/899)
