### ISSUE TITLE
Sample names (LIMS_IDs) in bam/VCF headers

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#943]
Related to this issue https://github.com/Clinical-Genomics/BALSAMIC/issues/882

Currently, the headers in the bam file are renamed as `TUMOR` and `NORMAL`, where the output VCFs generated downstream also contain `TUMOR` and `NORMAL` in their VCF headers. To be compatible with other workflows in cg environment (for eg: genotype), it is recommended to have LIMS_IDs in the VCF headers https://github.com/Clinical-Genomics/BALSAMIC/issues/882#issuecomment-1135775596

**Solution**:
Rename the bam headers to LIMS_IDs 

**Possible Conflicts:**

<img width="932" alt="Screenshot 2022-05-30 at 14 01 10" src="https://user-images.githubusercontent.com/6302819/170998061-199961a0-6673-4d96-915d-1f0988dafcd0.png">

We have `TUMOR` and `NORMAL` used as values for `Sample_ids` keys in scout config. But this shouldn't cause any conflicts unless the sample_ids match with the  names in the bam headers

**Comment by ivadym** [comment]
I'm closing it by now @Clinical-Genomics/cancer-bioinfo since the original issue was solved. If an additional need arises, we should open a new issue.
