### ISSUE TITLE
Missing FOUND_IN (or SET) tags for (recent?) Balsamic runs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/BALSAMIC#944]
**BALSAMIC version**
9.0.1 (`goodmole`), 8.2.9 (`raredragon`) and 8.2.10 (`coolgannet`).

**Issue** 
FOUND_IN or SET INFO tags are required to annotate caller status for display in Scout variant view.

This is established by a couple of pipelines on the RD-side and was once active also for somatic, compare e.g. [Scout cancer demo file](https://github.com/Clinical-Genomics/scout/blob/main/scout/demo/cancer_test.vcf.gz):
```
... 
FOUND_IN=mutect|/data/AML_VALIDATION/vcf/myeloid/803-15.bwa_myeloid.paired.mutect.vep.vcf,freebayes|/data/AML_VALIDATION/vcf/myeloid/803-15.bwa_myeloid.paired.freebayes_myeloid.vep.vcf;
...
```
which then renders on the variant page (somewhat redundantly 😊) like e.g.
![Screenshot 2022-05-31 at 14 47 10](https://user-images.githubusercontent.com/758570/171176788-c4f1be9b-6774-4019-9748-d44928487d69.png)

This would be useful at least as a safeguard for checking variant origin in UMI cases (c.f. https://github.com/Clinical-Genomics/scout/issues/3368) and has been requested for somatic SVs (https://github.com/Clinical-Genomics/scout/issues/3346).

The SET nomenclature (from GATK merge) is also available as an alternative, but as we generally only load Pass quality variants, the FOUND_IN INFO tag is simpler and considered preferred.

Cheers!

**Comment by ashwini06** [comment]
Fixed in #948
