### ISSUE TITLE
GNOMAD_popmax in v9.0.1

### ISSUE THREAD

**Issue by AleksandraKrstic** [Clinical-Genomics/BALSAMIC#945]
At https://balsamic.readthedocs.io/en/latest/balsamic_filters.html says: Attention: BALSAMIC <= v8.2.10 uses GNOMAD_popmax <= 0.005. From Balsamic v9.0.0, this settings is changed to 0.02, to reduce the stringency.
We wonder what is correct for Balsamic v9.0.1  0.02 or 0.005? (See https://balsamic.readthedocs.io/en/latest/balsamic_methods.html)

**Comment by vwirta** [comment]
The 'Attention' text you quote is for the UMI workflow.

For the standard targeted panel sequencing, please see the VARDICT section. Here the filter settings are as follows: 'Attention: BALSAMIC <= v8.2.7 uses minimum AF 1% (0.01). From Balsamic v8.2.8, minimum VAF is changed to 0.7% (0.007)'
