### ISSUE TITLE
Plan for BALSAMIC v10.0

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#954]
BALSAMIC key features planned for the next relase( v10.0):
- [X] CNA for T/N WGS using Delly - KM (https://github.com/Clinical-Genomics/BALSAMIC/pull/947) 
          - Added: Delly CNV for tumor normal analysis
          - Added: TIDDIT SV for tumor only and tumor-normal
          - Coverage files from TIDDIT - .cov.bed.gz. 
              -  DECISION: Delivery to Ceasar or not?- suggestion from Teresita feedback
- [ ] Minor fix for vcf2cytosure and an update to ReadtheDocs (https://github.com/Clinical-Genomics/BALSAMIC/pull/966)
- [X]  WGS vcf2cytosure for tumor only and tumor-normal KM (https://github.com/Clinical-Genomics/BALSAMIC/pull/947)
- [X] Separate UMI and standard workflows - APJ - https://github.com/Clinical-Genomics/BALSAMIC/pull/932
- [X] Separate balsamic-qc analysis workflow - ARE- (https://github.com/Clinical-Genomics/BALSAMIC/pull/942)
- [X] Storing of QC files in HK. VI - Done

- [X] Editing of final VCF files for Scout display of variant caller information. - APJ - (https://github.com/Clinical-Genomics/BALSAMIC/pull/948)

- [x] Upload of UMI cases to Scout (mostly in cg) - VI
       - Testing ongoing.
       - Discuss with Chiara and Daniel before merging

- [ ] Switch to uploading MAF variants from DNAscope VCF from BALSAMIC (will be done by cg)
- [x] Need to change the names of the samples (Tumor/Normal) in VCF file to internal LIMS-ID to be compatible with the genotype [Issue](https://github.com/Clinical-Genomics/BALSAMIC/issues/882)

- [x]  gender from customer matches observed gender in data; could be added by cg to BALSAMIC config[ PR ](https://github.com/Clinical-Genomics/BALSAMIC/pull/955)- mostly done (VI)
	1) Used internally for different balsamic tools for gender (for eg: vcf2cytosure) 
	2) If used different tools for gender prediction, cross-check with the gender in balsamic config. QC check- if only time permits.

- [x] coverage-based QC values-Ongoing [Vadym Ivanchuk](mailto:vadym.ivanchuk@scilifelab.se) [Keyvan Elhami](mailto:keyvan.elhami@scilifelab.se)

- [ ] PON for TGA (secondary priority, only if time permits - APJ)  (Next release)

**ACTION:** Documentation of BALSAMIC towards customers. Need to extend readthedocs https://balsamic.readthedocs.io/en/latest/index.html Prioritised topics to add

- [x] Description of how SV/CNA calling and merging is done

- [x] Description of interpretation of SV/CNA calls

- [ ] Organise internal workshop/educational session on how CNA & SV calling is done

**Timeline**
Latest date to put in production: July 1*
Planned date to be ready with new balsamic release version: Jun 23, 2022
Validation cases analysis begins on stage: June 27, 2022

**Start of validation process:** 
Validation plan: @moahaegglund  takes the lead

- [ ] Plan for information to customers regarding new features

**Comment by ashwini06** [comment]
@khurrammaqbool : Is it possible to add the information about the SV/CNA callers (description and interpretation) part to the BALSAMIC readthedocs for this release?

**Comment by vwirta** [comment]
@moahaegglund do we have a draft validation and implementation plan already?

**Comment by khurrammaqbool** [comment]
> @khurrammaqbool : Is it possible to add the information about the SV/CNA callers (description and interpretation) part to the BALSAMIC readthedocs for this release?

Added in https://github.com/Clinical-Genomics/BALSAMIC/pull/960
