### ISSUE TITLE
[FAILED_ANALYSIS]: Missing zgrep/bgzip in vcf2cytosure container

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#968]
The current develop container `vcf2cytosure` doesn't contain the commands zgrep, bgzip, which fails the `vcf2cytosure_convert_tumor_normal` rule 

<img width="1438" alt="Screenshot 2022-06-23 at 12 05 34" src="https://user-images.githubusercontent.com/6302819/175275323-fc9ad926-8e79-4a3b-91cb-b409ceb9c5bc.png">

Container located here: `/home/proj/long-term-stage/cancer/UMI_analysis_runs_APJ/balsamic_cache/9.0.1/containers/vcf2cytosure_failed.sif`

Complete log: `/home/proj/stage/cancer/cases/fleetjay/logs.3/BALSAMIC.fleetjay.vcf2cytosure_convert_tumor_normal.54.sh_3191120.err`

**Comment by khurrammaqbool** [comment]
It was fixed. Please confirm in develop branch before posting an issue.

**Comment by ashwini06** [comment]
Fixed in #969
