### ISSUE TITLE
not all snvs/indels uploaded

### ISSUE THREAD

**Issue by terestahl** [Clinical-Genomics/BALSAMIC#974]
Hi
I would like if it is possible that for cases in which not all snvs/indels are uploaded to scout due to e.g. high mutational burden, e.g. case LI015 that this is indicated somewhere in scout. It is important that this is noted somewhere to avoid wrong interpretations
thanks

teresita

**Comment by ivadym** [comment]
This is being addressed in this issue since it will be solved by providing a TMB score: https://github.com/Clinical-Genomics/BALSAMIC/issues/912. Closing @Clinical-Genomics/cancer-bioinfo.
