### ISSUE TITLE
Disable TNhaplotyper for WGS tumor-normal

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/BALSAMIC#981]
**Is your feature request related to a problem? Please describe.**
TNhaplotyer was decided to be removed for WGS tumor-normal analysis, but it is still running for the workflow consuming significant compute resources.

**Describe the solution you'd like**
If possible, a clear and concise description of what you want to happen.

**Describe alternatives you've considered**
Disabling TNhaplotyper for WGS tumor-normal analysis.

**Current BALSAMIC version**
`balsamic 10.0.2`

**Comment by vwirta** [comment]
I think this should also be on the roadmap for next release.

**Comment by ivadym** [comment]
Closing via https://github.com/Clinical-Genomics/BALSAMIC/pull/988
