### ISSUE TITLE
BALSAMIC v11.0.0 release

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#989]
## Balsamic features for the next release:

> Balsamic v11/v12 discussion
> - [ ] Filtering strategy prior to upload to Scout
>     - [ ] ENCODE Blacklist regions 
>     - [ ] Merge TNhaplotyper and TNscope before annotation for T-only analysis.
>   - [ ] Post-annotation filtering
>     - [ ] Database of somatic and germline variants using DNAscope VCF?
>   - [ ] Ranking to order variants

## Annotation
  - [x] loqusdb CLI for WGS: https://github.com/Clinical-Genomics/BALSAMIC/pull/992
  - [x] loqusdb normal SNV Frequencies for WGS: https://github.com/Clinical-Genomics/BALSAMIC/pull/1012
  - [x] loqusdb normal SV Frequencies for WGS: https://github.com/Clinical-Genomics/BALSAMIC/pull/1013
  - [x] Swegen SV and SNV Frequencies for WGS:  https://github.com/Clinical-Genomics/BALSAMIC/pull/1014
  - [x] Update documentation

## Filtering strategy prior to upload to Scout
 - [x] Add Pre-annotation filtering, WGS: https://github.com/Clinical-Genomics/BALSAMIC/pull/1013
 - [x] Add research and clincal VCFs, WGS: https://github.com/Clinical-Genomics/BALSAMIC/pull/1007
 - [x]  Add Pre-annotation filtering, research and clinical VCF TGA: https://github.com/Clinical-Genomics/BALSAMIC/pull/1024
 - [x] CG: https://github.com/Clinical-Genomics/cg/issues/1559
 - [x] Split vep germline rules: https://github.com/Clinical-Genomics/BALSAMIC/pull/1018
 - [x] Implement filtering against loqusdb observations: https://github.com/Clinical-Genomics/BALSAMIC/pull/1029
 - [x] Implement filtering against swegen SV and SNV: https://github.com/Clinical-Genomics/BALSAMIC/pull/1029
 - [x] Update documentation

## Rescue filtered out variants:
  - [x] #986 https://github.com/Clinical-Genomics/BALSAMIC/pull/1021
  - [x] #975 https://github.com/Clinical-Genomics/BALSAMIC/pull/1021
  - [x] Update documentation

## Variant callers
- [x] Add CNVpytor for WGS T-only analysis: https://github.com/Clinical-Genomics/BALSAMIC/pull/994
- [ ] Add CNVpytor for WGS T-N analysis
- [x] Disable TNhaplotyper for WGS tumor-normal: https://github.com/Clinical-Genomics/BALSAMIC/pull/988
- [x] Disable TNhaplotyper for WGS tumor-only: https://github.com/Clinical-Genomics/BALSAMIC/pull/1006
- [x] Disable TNhaplotyper for TGS: https://github.com/Clinical-Genomics/BALSAMIC/pull/1022
- [x] Update documentation

## PON
- [x] Generate a panel of normal reference and use it as input for BALSAMIC analysis
  - [x] Balsamic CLI, https://github.com/Clinical-Genomics/BALSAMIC/pull/983
  - [x] CG` balsamic-pon` workflow & automatic fetching of a PON file for targeted analysis if available, https://github.com/Clinical-Genomics/cg/pull/1533
  - [x] Update documentation, https://github.com/Clinical-Genomics/atlas/pull/868

## Scout
- [x] Add CNVpytor PDF to Scout https://github.com/Clinical-Genomics/BALSAMIC/pull/1023

## Update delivery report
  - [x] Delivery report generated and delivered to Caesar, https://github.com/Clinical-Genomics/cg/pull/1536
  - [x] Delivery report to contain VCF file names that were used in analysis and uploaded to Scout, https://github.com/Clinical-Genomics/cg/pull/1536
  - [x] Show version information regarding tools used in analysis (extracted from the `config.json` file), https://github.com/Clinical-Genomics/cg/pull/1536
  - [ ] Delivery report for QC only analysis
  - [x] Update documentation

## File delivery
- [x] Update stored and delivered files (HERMES & CG)
- [x] Update documentation
- [ ] Update atlas

## Feature Update
- [ ] Version information regarding tools and databases used in analysis
- [x] Update cluster.json for cpu and time
- [ ] Add memory in cluster.json
- [x] Add cluster configuration for processes missing them and for the newly added processes: https://github.com/Clinical-Genomics/BALSAMIC/pull/1028
- [ ] Move fastq concatenation from CG to BALSAMIC (https://github.com/Clinical-Genomics/BALSAMIC/issues/993):
  - [ ] Remove concatenation for BALSAMIC in CG
  - [ ] Adapt the CLI to accept multiple reads and concatenate the fastqs

## Bug Fixes
- [x] invalid flag for mate and cluster resources https://github.com/Clinical-Genomics/BALSAMIC/pull/1025/files 
- [x] shell condition & remove tnhaplotyper https://github.com/Clinical-Genomics/BALSAMIC/pull/1022 
- [x] sam validation error https://github.com/Clinical-Genomics/BALSAMIC/pull/1019, https://github.com/Clinical-Genomics/BALSAMIC/pull/1027
- [x] cnvkit container and add input VCF file https://github.com/Clinical-Genomics/BALSAMIC/pull/995/files
- [x] cnvkit container https://github.com/Clinical-Genomics/BALSAMIC/pull/996/files
- [x] add missing R pachages to cnvkit container https://github.com/Clinical-Genomics/BALSAMIC/pull/997
- [x] rlang for cnvkit conatainer https://github.com/Clinical-Genomics/BALSAMIC/pull/998
- [x] Increase sambamba run time https://github.com/Clinical-Genomics/BALSAMIC/pull/1001
- [x] python packages causing test_workflow to fail https://github.com/Clinical-Genomics/BALSAMIC/pull/1008
- [x] sam validation error https://github.com/Clinical-Genomics/BALSAMIC/pull/1019
- [x] invalid flag for mate and update commands https://github.com/Clinical-Genomics/BALSAMIC/pull/1025
- [x] fixes cli documentation in the balsamic readthedocs https://github.com/Clinical-Genomics/BALSAMIC/pull/979

## Timeline:
To be defined (Nov).

**Comment by vwirta** [comment]
Discussion: move fastq concatenation from cg (on log-in node) to balsamic (enables use of slurm on hasta)  @ivadym @henrikstranneheim @moahaegglund
