### ISSUE TITLE
Move concatenation from cg to BALSAMIC

### ISSUE THREAD

**Issue by rannick** [Clinical-Genomics/BALSAMIC#993]
**Issue described in https://github.com/Clinical-Genomics/cg/issues/1551**

Moving the concatenation process to BALSAMIC renders the cg process lighter and takes advantage of the SLURM submission process and dependence handling already in BALSAMIC

Implementation plan:
Update cg to stop concatenating when Pipeline = BALSAMIC
cg links the same way but without concatenation -> symlinked fastq should be in case/fastq
Balsamic concatenates as a rule within the workflow
Concatenated fastq files in analysis/fastq
Because the concatenation are not stored, the downstream processes should not be affected

**Can be closed when**

- [ ] A new concatenation rule is added
- [ ] Checks for dependency handling
- [ ] Merging to dev
- [ ] Validation with next release

**Comment by ivadym** [comment]
Completed: https://github.com/Clinical-Genomics/BALSAMIC/pull/1069

---

FYI @Clinical-Genomics/cancer-bioinfo: 

To run balsamic cases from CG, please use the [remove-concatenation-balsamic](https://github.com/Clinical-Genomics/cg/tree/remove-concatenation-balsamic) branch (is up to date with the current Balsamic develop branch)
